---
title: ""
numbered: false
---
# Resumen {.unnumbered}
El estudio de la dinámica ecológica de las poblaciones localizadas en los límites de su distribución se considera esencial para establecer unas directrices de gestión adecuadas bajo las incertidumbres climáticas actuales. Las poblaciones de los márgenes posteriores suelen estar adaptadas a las condiciones ambientales locales en el límite de la amplitud ecológica de la especie, y a menudo muestran una persistencia a largo plazo. Las respuestas locales a los cambios ambientales pueden diferir de la respuesta media de la especie y tales diferencias pueden promover o dificultar la supervivencia de las poblaciones del margen posterior de distribución en las condiciones actuales de cambio global. Los robledales de *Quercus pyrenaica* en Sierra Nevada representan uno de los márgenes más meridionales del  área de distribución de esta especie. Están localizados en una región de montaña que ha servido de refugio para la especie. Al igual que otras formaciones forestales Mediterráneas, han estado sometidos a intensas presiones antropogénicas a lo largo del tiempo, lo que ha provocado una reducción de su extensión y una modificación de su composición florística y de sus patrones estructurales. Históricamente, los robledales han sido explotados en monte bajo para la obtención de leña, carbón vegetal, taninos. También se aclararon para generar grandes zonas de pastoreo. Todas estas actuaciones condujeron a una sobreexplotación de los robledales, de tal forma que la configuración actual de estas formaciones en Sierra Nevada parece depender en gran medida del uso del pasado. Sin embargo, a partir de la segunda mitad del siglo XX se produjo un abandono de las actividades tradicionales, resultando en una disminución de la presión antrópica sobre los ecosistemas forestales. Paradójicamente, muchos robledales presentan un estado de degradación avanzado (*e.g.* problemas de regeneración, altas densidades, estancamiento en el crecimiento, entre otros). Estos problemas pueden verse agravados en el contexto actual de cambio climático, sobre todo teniendo en cuenta la alta vulnerabilidad de esta especie al cambio climático, y especialmente para las zonas situadas en el borde posterior de su área de distribución como es Sierra Nevada. Por tanto, entender la ecología de las poblaciones situadas en el borde posterior de su distribución es clave para evaluar la respuesta de la especie a las condiciones ambientales cambiantes. El objetivo general de esta tesis doctoral es analizar la dinámica de funcionamiento frente al cambio global de los robledales de *Quercus pyrenaica* situados en Sierra Nevada, una región montañosa que representa uno de los límites geográficos de su distribución, donde estas formaciones han sido objeto de intensas presiones antrópicas. 

En el [capítulo @sec-intro] prestamos la introducción y los objetivos de la de la tesis doctoral. Posteriormente en el [capítulo @sec-metodologia] presentamos el área de estudio, realizamos algunos apuntes sobre *Quercus pyrenaica*, y esbozamos de forma genérica la metodología empleada en la realización de la tesis doctoral. 

En el [capítulo @sec-multivar], utilizando información ambiental de alta resolución e inventarios forestales, hemos determinado que la precipitación y la radiación son las variables más importantes que explican la distribución de las poblaciones de robledal dentro de su margen de distribución. Hemos identificado la existencia de tres grupos de poblaciones de robledal dentro de Sierra Nevada, debido principalmente a las condiciones microambientales. Encontramos una notable coincidencia entre la agrupación de las poblaciones derivada del análisis de las variables ambientales y la ordenación de las poblaciones según la composición de especies, lo que sugiere una relación entre la heterogeneidad de los factores ambientales y la variabilidad de la composición de especies para estos bosques. Esta diversidad de condiciones ecológicas para las poblaciones de *Quercus pyrenaica* situadas en este borde posterior, está en consonancia con los altos niveles de diversidad genética mostrados por las poblaciones de esta especie en Sierra Nevada. 

En el [capítulo @sec-coloniza] hemos estudiado el patrón de colonización de los cultivos de montaña por parte de *Quercus pyrenaica* en dos localidades de Sierra Nevada. Para ello analizamos la estructura de la fuente de semillas (bosques circundantes), la abundancia de arrendajo *Garrulus glandarius* (principal dispersor de bellotas de roble), y la abundancia de juveniles de *Quercus pyrenaica* en los cultivos abandonados. Asimismo caracterizamos en la medida de lo posible la historia de gestión antes y después del abandono de cultivos. Los resultados indican que se está produciendo una recolonización natural de las tierras de cultivo abandonadas por parte de *Quercus pyrenaica* en el borde posterior de su distribución. Encontramos diferencias en el patrón de colonización entre los sitios de estudio, que parecen estar relacionadas con las diferencias en la gestión anterior y posterior al abandono. Nuestros resultados demuestran que incluso en las actuales condiciones climáticas cada vez más secas, los bosques de *Quercus pyrenaica* son capaces de recuperar los antiguos campos de cultivo abandonados en el mismo nivel altitudinal donde el robledal es la vegetación potencial. Este proceso natural puede aportar soluciones para la conservación de la biodiversidad, y mejora la mitigación del cambio climático y la adaptación al mismo. 

En el [capítulo @sec-carbon] realizamos una estimación de la capacidad de secuestro de carbono por parte de los robledales de *Quercus pyrenaica* en Sierra Nevada. Asimismo, estudiamos las tendencias temporales de la provisión de este servicio ecosistémico. Los robledales de Sierra Nevada, al igual que los del resto de la Península Ibérica, han experimentado un aumento de la biomasa total en las últimas décadas, y por tanto de su capacidad como sumidero de carbono. Los datos estimados de secuestro de Carbono para los robledales de Sierra Nevada son superiores a los observados para otras zonas, indicando el alto potencial como sumidero de carbono de estos robledales, a pesar de estar situados en el límite sur de su distribución. Estos resultados parecen estar relacionados con el hecho de que los robledales de Sierra Nevada son relativamente más jóvenes en comparación con otros robledales (debido al intenso uso antrópico al que han estado sometidos), y las condiciones de refugio en las que se encuentran los robledales de Sierra Nevada. Por otro lado, se encontraron diferencias  respecto al potencial de secuestro de Carbono entre las poblaciones de robledal de Sierra Nevada. Aquellas poblaciones que han estado sometidas a menos perturbaciones antropogénicas presentan una una mayor riqueza estructural, que se ve reflejado en valores más altos de biomasa, y por tanto, en un mayor potencial de secuestro de carbono. 

En el [capítulo @sec-dendro], combinando el estudio del verdor de la vegetación derivado de imágenes de satélite, con análisis dendrocronológicos de árboles adultos, hemos analizado la resiliencia a la sequía del crecimiento primario y secundario de los robledales de Sierra Nevada. Las tendencias de crecimiento reflejaron una fuerte influencia del uso del suelo en la estructura forestal actual. El crecimiento primario y secundario de esta especie, aún siendo muy sensible a la disponibilidad de agua, mostró una alta resiliencia a corto y largo plazo a los eventos de sequía. Los altos valores de resiliencia observados sugieren que las poblaciones de robledal de Sierra Nevada se encuentran en el borde posterior geográfico pero no climático ni ecológico. La resiliencia a la sequía que muestran los robledales de Sierra Nevada no es espacialmente homogénea, debido a las diferencias en las condiciones ecológicas y a los legados del uso del suelo. La gran variabilidad en las respuestas entre sitios muy cercanos geográficamente, parece indicar que las respuestas a la sequía son dependientes del sitio y pueden variar drásticamente en gradientes espaciales extremadamente estrechos, como los que ocurren en regiones de montaña. En los últimos años se ha observado una tendencia positiva en la productividad primaria y en el crecimiento secundario de los robledales de Sierra Nevada. Esta respuesta es diferente a la tendencia negativa de crecimiento que cabría esperar para las poblaciones situadas en el borde sur de su distribución, tal y como se ha observado para otras especies templadas y mediterráneas. 

En el [capítulo @sec-onto] evaluamos cómo modificaciones en los patrones de disponibilidad de agua debido al cambio climático pueden afectar a la productividad de robledales de Sierra Nevada. Utilizando información derivada de imágenes de satélite junto con un sistema de ontologías, hemos observado la concurrencia de cambios en los patrones de innivación (disponibilidad de agua) y en la productividad primaria de los robledales de *Quercus pyrenaica*. En las zonas donde se ha detectado un adelanto en la fecha de fusión de la nieve, es decir, la nieve presenta una tendencia significativa a retirarse antes, también se ha observado un aumento significativo en la productividad primaria de verano para los robledales. Este acoplamiento entre las tendencias de producción primaria y las de duración de la nieve es más patente para las poblaciones de robledales occidentales de Sierra Nevada. Esta modificación en los patrones de disponibilidad de agua debido al cambio climático parece estar afectando a la productividad estacional de los robledales. 

Finalmente, en el [capítulo @sec-es] realizamos una revisión de los servicios ecosistémicos proporcionados por los robledales de *Quercus pyrenaica*, combinando una revisión bibliográfica para todo el área de su distribución con un análisis espacio-temporal de la provisión de servicios ecosistémicos, usando los robledales de Sierra Nevada como caso de estudio. Los robledales proporcionan una gran cantidad de servicios ecosistémicos. Además del papel que presentan estos bosques como proveedores de servicios de regulación (*e.g.* sumidero de carbono) o de provisión (*e.g.* uso de su madera para el envejecimiento del vino), se ha puesto de manifiesto la existencia de un gran número de servicios ecosistémicos culturales proporcionados por los bosques de *Quercus pyrenaica*. El análisis espacio-temporal de la provisión de servicios ecosistémicos reveló diferencias en la oferta de servicios ecosistémicos entre las poblaciones de robledal de Sierra Nevada, siendo las poblaciones del sur las que presentan mayores valores de servicios de regulación y las del norte las que presentan mayores valores de servicios culturales. Observamos una variación temporal en el suministro de servicios ecosistémicos. Hasta mediados del siglo pasado, los servicios de provisión predominaban sobre los servicios de regulación y culturales. El abandono de las actividades tradicionales provocó una disminución de los servicios de provisión a favor de los servicios de regulación y, en las últimas décadas, de los servicios culturales. Nuestra recopilación de datos a escala local nos ha permitido cuantificar muchos de los servicios ecosistémicos prestados por los bosques de *Quercus pyrenaica*, lo cual proporciona a los gestores del territorio una información muy valiosa que puede ayudar en la planificación de actuaciones de gestión y conservación de esta formación forestal. 

The study of the ecological dynamics of populations located at the limits of their distribution is considered essential to establish appropriate management guidelines under current climatic uncertainties. Rear-edge populations are usually adapted to local environmental conditions at the limit of the ecological range of the species, and often show long-term persistence. Local responses to environmental changes may differ from the average response of the species, and such differences may promote or hinder the survival of the rear-edge populations under current conditions of global change. *Quercus pyrenaica* populations of Sierra Nevada represent one of the southernmost margins of this species' range. They are located in a mountain region that has served as a refuge for the species. Like other Mediterranean forest formations, *Quercus pyrenaica* woodlands have been subjected to intense anthropogenic pressures over time, which has led to a reduction in their extent and a modification of their floristic composition and structural patterns. Historically, *Quercus pyrenaica* forests been exploited in coppices for firewood, charcoal and tannins. They were also cleared to generate large grazing areas. All these actions led to an overexploitation of the *Quercus pyrenaica* woodlands, so that the current configuration of these formations in the Sierra Nevada seems to depend largely on past use. However, from the second half of the 20th century onwards, traditional activities were abandoned, resulting in a decrease in anthropic pressure on forest ecosystems. Paradoxically, many *Quercus pyrenaica* forests present an advanced state of degradation (regeneration problems, high tree stand densities, growth stagnation, among others). These problems may be aggravated in the current context of climate change, especially considering the high vulnerability of *Quercus pyrenaica* to climate change, and particularly for populations located at the rear edge of its distribution range such as Sierra Nevada. Therefore, understanding the ecology of populations located at the rear edge of its distribution is key to evaluate the response of the species to changing environmental conditions. The general objective of this doctoral thesis is to analyze the functioning dynamics in the face of global change  of *Quercus pyrenaica* populations located in Sierra Nevada, a mountainous region that represents one of the geographical limits of its distribution, where these formations have been subject to intense anthropic pressures. 

In the [chapter @sec-intro] we stated the introduction and the objectives of the doctoral thesis. Then, in the [chapter @sec-metodologia] we present the study area, we describe some of the features of *Quercus pyrenaica*, and we outline in a generic way the methodology used to carried out the doctoral thesis. 

In the [chapter @sec-multivar], using high-resolution environmental information, and forest inventories, we have determined that precipitation and radiation are the most important environmental variables explaining the distribution of *Quercus pyrenaica* populations within their range. We identified three clusters of *Quercus pyrenaica* populations within the Sierra Nevada, mainly due to microenvironmental conditions. We also found a remarkable match between the populations clustering derived from analysis of environmental variables, and the ordination of the populations according to species composition, suggesting a relationship between the heterogeneity of environmental factors and the variability of species composition for these forests. The diversity of ecological conditions for *Quercus pyrenaica* populations in this rear edge are consistent with the high genetic diversity shown by populations of this oak in the Sierra Nevada. 

In the [chapter @sec-coloniza] we studied the colonization pattern of *Quercus pyrenaica* into abandoned mountain croplands, in two localities of Sierra Nevada. For this purpose, we analyzed the structure of the seed source (surrounding forests), the abundance of *Garrulus glandarius* jays (main disperser of oak acorns), and the abundance of *Quercus pyrenaica* juveniles in abandoned croplands. We also characterized as far as posibble the management history prior- and after- crop abandonment. The results indicate that natural recolonization of abandoned croplands by *Quercus pyrenaica* is occurring at the rear edge of their distribution. We found differences in the colonization pattern among study sites, which seems to be related to differences in pre- and post-abandonment management. Our results demostrate that even in the current increasingly dry climatic conditions, *Quercus pyrenaica* woodlands are able to recover the abandoned former arable fields at the same altitudinal level where oak woodland is the potential vegetation. This natural process can provide solutions for biodiversity conservation, and enhances climate change mitigation and adaptation. 

In the [chapter @sec-carbon] we estimate the carbon sequestration capacity of *Quercus pyrenaica* forests in Sierra Nevada. We also studied temporal trends in the provision of this ecosystem service. The *Quercus pyrenaica* woodlands of Sierra Nevada, like those of the rest of the Iberian Peninsula, have experienced an increase in total biomass in recent decades, and therefore in their capacity as a carbon sink. The estimated carbon sequestration data for the *Quercus pyrenaica* forests of Sierra Nevada are higher than those observed for other areas, indicating the high potential of these oak forests as carbon sinks, despite being located at the southern limit of their distribution. These results seem to be related to the fact that the Sierra Nevada *Quercus pyrenaica* forests are relatively younger compared to other oak forests (due to the intense anthropic use to which they have been subjected), and the refuge conditions in which the Sierra Nevada oak forests are found. On the other hand, differences of carbon sequestration potential among Sierra Nevada *Quercus pyrenaica* populations were found. Those populations that have been subjected to less anthropogenic disturbances have a greater structural richness, which is reflected in higher biomass values, and therefore, in a higher carbon sequestration potential. 

In the [chapter @sec-dendro], we analyzed the resilience to drought of relict Mediterranean *Quercus pyrenaica* populations in Sierra Nevada in relation to historical records of land use, combining dendroecological growth of adult trees and greenness (EVI) as proxies for secondary and primary growth. The growth trends reflected a strong influence of old land-use legacies in the current forest structure. Trees were highly sensitive to moisture availability, but both primary growth and secondary growth expressed high resilience to drought events over the short and the long term. The high values of resilience observed suggest that the studied *Quercus pyrenaica* populations are located in a geographical but not a climatic or ecological rear edge. Resilience of oak stands to drought events was not spatially homogeneous across the mountain range, due to differences in ecological conditions and/or past management legacies. The large variability in the response to climate along the rear edge seems to indicate that responses to drought are site-dependent and can vary dramatically along extremely narrow spatial gradients, such as those occurring in mountain regions. In recent years, a positive trend in primary productivity and secondary growth of Sierra Nevada oak forests has been observed. This response is different from the negative growth trend that would be expected for populations located at the rear edge of their distribution, as has been observed for other temperate and Mediterranean species. 

In the [chapter @sec-onto] we evaluate how modifications in water availability patterns due to climate change may affect the productivity of Sierra Nevada *Quercus pyrenaica* woodlands. Using information derived from satellite imagery together with an ontology system, we observed the concurrence of changes in snowfall patterns (water availability) and primary productivity of oak woodlands in the Sierra Nevada. In areas where we have detected an earlier snowmelt date, *i.e.* snow cover present a significant trend to melt earlier, we have also observed a significant increase in summer primary productivity for *Quercus pyrenaica* woodlands. This coupling between primary production and snow duration trends is most apparent for western oak woodland populations in the Sierra Nevada. This modification in water availability patterns due to climate change appears to be affecting the seasonal productivity of oak woodlands.

Finally, in the [chapter @sec-es] we review the ecosystem services provided by *Quercus pyrenaica* woodlands, combining a general literature review (*e.g.* for the entire area of their distribution), with a spatio-temporal analysis of ecosystem service supply, using the Sierra Nevada *Quercus pyrenaica* woodlands as a case study. *Quercus pyrenaica* forests provide a large number of ecosystem services. In addition to the role of these forests as providers of regulating services (*e.g.* carbon sink) or provisioning services (*e.g.* use of their wood for wine aging), the existence of a large number of cultural ecosystem services provided by oak forests has been revealed. Spatio-temporal analysis of ecosystem services revealed differences in the supply of ecosystem services among Sierra Nevada oak woodland populations, with southern populations having higher values of regulating services and northern populations having higher values of cultural services. We observed temporal variation in the supply of ecosystem services. Until the middle of the last century, provisioning services predominated over regulating and cultural services. The abandonment of traditional activities led to a decline in provisioning services in favor of regulating services and, in recent decades, cultural services. Our compilation of data at the local scale has allowed us to quantify many of the ecosystem services provided by the *Quercus pyrenaica* forests, which provides land managers with valuable information that can help in the planning of management and conservation actions for this forest formation.
