<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Carbon sequestration of coppiced forests of Q. pyrenaica. An study case from the rear-edge of its distribution – Tesis Quarto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chap06-dendro.html" rel="next">
<link href="./chap04-coloniza.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chap05-carbon.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Carbon sequestration of coppiced forests of <em>Q. pyrenaica</em>. An study case from the rear-edge of its distribution</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tesis Quarto</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Título de tu tesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción General</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap02-metodologia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Metodología general</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap03-multivariante.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ecological diversity within rear-edge: a case study from Mediterranean <em>Quercus pyrenaica</em> Willd.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap04-coloniza.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Colonization pattern of abandoned croplands by <em>Q. pyrenaica</em> in a Mediterranean mountain region</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap05-carbon.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Carbon sequestration of coppiced forests of <em>Q. pyrenaica</em>. An study case from the rear-edge of its distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap06-dendro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land-use legacies and climate change as a double challenge to oak forest resilience: mismatches of geographical and ecological rear edges</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Referencias</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-carbon-intro" id="toc-sec-carbon-intro" class="nav-link active" data-scroll-target="#sec-carbon-intro"><span class="header-section-number">6.1</span> Introduction</a></li>
  <li><a href="#sec-carbon-mat" id="toc-sec-carbon-mat" class="nav-link" data-scroll-target="#sec-carbon-mat"><span class="header-section-number">6.2</span> Material and Methods</a>
  <ul class="collapse">
  <li><a href="#sec-carbon-mat-studysite" id="toc-sec-carbon-mat-studysite" class="nav-link" data-scroll-target="#sec-carbon-mat-studysite"><span class="header-section-number">6.2.1</span> Study site and oak woodlands</a></li>
  <li><a href="#sec-carbon-mat-field-data" id="toc-sec-carbon-mat-field-data" class="nav-link" data-scroll-target="#sec-carbon-mat-field-data"><span class="header-section-number">6.2.2</span> Biomass data</a></li>
  <li><a href="#sec-carbon-mat-biomass" id="toc-sec-carbon-mat-biomass" class="nav-link" data-scroll-target="#sec-carbon-mat-biomass"><span class="header-section-number">6.2.3</span> Biomass and Carbon estimation</a></li>
  <li><a href="#sec-carbon-mat-lidar" id="toc-sec-carbon-mat-lidar" class="nav-link" data-scroll-target="#sec-carbon-mat-lidar"><span class="header-section-number">6.2.4</span> Airborne Laser Scanning (ALS) data and processing</a></li>
  <li><a href="#sec-carbon-mat-cmpas" id="toc-sec-carbon-mat-cmpas" class="nav-link" data-scroll-target="#sec-carbon-mat-cmpas"><span class="header-section-number">6.2.5</span> Cartography of biomass and C stocks</a></li>
  </ul></li>
  <li><a href="#sec-carbon-mat-temporal" id="toc-sec-carbon-mat-temporal" class="nav-link" data-scroll-target="#sec-carbon-mat-temporal"><span class="header-section-number">6.3</span> Temporal evolution of tree biomass in <em>Q. pyrenaica</em> stands</a></li>
  <li><a href="#sec-carbon-analysis" id="toc-sec-carbon-analysis" class="nav-link" data-scroll-target="#sec-carbon-analysis"><span class="header-section-number">6.4</span> Statistical analysis</a></li>
  <li><a href="#sec-carbon-results" id="toc-sec-carbon-results" class="nav-link" data-scroll-target="#sec-carbon-results"><span class="header-section-number">6.5</span> Results</a>
  <ul class="collapse">
  <li><a href="#sec-carbon-results-modelling" id="toc-sec-carbon-results-modelling" class="nav-link" data-scroll-target="#sec-carbon-results-modelling"><span class="header-section-number">6.5.1</span> Biomass modelling</a></li>
  <li><a href="#sec-carbon-results-cartography" id="toc-sec-carbon-results-cartography" class="nav-link" data-scroll-target="#sec-carbon-results-cartography"><span class="header-section-number">6.5.2</span> Differences on biomass and C stock among Pyrenean oak populations</a></li>
  <li><a href="#sec-carbon-results-prediction" id="toc-sec-carbon-results-prediction" class="nav-link" data-scroll-target="#sec-carbon-results-prediction"><span class="header-section-number">6.5.3</span> Predictions of stand biomass</a></li>
  <li><a href="#sec-carbon-results-temporal" id="toc-sec-carbon-results-temporal" class="nav-link" data-scroll-target="#sec-carbon-results-temporal"><span class="header-section-number">6.5.4</span> Temporal evolution of biomass in <em>Q. pyrenaica</em> stands</a></li>
  </ul></li>
  <li><a href="#sec-carbon-discussion" id="toc-sec-carbon-discussion" class="nav-link" data-scroll-target="#sec-carbon-discussion"><span class="header-section-number">6.6</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#sec-carbon-discussion-sn" id="toc-sec-carbon-discussion-sn" class="nav-link" data-scroll-target="#sec-carbon-discussion-sn"><span class="header-section-number">6.6.1</span> Carbon sequestration by Sierra Nevada oak woodlands.</a></li>
  <li><a href="#sec-carbon-discussion-factors" id="toc-sec-carbon-discussion-factors" class="nav-link" data-scroll-target="#sec-carbon-discussion-factors"><span class="header-section-number">6.6.2</span> Factors explaining biomass in the oak woodlands</a></li>
  <li><a href="#sec-carbon-discussion-differences" id="toc-sec-carbon-discussion-differences" class="nav-link" data-scroll-target="#sec-carbon-discussion-differences"><span class="header-section-number">6.6.3</span> Biomass differences within oak woodlands</a></li>
  <li><a href="#sec-carbon-discussion-trends" id="toc-sec-carbon-discussion-trends" class="nav-link" data-scroll-target="#sec-carbon-discussion-trends"><span class="header-section-number">6.6.4</span> Trends of carbon sequestration by oak woodlands</a></li>
  </ul></li>
  <li><a href="#sec-carbon-discussion-management" id="toc-sec-carbon-discussion-management" class="nav-link" data-scroll-target="#sec-carbon-discussion-management"><span class="header-section-number">6.7</span> Management implications</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-carbon" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Carbon sequestration of coppiced forests of <em>Q. pyrenaica</em>. An study case from the rear-edge of its distribution</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Antonio J. Pérez-Luque</strong>; Mihai Tanase; Cristina Aponte &amp; Regino Zamora (In prep.)</p>
<section id="sec-carbon-intro" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-carbon-intro"><span class="header-section-number">6.1</span> Introduction</h2>
<p>Forest ecosystems are suppliers of several ecosystems services to humans <span class="citation" data-cites="Iversonetal2018EcosystemServices MartinezPasturetal2018EcosystemServices NoceSantini2018MediterraneanForest">(<a href="#ref-Iversonetal2018EcosystemServices" role="doc-biblioref">Iverson et al. 2018</a>, <a href="#ref-MartinezPasturetal2018EcosystemServices" role="doc-biblioref">Martínez Pastur et al. 2018</a>, <a href="#ref-NoceSantini2018MediterraneanForest" role="doc-biblioref">Noce and Santini 2018</a>)</span>. Forest ecosystem services include provisioning services (<em>e.g.</em> wood and non-wood forest products), regulating services (<em>e.g.</em> climate regulation), habitat or support services, and cultural services. In Mediterranean region, humans have been exploiting forest resources for centuries <span class="citation" data-cites="ValbuenaCarabanaetal2010HistoricalRecent">(<a href="#ref-ValbuenaCarabanaetal2010HistoricalRecent" role="doc-biblioref">Valbuena-Carabaña et al. 2010</a>)</span>, however in the last decades a strong abandonment of traditional activities in mountains regions have been observed, mainly due to the rural exodus and the low economic value of forest products activities <span class="citation" data-cites="Chauchardetal2007PatternsLanduse Debusscheetal1999MediterraneanLandscape MacDonaldetal2000AgriculturalAbandonment">(<a href="#ref-Debusscheetal1999MediterraneanLandscape" role="doc-biblioref">Debussche et al. 1999</a>, <a href="#ref-MacDonaldetal2000AgriculturalAbandonment" role="doc-biblioref">MacDonald et al. 2000</a>, <a href="#ref-Chauchardetal2007PatternsLanduse" role="doc-biblioref">Chauchard et al. 2007</a>)</span>. As a result, many forests currently have high tree-density stands, with an increased competition for resources, which can lead to widespread weakening of stand, increasing the vulnerability of forests to abiotic and biotic disturbances <span class="citation" data-cites="Tardieuetal2018HumanNeeds">(<a href="#ref-Tardieuetal2018HumanNeeds" role="doc-biblioref">Tardieu et al. 2018</a>)</span>. This may be especially relevant for forests stands located at the rear-edge of the species distribution <span class="citation" data-cites="HampePetit2005ConservingBiodiversity">(<a href="#ref-HampePetit2005ConservingBiodiversity" role="doc-biblioref">Hampe and Petit 2005</a>)</span>, which are usually considered more vulnerable to climate change compared with populations at the centre of a species’ range <span class="citation" data-cites="Fadyetal2016EvolutionbasedApproach Pirononetal2017GeographicVariation Rehmetal2015LosingYour">(<a href="#ref-Rehmetal2015LosingYour" role="doc-biblioref">Rehm et al. 2015</a>, <a href="#ref-Fadyetal2016EvolutionbasedApproach" role="doc-biblioref">Fady et al. 2016</a>, <a href="#ref-Pirononetal2017GeographicVariation" role="doc-biblioref">Pironon et al. 2017</a>)</span>.</p>
<p><em>Q. pyrenaica</em> (Pyrenean oak) is a marcescent Mediterranean tree species widely distributed throughout southwestern France and the Iberian Peninsula, reaching their southern limit in mountain areas of northern Morocco <span class="citation" data-cites="Franco1990Quercus">(<a href="#ref-Franco1990Quercus" role="doc-biblioref">Franco 1990</a>)</span>. The rear-edge populations of this species are restricted to high-mountain areas where these populations persists as isolated nuclei with ecological conditions very different from those of the main distribution area <span class="citation" data-cites="PerezLuqueetal2021EcologicalDiversity">(<a href="#ref-PerezLuqueetal2021EcologicalDiversity" role="doc-biblioref">Pérez-Luque et al. 2021</a>)</span>. Due to its ability to resprout from stumps and the entire root system, most stands of this species have been coppiced for centuries mainly for firewood, charcoal, tannins and woody pasture production <span class="citation" data-cites="SanchezPalomaresetal2008EstacionesEcologicas XimenezdeEmbun1961MonteBajo">(<a href="#ref-XimenezdeEmbun1961MonteBajo" role="doc-biblioref">Ximénez de Embún 1961</a>, <a href="#ref-SanchezPalomaresetal2008EstacionesEcologicas" role="doc-biblioref">Sánchez Palomares et al. 2008</a>)</span>. All these anthropogenic processes have transformed native woodland structures <span class="citation" data-cites="Tarregaetal2006ForestStructure">(<a href="#ref-Tarregaetal2006ForestStructure" role="doc-biblioref">Tárrega et al. 2006</a>)</span>, and nowadays it is difficult to find stands of this oak that can be qualified as natural or pristine forests <span class="citation" data-cites="RuizdelaTorre2006FloraMayor">(<a href="#ref-RuizdelaTorre2006FloraMayor" role="doc-biblioref">Ruiz de la Torre 2006</a>)</span>. Paradoxically, after the diminution of human pressure on woodlands over the last decades, the abandonded coppices of <em>Q. pyrenaica</em> present an advanced state of degradation with important ecological, economic and social problems <span class="citation" data-cites="Bravoetal2008SelviculturaMontes MontoyaMeson1979SituacionActual Piqueetal2018Spain PiqueVericat2015EvolutionPerspectives Vericatetal2012GestionAdaptativa">(<a href="#ref-MontoyaMeson1979SituacionActual" role="doc-biblioref">Montoya and Mesón 1979</a>, <a href="#ref-Bravoetal2008SelviculturaMontes" role="doc-biblioref">Bravo et al. 2008</a>, <a href="#ref-Vericatetal2012GestionAdaptativa" role="doc-biblioref">Vericat et al. 2012</a>, <a href="#ref-PiqueVericat2015EvolutionPerspectives" role="doc-biblioref">Piqué and Vericat 2015</a>, <a href="#ref-Piqueetal2018Spain" role="doc-biblioref">Piqué et al. 2018</a>)</span>. Due to the importance of this species, several management practices (<em>e.g.</em>&nbsp;conversion to high forest) have been proposed to improve the state of abandoned coppices <span class="citation" data-cites="Bravoetal2008SelviculturaMontes Montoya1982SelviculturaOrdenacion Montoya1983UsosAlternativos Serradaetal1992CoppiceSystem Vericatetal2012GestionAdaptativa">(<a href="#ref-Montoya1982SelviculturaOrdenacion" role="doc-biblioref">Montoya 1982</a>, <a href="#ref-Montoya1983UsosAlternativos" role="doc-biblioref">1983</a>, <a href="#ref-Serradaetal1992CoppiceSystem" role="doc-biblioref">Serrada et al. 1992</a>, <a href="#ref-Bravoetal2008SelviculturaMontes" role="doc-biblioref">Bravo et al. 2008</a>, <a href="#ref-Vericatetal2012GestionAdaptativa" role="doc-biblioref">Vericat et al. 2012</a>)</span>, although they have not been very successful, partly due to the lack of a comprehensive understanding of the physiological mechanisms underpinning tree stagnation <span class="citation" data-cites="Salomonetal2017GeneralFailure ValbuenaCarabanaGil2017CentenaryCoppicing">(<a href="#ref-Salomonetal2017GeneralFailure" role="doc-biblioref">Salomón et al. 2017</a>, <a href="#ref-ValbuenaCarabanaGil2017CentenaryCoppicing" role="doc-biblioref">Valbuena-Carabaña and Gil 2017</a>)</span>. In view of this situation, it is essential to seek for alternative management practices to the traditional uses of the abandoned coppices <span class="citation" data-cites="MesonMontoya1985VegetacionForestal SanMigueletal2012BosquesMatorrales">(<a href="#ref-MesonMontoya1985VegetacionForestal" role="doc-biblioref">Mesón and Montoya 1985</a>, <a href="#ref-SanMigueletal2012BosquesMatorrales" role="doc-biblioref">San Miguel et al. 2012</a>)</span>. Some management alternatives based on pastoral use have been proposed <span class="citation" data-cites="HerreraCalvo2016UsoPastoral">(<a href="#ref-HerreraCalvo2016UsoPastoral" role="doc-biblioref">Herrera Calvo 2016</a>)</span>, but to our knowledge few proposals have focused on the provision of the ecosystem services provided by this oak forests <span class="citation" data-cites="Piqueetal2018Spain PiqueVericat2015EvolutionPerspectives">(<a href="#ref-PiqueVericat2015EvolutionPerspectives" role="doc-biblioref">Piqué and Vericat 2015</a>, <a href="#ref-Piqueetal2018Spain" role="doc-biblioref">Piqué et al. 2018</a>)</span>.</p>
<p>The carbon sequestration is one of the most relevant ecosystems services provided by Mediterranean forests <span class="citation" data-cites="Gauquelinetal2018MediterraneanForests NoceSantini2018MediterraneanForest">(<a href="#ref-NoceSantini2018MediterraneanForest" role="doc-biblioref">Noce and Santini 2018</a>, <a href="#ref-Gauquelinetal2018MediterraneanForests" role="doc-biblioref">Gauquelin et al. 2018</a>)</span>. Carbon stock can be assumed as an indicator of the capacity of ecosystems to contribute to climate regulation because their potential to influence atmospheric CO<sub>2</sub> concentration <span class="citation" data-cites="Lauterbach2007AssessmentExisting Luyssaertetal2008OldgrowthForests">(<a href="#ref-Lauterbach2007AssessmentExisting" role="doc-biblioref">Lauterbach 2007</a>, <a href="#ref-Luyssaertetal2008OldgrowthForests" role="doc-biblioref">Luyssaert et al. 2008</a>)</span>. Mediterranean forests represent a carbon sink expected to increase over coming decades <span class="citation" data-cites="Canellasetal2017CarbonSequestration PasalodosTatoetal2017EvaluationTree">(<a href="#ref-Canellasetal2017CarbonSequestration" role="doc-biblioref">Cañellas et al. 2017</a>, <a href="#ref-PasalodosTatoetal2017EvaluationTree" role="doc-biblioref">Pasalodos-Tato et al. 2017</a>)</span>. Improving carbon estimation and our understanding of the effects of forest management could be useful for forest managers, which could include carbon sequestration among the different objectives pursued in the forests management <span class="citation" data-cites="RuizPeinadoetal2017ForestManagement">(<a href="#ref-RuizPeinadoetal2017ForestManagement" role="doc-biblioref">Ruiz-Peinado et al. 2017</a>)</span>. Several studies have been conducted to determine carbon sequestration by forest ecosystems in the Mediterranean region based on data from forest carbon inventories, field measurements, remote sensing, laser scanning and growth simulation <span class="citation" data-cites="Canellasetal2008SilvicultureCarbon Chiesietal2005ModellingCarbon Garciaetal2010EstimatingBiomass GuerraHernandezetal2016ComparisonALS Simonsonetal2016ModellingAboveground Vayredaetal2012SpatialPatterns">(<a href="#ref-Chiesietal2005ModellingCarbon" role="doc-biblioref">Chiesi et al. 2005</a>, <a href="#ref-Canellasetal2008SilvicultureCarbon" role="doc-biblioref">Cañellas et al. 2008</a>, <a href="#ref-Garciaetal2010EstimatingBiomass" role="doc-biblioref">García et al. 2010</a>, <a href="#ref-Vayredaetal2012SpatialPatterns" role="doc-biblioref">Vayreda et al. 2012</a>, <a href="#ref-GuerraHernandezetal2016ComparisonALS" role="doc-biblioref">Guerra-Hernández et al. 2016</a>, <a href="#ref-Simonsonetal2016ModellingAboveground" role="doc-biblioref">Simonson et al. 2016</a>)</span>. LIDAR (Light Detection And Ranging) has emerged as an effective technique for quantifying aboveground biomass in forests <span class="citation" data-cites="Belandetal2019PromotingUse Lefskyetal2002LidarRemote Xiaoetal2019RemoteSensing">(<a href="#ref-Lefskyetal2002LidarRemote" role="doc-biblioref">Lefsky et al. 2002</a>, <a href="#ref-Belandetal2019PromotingUse" role="doc-biblioref">Beland et al. 2019</a>, <a href="#ref-Xiaoetal2019RemoteSensing" role="doc-biblioref">Xiao et al. 2019</a>)</span> and has been also used for quantifying carbon stocks <span class="citation" data-cites="Simonsonetal2016ModellingAboveground Zhaoetal2018UtilityMultitemporal">(<a href="#ref-Simonsonetal2016ModellingAboveground" role="doc-biblioref">Simonson et al. 2016</a>, <a href="#ref-Zhaoetal2018UtilityMultitemporal" role="doc-biblioref">Zhao et al. 2018</a>)</span>. In this study we combined Airborne Laser Scanning LIDAR data and field inventories to estimate the biomass of Pyrenean oak woodlands (<em>Q. pyrenaica</em>) of Sierra Nevada (southern Spain), and then to assess the carbon sequestration capacity of those forests and their role as carbon sink. The specific objectives are: <em>(i)</em> to estimate the potential capacity of these ecosystems to sequester carbon dioxide and to evaluate the temporal trends for this ecosystem service; <em>(ii)</em> to explore the factors that explain the C stock for <em>Q. pyrenaica</em> woodland in Sierra Nevada; and <em>(ii)</em> to analyse the differences in biomass and carbon sequestration among oak populations within this mountain region.</p>
</section>
<section id="sec-carbon-mat" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-carbon-mat"><span class="header-section-number">6.2</span> Material and Methods</h2>
<section id="sec-carbon-mat-studysite" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-carbon-mat-studysite"><span class="header-section-number">6.2.1</span> Study site and oak woodlands</h3>
<p>The study area is located in Sierra Nevada (37°N, 3°W), a high-mountain range of southern of Andalusia with elevations of up to 3 482 <em>m.a.s.l.</em>. The climate is Mediterranean, characterized by cold winters and hot summers, with pronounced summer drought and increasing aridity with decreasing altitude, and marked variability according to elevation and aspect. In Sierra Nevada there are eight Pyrenean oak populations (2 400 ha), distributed from 1 100 to 2 000 <em>m.a.s.l.</em> and often associated with major river valleys. Those eight oak populations could be grouped in three clusters, based on their structure and floristic composition: the northern (N), the northwestern (NW), and the southern (S) clusters <span class="citation" data-cites="PerezLuqueetal2021EcologicalDiversity">(<a href="#ref-PerezLuqueetal2021EcologicalDiversity" role="doc-biblioref">Pérez-Luque et al. 2021</a>)</span>. <em>Q. pyrenaica</em> woodlands in this mountain region represent a rear edge of their habitat distribution <span class="citation" data-cites="HampePetit2005ConservingBiodiversity">(<a href="#ref-HampePetit2005ConservingBiodiversity" role="doc-biblioref">Hampe and Petit 2005</a>)</span>. They are the richest forest formation in vascular plant species of Sierra Nevada, containing several endemic and endangered plant species <span class="citation" data-cites="Loriteetal2008PhytosociologicalReview">(<a href="#ref-Loriteetal2008PhytosociologicalReview" role="doc-biblioref">Lorite et al. 2008</a>)</span>, and they also harbor high levels of intraspecific genetic diversity <span class="citation" data-cites="ValbuenaCarabanaGil2013GeneticResilience">(<a href="#ref-ValbuenaCarabanaGil2013GeneticResilience" role="doc-biblioref">Valbuena-Carabaña and Gil 2013</a>)</span>. However, these relict forests have undergone intensive human use throughout history <span class="citation" data-cites="CamachoOlmedoetal2002DinamicaEvolutiva">(<a href="#ref-CamachoOlmedoetal2002DinamicaEvolutiva" role="doc-biblioref">Camacho-Olmedo et al. 2002a</a>)</span>. Furthermore, the conservation status of this species for southern Spain is considered <em>"Vulnerable"</em> and it is expected to suffer from climate change, reducing its suitable habitats in the near future <span class="citation" data-cites="GeaIzquierdoetal2013GrowthProjections GeaIzquierdoetal2017RiskyFuture Benitoetal2011SimulatingPotential">(<a href="#ref-Benitoetal2011SimulatingPotential" role="doc-biblioref">Benito et al. 2011</a>, <a href="#ref-GeaIzquierdoetal2013GrowthProjections" role="doc-biblioref">Gea-Izquierdo et al. 2013</a>, <a href="#ref-GeaIzquierdoetal2017RiskyFuture" role="doc-biblioref">2017</a>)</span>.</p>
<div id="tbl-carbon-biomasseq" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carbon-biomasseq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Allometric equations to compute biomass fraction of <em>Q. pyrenaica</em> RuizPeinadoetal2012BiomassModels. DBH: Diameter at breast height; h: Tree height.
</figcaption>
<div aria-describedby="tbl-carbon-biomasseq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>ll@ Tree fraction</th>
<th>Equation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Stem and thick branches</td>
<td>*** = 0.0261 DBH2</td>
</tr>
<tr class="even">
<td>Medium branches</td>
<td>*** = 0.0260 DBH2 + 0.536 h + 0.00538 DBH2 h</td>
</tr>
<tr class="odd">
<td>Thin branches and leaves</td>
<td>*** = 0.898 DBH 0.445 h</td>
</tr>
<tr class="even">
<td>Roots</td>
<td>*** = 0.143 DBH2</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-carbon-mat-field-data" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="sec-carbon-mat-field-data"><span class="header-section-number">6.2.2</span> Biomass data</h3>
<p>We used two types of field data, inventories (previous collected, 90 plots), and field data (20 plots) collected for this study.</p>
<div id="tbl-carbon-inventories" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carbon-inventories-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Field data used to compute the biomass of <em>Q. pyrenaica</em>. For DBH (Diameter at breast height) and Tree height, the average values and range (in brackets) are shown.
</figcaption>
<div aria-describedby="tbl-carbon-inventories-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>lllllll [0.5pt] <strong>Source</strong></th>
<th><strong>n plots</strong></th>
<th>area (m2)</th>
<th><strong>year</strong></th>
<th><strong># trees</strong></th>
<th><strong>DBH (cm)</strong></th>
<th><strong>Tree height (m)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dataset of Global Change, altitudinal range shift and colonization of degraded habitats in Mediterranean mountains (MIGRAME) PerezLuqueetal2015DatasetMIGRAME</td>
<td>30</td>
<td>300</td>
<td>2012</td>
<td>1422</td>
<td>10.77 (7.5–105)</td>
<td>4.27 (1.1–18)</td>
</tr>
<tr class="even">
<td>Sierra Nevada Global Change Observatory Aspizuaetal2012EvaluacionGestion,Zamoraetal2017GlobalChange</td>
<td>3</td>
<td>400</td>
<td>2011,2012</td>
<td>122</td>
<td>19.03 (8–36)</td>
<td>9.57 (4.7–16.4)</td>
</tr>
<tr class="odd">
<td>Protection of key ecosystem services by adaptive management of climate change endangered mediterranean socioecosystems BareaAzconetal2017LIFEADAPTAMED. Forest inventories from Action C6 of the project</td>
<td>16</td>
<td>706.85</td>
<td>2015, 2017</td>
<td>650</td>
<td>13.26 (7.6–50)</td>
<td>6.96 (3.6–14)</td>
</tr>
<tr class="even">
<td>Protection of key ecosystem services by adaptive management of climate change endangered mediterranean socioecosystems BareaAzconetal2017LIFEADAPTAMED. Forest inventories associated with dendrochronological plots</td>
<td>2</td>
<td>254.47–530.93</td>
<td>2018</td>
<td>191</td>
<td>7.73 (2.1–42.2)</td>
<td>4.48 (1.1–13.6)</td>
</tr>
<tr class="odd">
<td>Forest inventories from dendroecological research PerezLuqueetal2020LanduseLegacies</td>
<td>39</td>
<td>314.16</td>
<td>2018</td>
<td>457</td>
<td>26.3 (2.86–122.55)</td>
<td>10.31 (3–20.4)</td>
</tr>
<tr class="even">
<td>This study field data</td>
<td>23</td>
<td>254.47–706.85</td>
<td>2019,2020</td>
<td>382</td>
<td>24.32 (2.91–67)</td>
<td>11.42 (1.7–20.6)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Field data were obtained from a compilation of several forest inventories carried out in the Sierra Nevada mountain range (Table&nbsp;<a href="#tab:carbon:inventories" data-reference-type="ref" data-reference="tab:carbon:inventories">[tab:carbon:inventories]</a>). In a first step, we selected plots included in the current distribution of Pyrenean oak in Sierra Nevada <span class="citation" data-cites="PerezLuqueetal2019MapEcosystems">(<a href="#ref-PerezLuqueetal2019MapEcosystems" role="doc-biblioref">Pérez-Luque et al. 2019</a>)</span>. Then, only plots with complete information (<em>i.e.</em> those where all tree individual with dbh &gt; 7.5 cm were measured), and pure stands (<em>i.e.</em> <em>Q. pyrenaica</em> composition &gt; 70%) were selected. A spatial filter was also applied to discard overlapping plots. We also discarded old forests inventories (<em>i.e.</em> more than 10 years). All selected plots were measured between 2012 and 2020. In order to have a representation of all the oak populations, additional circular plots (radius 9 to 16 m) were sampled between October 2019 and March 2020. The plots were selected in proportion to the extension of the different ecological strata, providing representative stands with a variety of stand structure and site conditions. A sub-meter global satellite receiver (Leica Zeno 20 GIS, Leica Geosystems, Switzerland) was used to survey plot centers. We tagged and measured all tree individuals within the circular plot. Diameter at breast height (DBH) was measured to the nearest 0.1 cm with a graduated caliper, and tree height was measured to the nearest 0.1 m with a hypsometer. Azimuth and distance of each measured tree from the plot center were also recorded. A total of 113 plots (254 to 400 m<span class="math inline">\(^2\)</span>) were finally selected with a total of 3 224 measured trees (Table&nbsp;<a href="#tab:carbon:inventories" data-reference-type="ref" data-reference="tab:carbon:inventories">[tab:carbon:inventories]</a>).</p>
</section>
<section id="sec-carbon-mat-biomass" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="sec-carbon-mat-biomass"><span class="header-section-number">6.2.3</span> Biomass and Carbon estimation</h3>
<p>The biomass of individual trees was estimated according to published species-specific allometric equations <span class="citation" data-cites="RuizPeinadoetal2012BiomassModels">(<a href="#ref-RuizPeinadoetal2012BiomassModels" role="doc-biblioref">Ruiz-Peinado et al. 2012</a>)</span>. For each tree, dry biomass was estimated as a sum of the different fractions <span class="citation" data-cites="CarvalhoParresol2003AdditivityTree">(<a href="#ref-CarvalhoParresol2003AdditivityTree" role="doc-biblioref">Carvalho and Parresol 2003</a>)</span>: stem plus branches with a diameter &gt; 7 cm (); branches with a diameter between 2 and 7 cm (), branches with a diameter of less than 2 cm with leaves (), and the belowground fraction () the roots. Biomass of each fraction were computed using the equations developed for <em>Q. pyrenaica</em> <span class="citation" data-cites="RuizPeinadoetal2012BiomassModels">(<a href="#ref-RuizPeinadoetal2012BiomassModels" role="doc-biblioref">Ruiz-Peinado et al. 2012</a>)</span> (Table&nbsp;<a href="#tab:carbon:biomasseq" data-reference-type="ref" data-reference="tab:carbon:biomasseq">[tab:carbon:biomasseq]</a>).</p>
<p>The carbon content in each biomass fraction was calculated by multiplying each value by 0.475, <em>i.e.</em> the species-specific carbon content of the biomass for this species <span class="citation" data-cites="Ibanezetal2002MetodologiaComplementaria Monteroetal2005ProduccionBiomasa">(<a href="#ref-Ibanezetal2002MetodologiaComplementaria" role="doc-biblioref">Ibáñez et al. 2002</a>, <a href="#ref-Monteroetal2005ProduccionBiomasa" role="doc-biblioref">Montero et al. 2005</a>)</span>. The equivalent tree CO<sub>2</sub> sequestration was estimated by multiplying the tree carbon content by 3.67, <em>i.e.</em> the ratio between CO<sub>2</sub> molecular weight and C atomic weight. Biomass and carbon storage of individual trees were aggregated at plot level and scaled-up to hectarea to obtain the values of biomass for each fraction (Mg ha<span class="math inline">\(^{-1}\)</span>), and the total carbon storage (Mg ha<span class="math inline">\(^{-1}\)</span>) at the plot level.</p>
</section>
<section id="sec-carbon-mat-lidar" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="sec-carbon-mat-lidar"><span class="header-section-number">6.2.4</span> Airborne Laser Scanning (ALS) data and processing</h3>
<p>Airborne Laser Scanning (ALS) data were acquired in 2014, with up to four returns measured per pulse, within the Spanish National Plan for Aerial Orthophotography (PNOA, by its Spanish language acronym) were used to generate the biomass map. The nominal point density was 0.5 points m<span class="math inline">\(^-2\)</span> with a vertical accuracy better than 0.20 m. The data were examined for extent, point density and consistency with overlapping points from adjacent scanning lines being removed. Gap filling was carried out when data from additional flight lines were available. The point clouds were classified into ground and non-ground using the Multiscale Curvature Classification (MCC) algorithm <span class="citation" data-cites="EvansHudak2007MultiscaleCurvature">(<a href="#ref-EvansHudak2007MultiscaleCurvature" role="doc-biblioref">Evans and Hudak 2007</a>)</span>. Non-ground returns were labelled as vegetation as no infrastructure is present in the study area. The classified point cloud (ground class) was used to derive a digital elevation model (DEM). The DEM was subsequently used to compute the height above ground (<em>i.e.</em> normalized height) for the points classified as vegetation. Based on the height above ground, four generic groups of lidar metrics were generated at 20-m spatial resolution: canopy metrics, strata metrics, first returns metrics and all returns metrics. For example, canopy metrics included canopy closure at different heights (<em>i.e.</em>, 1-, 2-, 4-, 6-, 8-, 10-, and 12-m) while strata metrics included canopy closure and forest density for specific strata (<em>i.e.</em>, 0-0.5 m, 1-6 m, 1-8 m, 1-10 m, 1-12 m, 1-16 m, 1-24 m, 2-4 m, 2-6 m,..., 8-16 m, 8-24 m). Percentiles were computed using first returns as well as all returns metrics. Canopy closure metrics were defined as the proportion of first returns over a specific height threshold. Strata-specific canopy closure and forest density metrics were defined as the proportion of first returns and, respectively, all returns falling within specific height thresholds. Such metrics, representing proxies of forest structural characteristics, were aggregated at plot level and correlated with field-based plot biomass estimates to select optimum predictor variables for forest biomass. A two-step variable selection approach was used to identify the best lidar predictors for each biomass fraction. First, correlation among all 250 lidar variables was assessed and highly correlated (|r| &gt; 0.7) variables were excluded from the dataset after retaining those with the highest correlation with biomass response variables (, , , , and ). Second, the VSURF variable selection algorithm was implemented in R <span class="citation" data-cites="VSURF">(<a href="#ref-VSURF" role="doc-biblioref">Genuer et al. 2019</a>)</span> to identify the best predictors for each response variable. Briefly, this algorithm computes random forest models and variables are selected based on their importance value and on their capacity to decrease the OOB (out-of-bag) error of these models <span class="citation" data-cites="VSURF">(<a href="#ref-VSURF" role="doc-biblioref">Genuer et al. 2019</a>)</span>.</p>
<p>Biomass maps were generated based on the selected predictor lidar variables using a Support Vector Machines (SVM) classification. The SVM model’s stability and error were computed by randomly splitting the dataset (<em>n</em>=113 plots) into calibration and validation metrics (using a 60:40 rule). 100 random iterations were carried out to compute average error metrics including the average root mean squared error (RMSE), the relative RMSE (RMSE%) and the correlation (r) between predicted and observed biomass. SVM biomass models were applied over the extents of the eight oak populations. For each biomass fraction, we compared the performance of the plot-scale biomass measurements (field data) with the predicted values derived from the ALS modelling. We used graphical methods and computed a Pearson correlation coefficient.</p>
</section>
<section id="sec-carbon-mat-cmpas" class="level3" data-number="6.2.5">
<h3 data-number="6.2.5" class="anchored" data-anchor-id="sec-carbon-mat-cmpas"><span class="header-section-number">6.2.5</span> Cartography of biomass and C stocks</h3>
<p>For each of the estimated biomass fractions obtained from the modelling, we generated a map of biomass and sequestered C for each of the oak populations studied. The distribution of <em>Q. pyrenaica</em> forests in Sierra Nevada were obtained from vegetation and ecosystem maps of Sierra Nevada at 1:10 000 scale <span class="citation" data-cites="CMAOT2014CartografiaEvaluacion PerezLuqueetal2019MapEcosystems">(<a href="#ref-CMAOT2014CartografiaEvaluacion" role="doc-biblioref">CMAOT 2014</a>, <a href="#ref-PerezLuqueetal2019MapEcosystems" role="doc-biblioref">Pérez-Luque et al. 2019</a>)</span>. The pixel size selected to compute the ALS-derived metrics and to map the biomass and C stock was 20 m × 20 m, representing an area of 400 m<sup>2</sup>, similar to the field plot dimensions (mean = 439 m<sup>2</sup>, range 254 - 706.85) (Table&nbsp;<a href="#tab:carbon:inventories" data-reference-type="ref" data-reference="tab:carbon:inventories">[tab:carbon:inventories]</a>).</p>
</section>
</section>
<section id="sec-carbon-mat-temporal" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-carbon-mat-temporal"><span class="header-section-number">6.3</span> Temporal evolution of tree biomass in <em>Q. pyrenaica</em> stands</h2>
<p>We explored the temporal variation of biomass for this species at national level, and then only for plots located in our study area. To analyze the temporal evolution of the tree biomass of <em>Q. pyrenaica</em> forests, we used data from Spanish National Forest Inventory (SNFI), an extensive national database of forest surveys distributed systematically across the forested area of Spain. We used data from the second <span class="citation" data-cites="VillaescusaDiaz1998SegundoInventario">(<a href="#ref-VillaescusaDiaz1998SegundoInventario" role="doc-biblioref">Villaescusa and Díaz 1998</a>)</span> and the third Spanish Forest Inventory <span class="citation" data-cites="Villanueva2005TercerInventario">(<a href="#ref-Villanueva2005TercerInventario" role="doc-biblioref">Villanueva 2005</a>)</span>, carried out during 1986-1996 and during 1997-2007, respectively. The SNFI is based on a network of circular plots which allows forest characterization and includes exhaustive information on the structure and composition of canopy and understory woody species. Each plot consisted of four concentric circles of <em>radii</em> 5-, 10-, 15- and 25-m, in which DBH and total height were measured in all trees of DBH &gt; 7.5-, 12.5-, 22.5- and 42.5-cm, respectively <span class="citation" data-cites="Alberdietal2016SpanishNational">(<a href="#ref-Alberdietal2016SpanishNational" role="doc-biblioref">Alberdi et al. 2016</a>)</span>. Of the SNFI3 plots where <em>Q. pyrenaica</em> was present (<em>n</em> = 6382 plots), we selected only plots measured previously in the SNFI2, and with <em>Q. pyrenaica</em> as the main dominant species (<em>n</em> = 2269). For each plot, we computed aboveground and belowground biomass of each <em>Q. pyrenaica</em> adult tree using allometric equations (Table&nbsp;<a href="#tab:carbon:biomasseq" data-reference-type="ref" data-reference="tab:carbon:biomasseq">[tab:carbon:biomasseq]</a>) <span class="citation" data-cites="RuizPeinadoetal2012BiomassModels">(<a href="#ref-RuizPeinadoetal2012BiomassModels" role="doc-biblioref">Ruiz-Peinado et al. 2012</a>)</span>. We scaled-up to hectarea and aggregated at plot level. The temporal variation of biomass was estimated as the difference between biomass value of the same plot at the SNF3 and at the SNF2: <span class="math display">\[\Delta Biomass = B_{i, SNFI3} - B_{i, SNFI2}\]</span></p>
</section>
<section id="sec-carbon-analysis" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-carbon-analysis"><span class="header-section-number">6.4</span> Statistical analysis</h2>
<p>We analyzed differences of the ALS-derived biomass and carbon dioxide sequestration for each fraction among the different oak populations and oak-population clusters. Non parametric Kruskal-Wallis test were used because data do not fit normality, homocedasticity or independence. Multiple pairwise comparisons after this test were made using Dunn’s test with Bonferroni’s correction. We also explored differences in the forest structure among oak-populations clusters. For this purpose, we computed several forest attributes for each field plot: mean tree height (m), average DBH (cm), basal area (m<sup>2</sup> ha<sup>-1</sup>) and tree density (trees ha<sup>-1</sup>). Differences for stand attributes among oak-population clusters were also analyzed with the non-parametric Kruskal-Wallis test, followed by multiple pairwise comparisons using Dunn’s test with Bonferroni’s correction.</p>
<p>We used generalized linear models (GLM) to analyze the effect of the different explanatory variables and their interactions on the forest C stock (<em>i.e.</em>: , , ). As explanatory variables we selected: topographic variables (elevation, slope and aspect); competition related-variables (tree density); stand-structural variables (Shannon structural diversity index and vertical strata richness); and microclimatic variables (topographic wetness index, a surrogate of the moisture content). Topographic variables were derived from a digital elevation model at 5 x 5 meters resolution (Spanish National Geographic Institute). For each plot we compute the tree density (trees ha<sup>-1</sup>), and the strata richness (number of different diametric classes) using the DBH. We considered the following diametric classes: &lt;2.5 cm; each 5 cm-intervals; and &gt;52.5 cm. We also characterized the structural diversity by computing a Shannon-Weber structural diversity index following <span class="citation" data-cites="delRioetal2003IndicesStand">(<a href="#ref-delRioetal2003IndicesStand" role="doc-biblioref">Rio et al. 2003</a>)</span>. This index is considered a surrogate of structural heterogeneity <span class="citation" data-cites="McElhinnyetal2005ForestWoodland Gadowetal2012ForestStructure">(<a href="#ref-McElhinnyetal2005ForestWoodland" role="doc-biblioref">McElhinny et al. 2005</a>, <a href="#ref-Gadowetal2012ForestStructure" role="doc-biblioref">Gadow et al. 2012</a>)</span>. The topographic wetness index is an estimate of the predicted water accumulation and is considered a surrogate of soil-moisture <span class="citation" data-cites="Zinkoetal2005PlantSpecies Petrosellietal2013EcologicalBehavior">(<a href="#ref-Zinkoetal2005PlantSpecies" role="doc-biblioref">Zinko et al. 2005</a>, <a href="#ref-Petrosellietal2013EcologicalBehavior" role="doc-biblioref">Petroselli et al. 2013</a>)</span>. It was derived from the high-resolution digital elevation model using the dynatopmodel R package <span class="citation" data-cites="Metcalfeetal2018DynatopmodelImplementation">(<a href="#ref-Metcalfeetal2018DynatopmodelImplementation" role="doc-biblioref">Metcalfe et al. 2018</a>)</span>. Stepwise model selection was applied starting from the saturated model and removing the least significant term until there was no further decrease in the Bayesian Information Criterion (BIC). We considered all models within 2 BIC units as equivalent in terms of fit.</p>
<p>All analyses were conducted using the R software <span class="citation" data-cites="base">(<a href="#ref-base" role="doc-biblioref">R Core Team 2020</a>)</span>, and the vegan <span class="citation" data-cites="vegan">(<a href="#ref-vegan" role="doc-biblioref">Oksanen et al. 2019</a>)</span>, randomForest <span class="citation" data-cites="randomForest">(<a href="#ref-randomForest" role="doc-biblioref">Liaw and Wiener 2002</a>)</span>, nlstools <span class="citation" data-cites="nlstools">(<a href="#ref-nlstools" role="doc-biblioref">Baty et al. 2015</a>)</span>, nlme <span class="citation" data-cites="nlme">(<a href="#ref-nlme" role="doc-biblioref">Pinheiro et al. 2021</a>)</span>, biostat <span class="citation" data-cites="biostat">(<a href="#ref-biostat" role="doc-biblioref">Gegzna 2020</a>)</span>, glmulti <span class="citation" data-cites="glmulti">(<a href="#ref-glmulti" role="doc-biblioref">Calcagno 2020</a>)</span>, MuMIn <span class="citation" data-cites="MuMIn">(<a href="#ref-MuMIn" role="doc-biblioref">Bartoń 2020</a>)</span> and VSURF packages <span class="citation" data-cites="VSURF">(<a href="#ref-VSURF" role="doc-biblioref">Genuer et al. 2019</a>)</span>.</p>
</section>
<section id="sec-carbon-results" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-carbon-results"><span class="header-section-number">6.5</span> Results</h2>
<section id="sec-carbon-results-modelling" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="sec-carbon-results-modelling"><span class="header-section-number">6.5.1</span> Biomass modelling</h3>
<p>The LIDAR-metrics that best predicted the each-fraction biomass values are presented in Table&nbsp;<a href="#tab:carbon:lidarmodels" data-reference-type="ref" data-reference="tab:carbon:lidarmodels">[tab:carbon:lidarmodels]</a>. The rumple index, elevation, canopy height maximum and 99<sup>th</sup> percentile of canopy height were the LIDAR-metrics better explained the biomass model for the , and fractions (Table&nbsp;<a href="#tab:carbon:lidarmodels" data-reference-type="ref" data-reference="tab:carbon:lidarmodels">[tab:carbon:lidarmodels]</a>), and they also were selected in biomass model for the and fractions. The better models provided R<sup>2</sup> values ranged from 0.17 () to 0.45 () (Table&nbsp;<a href="#tab:carbon:lidarmodels" data-reference-type="ref" data-reference="tab:carbon:lidarmodels">[tab:carbon:lidarmodels]</a>).</p>
<p>The evaluation of the observed (field-measured) <em>versus</em> the ALS-estimated values for all biomass fractions are presented in Figure&nbsp;<a href="#fig:carbon:compara" data-reference-type="ref" data-reference="fig:carbon:compara">[fig:carbon:compara]</a>. The higher correlations were obtained for and fractions which showed 0.61 and 0.60 R<sup>2</sup> values respectively. The other biomass components showed significant but weaker correlations, particularly the fraction with a R<sup>2</sup> value of 0.14 (Figure&nbsp;<a href="#fig:carbon:compara" data-reference-type="ref" data-reference="fig:carbon:compara">[fig:carbon:compara]</a>).</p>
<div id="fig-carbon-compara" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-carbon-compara-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/carbon/carbon-compara-lidar-field.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-carbon-compara-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Scatterplots of the field-measured biomass fractions and the most accurate model-estimated values of the biomass fractions in the same plot. R2 and significance values of the correlation are included
</figcaption>
</figure>
</div>
<div id="tbl-carbon-compara" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carbon-compara-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Stand characteristics, field-measured and ALS-derived biomass (Mg ha<span class="math inline">\(^-1\)</span>) and potential carbon dioxide sequestration (Mg CO<span class="math inline">\(_2\)</span> ha<span class="math inline">\(^-1\)</span>) values for Pyrenean oak-population clusters in Sierra Nevada. Statistics and significance value for Kruskal-Wallis tests were shown. Different letters indicate statistically significant differences between oak-population clusters (Dunn’s test, p &lt; 0.05). Total values of ALS-derived Biomass (Mg) and Potential CO<span class="math inline">\(_2\)</span> sequestration (Mg CO<span class="math inline">\(_2\)</span>) for all <em>Q. pyrenaica</em> forests in Sierra Nevada are shown. Values in bracket show total values for each oak-population cluster.
</figcaption>
<div aria-describedby="tbl-carbon-compara-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><strong><em>Stand features</em></strong></th>
<th><strong>N</strong></th>
<th></th>
<th><strong>NW</strong></th>
<th></th>
<th><strong>S</strong></th>
<th>* *</th>
<th><em>Statistic</em></th>
<th><em>p-value</em></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tree height (avg.)</td>
<td>14.69 ± 0.81 a</td>
<td></td>
<td>9.10 ± 0.55 b</td>
<td></td>
<td>7.81 ± 0.36 b</td>
<td></td>
<td>15.23</td>
<td>0.001</td>
<td></td>
</tr>
<tr class="even">
<td>Tree height (min)</td>
<td>10.32 ± 1.49 a</td>
<td></td>
<td>4.02 ± 0.52 b</td>
<td></td>
<td>3.71 ± 0.31 b</td>
<td></td>
<td>11.20</td>
<td><em>0.004</em></td>
<td></td>
</tr>
<tr class="odd">
<td>Tree height (max)</td>
<td>18.54 ± 0.68 a</td>
<td></td>
<td>14.76 ± 0.40 b</td>
<td></td>
<td>13.89 ± 0.33 b</td>
<td></td>
<td>12.67</td>
<td><em>0.002</em></td>
<td></td>
</tr>
<tr class="even">
<td>DBH</td>
<td>39.36 ± 6.00 a</td>
<td></td>
<td>20.18 ± 1.24 b</td>
<td></td>
<td>20.88 ± 1.54 b</td>
<td></td>
<td>8.43</td>
<td>0.015</td>
<td></td>
</tr>
<tr class="odd">
<td>Basal Area</td>
<td>35.99 ± 6.61 a</td>
<td></td>
<td>28.08 ± 2.34 a</td>
<td></td>
<td>28.81 ± 2.26 a</td>
<td></td>
<td>1.31</td>
<td>0.518</td>
<td></td>
</tr>
<tr class="even">
<td>Tree density</td>
<td>405.51 ± 165.87 a</td>
<td></td>
<td>898.86 ± 104.02 a</td>
<td></td>
<td>838.35 ± 106.01 a</td>
<td></td>
<td>3.69</td>
<td>0.158</td>
<td></td>
</tr>
<tr class="odd">
<td><strong><em>Field-measured biomass</em></strong></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>182.89 ± 33.18</td>
<td></td>
<td>113.21 ± 11.41</td>
<td></td>
<td>117.18 ± 11.72</td>
<td></td>
<td>4.30</td>
<td>0.116</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>28.82 ± 5.37</td>
<td></td>
<td>17.49 ± 1.85</td>
<td></td>
<td>17.31 ± 1.69</td>
<td></td>
<td>5.25</td>
<td>0.072</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>8.75 ± 2.06</td>
<td></td>
<td>9.73 ± 0.74</td>
<td></td>
<td>8.63 ± 0.48</td>
<td></td>
<td>1.06</td>
<td>0.587</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>65.52 ± 12.04</td>
<td></td>
<td>51.12 ± 4.26</td>
<td></td>
<td>52.46 ± 4.11</td>
<td></td>
<td>1.31</td>
<td>0.518</td>
<td></td>
</tr>
<tr class="even">
<td><strong><em>ALS-derived measured</em></strong></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><strong><em>Total</em></strong></td>
</tr>
<tr class="odd">
<td></td>
<td>84.29 ± 0.50 a (1.03 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>83.35 ± 0.37 a (1.98 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>89.16 ± 0.33 b (2.62 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2296.42</td>
<td>0.001</td>
<td>5.62 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>8.71 ± 0.04 a (0.10 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>8.24 ± 0.03 b (0.18 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>8.37 ± 0.02 c (0.24 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>1446.20</td>
<td>0.001</td>
<td>0.52 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td>13.16 ± 0.08 a (0.16 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>13.10 ± 0.06 a (0.31 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>14.18 ± 0.05 b (0.42 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2138.11</td>
<td>0.001</td>
<td>0.89 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>49.32 ± 0.21 a (0.59 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>46.56 ± 0.16 b (1.08 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>47.74 ± 0.13 c (1.4 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2978.22</td>
<td>0.001</td>
<td>3.07 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td>152.06 ± 0.81 a (1.85 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>147.27 ± 0.60 b (3.48 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>157.13 ± 0.53 c (4.61 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2369.70</td>
<td>0.001</td>
<td>9.94 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="even">
<td>CO<span class="math inline">\(_2\)</span> stock stem</td>
<td>146.93 ± 0.86 a (1.03 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>145.30 ± 0.64 a (1.89 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>155.44 ± 0.57 b (2.44 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2296.42</td>
<td>0.001</td>
<td>5.36 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="odd">
<td>CO<span class="math inline">\(_2\)</span> stock b27</td>
<td>15.19 ± 0.06 a (1.79 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>14.37 ± 0.05 b (3.44 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>14.59 ± 0.04 c (4.57 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>1446.20</td>
<td>0.001</td>
<td>9.8 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="even">
<td>CO<span class="math inline">\(_2\)</span> stock b2</td>
<td>22.95 ± 0.15 a (0.28 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>22.85 ± 0.11 a (0.54 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>24.73 ± 0.10 b (0.73 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2138.11</td>
<td>0.001</td>
<td>1.54 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="odd">
<td>CO<span class="math inline">\(_2\)</span> stock root</td>
<td>85.98 ± 0.37 a (0.17 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>81.17 ± 0.27 b (0.31 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>83.23 ± 0.22 c (0.42 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2978.22</td>
<td>0.001</td>
<td>0.9 10<span class="math inline">\(^6\)</span></td>
</tr>
<tr class="even">
<td>CO<span class="math inline">\(_2\)</span> stock total</td>
<td>265.07 ± 1.41 a (3.22 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>256.72 ± 1.05 b (6.07 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>273.91 ± 0.93 c (8.04 10<span class="math inline">\(^6\)</span>)</td>
<td></td>
<td>2369.70</td>
<td>0.001</td>
<td>17.33 10<span class="math inline">\(^6\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-carbon-results-cartography" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="sec-carbon-results-cartography"><span class="header-section-number">6.5.2</span> Differences on biomass and C stock among Pyrenean oak populations</h3>
<p>The cartography for total biomass () and the potential dioxide carbon sequestration of are shown in Figure&nbsp;<a href="#fig:carbon:mapas-wt" data-reference-type="ref" data-reference="fig:carbon:mapas-wt">[fig:carbon:mapas-wt]</a>. The total estimated biomass (aboveground and belowground) existing in the <em>Q. pyrenaica</em> woodlands of Sierra Nevada amounted to 9.94 Tg (1 Tg = 10<span class="math inline">\(^12\)</span> g), which represents a potential sequestration of 17.33 Tg of CO<sub>2</sub> (Table&nbsp;<a href="#tab:carbon:temporal" data-reference-type="ref" data-reference="tab:carbon:temporal">[tab:carbon:temporal]</a>).</p>
<p>The spatial distribution of the estimated biomass in the <em>Q. pyrenaica</em> forests of Sierra Nevada showed a general pattern with higher values mostly concentrated at southernmost oak woodlands. We observed that the MON population, belonging to NW cluster, showed the higher values for the estimated biomass and for the dioxide carbon sequestration potential (Figure&nbsp;<a href="#fig:carbon:mapas-wt" data-reference-type="ref" data-reference="fig:carbon:mapas-wt">[fig:carbon:mapas-wt]</a>; Table&nbsp;<a href="#tab:carbon:biomass-pop" data-reference-type="ref" data-reference="tab:carbon:biomass-pop">[tab:carbon:biomass-pop]</a>).</p>
<div id="fig-carbon-mapas-wt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-carbon-mapas-wt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/carbon/carbon-mapas-wt-ct.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-carbon-mapas-wt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Total biomass () (<strong>a</strong>) and Potential Carbon sequestration (<strong>b</strong>) for each of the eight Pyrenean oak populations of Sierra Nevada. Different spatial scales were used for ease of visualization.
</figcaption>
</figure>
</div>
<p>The comparison of field-derived measures between oak-cluster populations revealed differences for tree height and DBH, but no for Basal Area and Tree density (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>). The oak woodlands of N-cluster showed significantly taller trees with larger DBH than those of the NW and S (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>, Figure&nbsp;<a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>). Lower tree density and higher basal area were observed for N oak-woodlands, but the differences were not significant with the other oak-populations. No differences were found for field-biomass estimation between oak-populations (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>).</p>
<div id="tbl-carbon-bestmodels" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carbon-bestmodels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Summary of the best model (in terms of Bayesian Information Criterion) of total (), stem (), and root () biomass (Mg ha<span class="math inline">\(^-1\)</span>) as a function of field-plot variables.
</figcaption>
<div aria-describedby="tbl-carbon-bestmodels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>l</th>
<th>crr</th>
<th>crr</th>
<th>crr@</th>
<th>***</th>
<th></th>
<th></th>
<th>***</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><em>Effects</em></strong></td>
<td><strong><em>Estimate</em></strong></td>
<td><strong><em>Z-value</em></strong></td>
<td><strong><em>p-value</em></strong></td>
<td><strong><em>Estimate</em></strong></td>
<td><strong><em>Z-value</em></strong></td>
<td><strong><em>p-value</em></strong></td>
<td><strong><em>Estimate</em></strong></td>
<td><strong><em>Z-value</em></strong></td>
<td><strong><em>p-value</em></strong></td>
</tr>
<tr class="even">
<td>Intercept</td>
<td>-1094.19 ± 292.09</td>
<td>-3.75</td>
<td>0.001</td>
<td>-721.44 ± 188.25</td>
<td>-3.83</td>
<td>0.001</td>
<td>-224.74 ± 68.09</td>
<td>-3.3</td>
<td>0.001</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(Ln\)</span> Tree density (trees ha<span class="math inline">\(^-1\)</span>)</td>
<td>102.04 ± 44.97</td>
<td>2.27</td>
<td>0.03</td>
<td>73.14 ± 28.98</td>
<td>2.52</td>
<td>0.01</td>
<td>22.08 ± 10.48</td>
<td>2.11</td>
<td>0.04</td>
</tr>
<tr class="even">
<td><strong>Elevation (m)</strong></td>
<td>0.31 ± 0.05</td>
<td>6.77</td>
<td>0.001</td>
<td>0.17 ± 0.03</td>
<td>5.83</td>
<td>0.001</td>
<td>0.07 ± 0.01</td>
<td>6.83</td>
<td>0.001</td>
</tr>
<tr class="odd">
<td><strong>Structural diversity index</strong></td>
<td>2617.14 ± 828.65</td>
<td>3.16</td>
<td>0.002</td>
<td>1809.87 ± 534.06</td>
<td>3.39</td>
<td>0.001</td>
<td>542.41 ± 193.18</td>
<td>2.81</td>
<td>0.006</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(Ln\)</span> Tree density $$ Structural diversity index</strong></td>
<td>-349.22 ± 122.01</td>
<td>-2.86</td>
<td>0.005</td>
<td>-242.94 ± 78.63</td>
<td>-3.09</td>
<td>0.003</td>
<td>-76.26 ± 28.44</td>
<td>-2.68</td>
<td>0.009</td>
</tr>
<tr class="odd">
<td><strong>Degree of freedom</strong></td>
<td>101</td>
<td></td>
<td></td>
<td>101</td>
<td></td>
<td></td>
<td>101</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>AIC</strong></td>
<td>1196</td>
<td></td>
<td></td>
<td>1103</td>
<td></td>
<td></td>
<td>887</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>BIC</strong></td>
<td>1212</td>
<td></td>
<td></td>
<td>1119</td>
<td></td>
<td></td>
<td>903</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Deviance Explained</strong></td>
<td>0.413</td>
<td></td>
<td></td>
<td>0.373</td>
<td></td>
<td></td>
<td>0.381</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Significant differences for ALS-estimated biomass were found among oak-clusters (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>). The values for the stem fraction () and small branches () biomass fractions were significantly higher for S oak-populations than for those in the N and NW, the latter showing no differences (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>). The total biomass () was significantly different between oak-population clusters with higher values for southern oak populations (Figure&nbsp;<a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>). Root biomass () and medium branches biomass () were significantly higher for northern oak-populations (N) (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>; Figure&nbsp;<a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>).</p>
<div id="fig-carbon-schema" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-carbon-schema-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/carbon/carbon-esquema-compara2.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-carbon-schema-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Comparison of stand features and ALS-estimated biomass fractions between oak-population clusters of <em>Quercus pyrenaica</em> woodlands in Sierra Nevada. The distribution of oak-cluster are shown upper-right. Different letters indicate statistically significant differences between oak-population clusters (Dunn’s test, p 0.05) after Kruskal-Wallis test.
</figcaption>
</figure>
</div>
</section>
<section id="sec-carbon-results-prediction" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="sec-carbon-results-prediction"><span class="header-section-number">6.5.3</span> Predictions of stand biomass</h3>
<p>The best GLM models selected for total (), stem () and root () biomass explained 70.3%, 67.3% and 63.1% of variance respectively (Table&nbsp;<a href="#tab:carbon:bestmodels" data-reference-type="ref" data-reference="tab:carbon:bestmodels">[tab:carbon:bestmodels]</a> and Table&nbsp;<a href="#tab:carbon:model-selection" data-reference-type="ref" data-reference="tab:carbon:model-selection">[tab:carbon:model-selection]</a>). The elevation and the shannon structural diversity index showed positive effects on estimated biomass (Table&nbsp;<a href="#tab:carbon:bestmodels" data-reference-type="ref" data-reference="tab:carbon:bestmodels">[tab:carbon:bestmodels]</a>; Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>). Tree density negatively affected the estimated total biomass. The interaction between tree density and the shannon structural diversity index was significantly (Table&nbsp;<a href="#tab:carbon:bestmodels" data-reference-type="ref" data-reference="tab:carbon:bestmodels">[tab:carbon:bestmodels]</a>), indicating that the total biomass increased with the increase structural diversity at lowest and medium tree densities, but decreased at high values of tree density (Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>).</p>
<div id="fig-carbon-glm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-carbon-glm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/carbon/carbon-glm-effects.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-carbon-glm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Predicted effects of the (<strong>a</strong>) elevation (meters), (<strong>a</strong>) tree density (trees ha-1), (<strong>c</strong>) shannon structural diversity index, and (<strong>d</strong>) tree density $$ shannon structural diversity index, on the total biomass (; Mg ha<span class="math inline">\(^-1\)</span>).
</figcaption>
</figure>
</div>
</section>
<section id="sec-carbon-results-temporal" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="sec-carbon-results-temporal"><span class="header-section-number">6.5.4</span> Temporal evolution of biomass in <em>Q. pyrenaica</em> stands</h3>
<p>A general pattern of increase in aboveground tree biomass was observed for most analyzed plots (Table&nbsp;<a href="#tab:carbon:temporal" data-reference-type="ref" data-reference="tab:carbon:temporal">[tab:carbon:temporal]</a>), with a total increase of 19 172 Mg ha<span class="math inline">\(^{-1}\)</span> between the two national forest inventories. About 89 % of the plots showed an increase in aboveground tree biomass, with an average of 11.46 Mg ha<span class="math inline">\(^{-1}\)</span> (Table&nbsp;<a href="#tab:carbon:temporal" data-reference-type="ref" data-reference="tab:carbon:temporal">[tab:carbon:temporal]</a>). This general pattern was also observed for plots located in Sierra Nevada (Figure&nbsp;<a href="#fig:carbon:ifn" data-reference-type="ref" data-reference="fig:carbon:ifn">[fig:carbon:ifn]</a>).</p>
<div id="fig-carbon-ifn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-carbon-ifn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/carbon/carbon-mapa-ifn.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-carbon-ifn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: Variation of tree biomass between the second and third Spanish National Forest Inventories, for plots (points) located on Sierra Nevada which have <em>Q. pyrenaica</em> as the main species. Size point indicates the variation in total biomass ($$ Mg ha<span class="math inline">\(^-1\)</span>).
</figcaption>
</figure>
</div>
<div id="tbl-carbon-temporal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carbon-temporal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.5: Temporal evolution of the total biomass (Mg ha<span class="math inline">\(^-1\)</span>) of <em>Q. pyrenaica</em> and the total carbon (Mg ha<span class="math inline">\(^-1\)</span>) between the second (SNFI2) and third (SNFI3) Spanish National Forest Inventories. Plots were aggregated by loss/gains of the tree numbers ($$ trees), and also by increase/decrease of biomass during the period analyzed. The total variation in biomass (<em>i.e.</em> sum for all plots), and the average variation per plot are shown for each category.
</figcaption>
<div aria-describedby="tbl-carbon-temporal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th>p2cm</th>
<th>&gt;p3cm</th>
<th>c <span class="math display">\[ **trees** | **Biomass** | **\# plots** | \]</span> total biomass (Mg ha<span class="math inline">\(^-1\)</span>)</th>
<th>Average variation per plot (Mg ha<span class="math inline">\(^-1\)</span>)</th>
<th>** Total Carbon** 0</th>
<th>Decrease</th>
<th>159</th>
<th>-1060.39</th>
<th>-6.67 (0.86)</th>
<th>-1846.85</th>
<th>Increase</th>
<th>123</th>
<th>921.40</th>
<th>7.49 (0.86)</th>
<th>1604.77 0</th>
<th>Decrease</th>
<th>33</th>
<th>-287.19</th>
<th>-8.7 (2.82)</th>
<th>-500.19</th>
<th>Increase</th>
<th>1586</th>
<th>18183.25</th>
<th>11.46 (0.41)</th>
<th>31669.16 0</th>
<th>Decrease</th>
<th>56</th>
<th>-141.40</th>
<th>-2.53 (0.59)</th>
<th>-246.28</th>
<th>Increase</th>
<th>312</th>
<th>1556.16</th>
<th>4.99 (0.48)</th>
<th>2710.32</th>
<th></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-carbon-discussion" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-carbon-discussion"><span class="header-section-number">6.6</span> Discussion</h2>
<section id="sec-carbon-discussion-sn" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="sec-carbon-discussion-sn"><span class="header-section-number">6.6.1</span> Carbon sequestration by Sierra Nevada oak woodlands.</h3>
<p>Total estimated biomass values in Sierra Nevada oak woodlands ranged from 147.27 – 157.13 Mg ha<span class="math inline">\(^{-1}\)</span> (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>), with aboveground biomass (sum of , and fractions) ranging from 104.69 - 111.71 Mg ha<span class="math inline">\(^{-1}\)</span>. Our results are consistent with the mean aboveground biomass density cited by the IPCC guidelines as the default value for temperate mountain systems (130 (20 - 600) Mg ha<span class="math inline">\(^{-1}\)</span>) in Europe <span class="citation" data-cites="IPCC2006ForestLand">(<a href="#ref-IPCC2006ForestLand" role="doc-biblioref">IPCC 2006</a>)</span>. Using data from the Spanish Third National Forest Inventory, <span class="citation" data-cites="Vayredaetal2012SpatialPatterns">Vayreda et al. (<a href="#ref-Vayredaetal2012SpatialPatterns" role="doc-biblioref">2012</a>)</span> reported an average value for stand C stock of 45 Mg ha<span class="math inline">\(^{-1}\)</span> along the distribution of <em>Q. pyrenaica</em> in the Iberian Peninsula. Those values were lower than the estimated carbon stock (above- and below-ground) in our study which ranged from 69.95 - 74.63 Mg ha<span class="math inline">\(^{-1}\)</span> (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>). At a more regional scale, our results showed higher values than those found in the central range of the species distribution, where aboveground biomass varied between 63.8 - 98 Mg ha<span class="math inline">\(^{-1}\)</span> <span class="citation" data-cites="GallardoLanchoGonzalezHernandez2004SequestrationCarbon">(<a href="#ref-GallardoLanchoGonzalezHernandez2004SequestrationCarbon" role="doc-biblioref">Gallardo Lancho and González Hernández 2004</a>)</span>. Estimates of dioxide carbon sequestration for <em>Q. pyrenaica</em> pure stands (122.19 - 152.82 Mg ha<span class="math inline">\(^{-1}\)</span>) located in the Central Mountain Range (Spain) <span class="citation" data-cites="Canellasetal2008SilvicultureCarbon Canellasetal2017CarbonSequestration">(<a href="#ref-Canellasetal2008SilvicultureCarbon" role="doc-biblioref">Cañellas et al. 2008</a>, <a href="#ref-Canellasetal2017CarbonSequestration" role="doc-biblioref">Cañellas et al. 2017</a>)</span> were also lower than our results (256.72 - 273.91) (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>). Despite the potential differences derived from the carbon estimation method (<em>i.e.</em> LIDAR estimation <em>versus</em> field-ground based estimation; biomass expansion factors), several factors could explain the differences found in our results with respect to the values reported for other studies. First, it is generally accepted that there is an age‐related decline in stand biomass accumulation <span class="citation" data-cites="Xuetal2012AgerelatedDecline">(<a href="#ref-Xuetal2012AgerelatedDecline" role="doc-biblioref">Xu et al. 2012</a>)</span> with the productivity of old-growth forests being usually lower than younger forests <span class="citation" data-cites="Kutschetal2009EcophysiologicalCharacteristics">(<a href="#ref-Kutschetal2009EcophysiologicalCharacteristics" role="doc-biblioref">Kutsch et al. 2009</a>)</span>. Oak woodlands of Sierra Nevada are composed of relatively young trees <span class="citation" data-cites="GeaIzquierdoCanellas2014LocalClimate PerezLuqueetal2020LanduseLegacies RubioCuadradoetal2018AbioticFactors">(<a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>, <a href="#ref-RubioCuadradoetal2018AbioticFactors" role="doc-biblioref">Rubio-Cuadrado et al. 2018</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span> in comparison with other woodlands of the species along their distribution area <span class="citation" data-cites="GeaIzquierdoCanellas2014LocalClimate">(<a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>)</span>. The strong anthropic perturbations in these oak has conditioned their structure. For instance, some of the oak woodlands were massively cut down during Spanish Civil post-war period for use as wood gas for vehicles <span class="citation" data-cites="Prieto1975BosquesSierra">(<a href="#ref-Prieto1975BosquesSierra" role="doc-biblioref">Prieto 1975</a>)</span>, or for use in intense mining activities <span class="citation" data-cites="PerezLuqueetal2020LanduseLegacies">(<a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>. Therefore, we can consider that many of the oak woodlands of Sierra Nevada oaks are relatively young, which might explain the high potential for C accumulation obtained in our study, since it has been shown that forest created as a result of drastic land-use changes exhibited faster growing rates, and therefore higher potential C accumulation, than pre-existing forests <span class="citation" data-cites="VilaCabreraetal2017NewForests">(<a href="#ref-VilaCabreraetal2017NewForests" role="doc-biblioref">Vilà-Cabrera et al. 2017</a>)</span>. Differences in carbon stock between young oak coppices and mature forests were reported for other <em>Quercus</em> species <span class="citation" data-cites="Bruckmanetal2011CarbonPools Cotillasetal2016AbovegroundBelowground">(<a href="#ref-Bruckmanetal2011CarbonPools" role="doc-biblioref">Bruckman et al. 2011</a>, <a href="#ref-Cotillasetal2016AbovegroundBelowground" role="doc-biblioref">Cotillas et al. 2016</a>)</span>. Therefore, it is likely that the high total ecosystem C values obtained in our area of study could be partly explained by the stands age-development stage <span class="citation" data-cites="Makinecietal2015EcosystemCarbon">(<a href="#ref-Makinecietal2015EcosystemCarbon" role="doc-biblioref">Makineci et al. 2015</a>)</span>. Secondly, the water availability is generally the most limiting factor driving radial growth of <em>Q. pyrenaica</em> along its distribution range in the Iberian Peninsula <span class="citation" data-cites="GeaIzquierdoCanellas2014LocalClimate">(<a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>)</span>. In Sierra Nevada, northern and northwestern oak populations are located in valley bottoms with high values of relative humidity; and southern ones get the extra supply of water from moist air from the Mediterranean sea. Therefore water availability does not seem to be strongly limiting the oak-growth in this mountain region. In fact, in the last decades positive trends have been observed for greenness and secondary growth of oak woodlands in Sierra Nevada <span class="citation" data-cites="GeaIzquierdoCanellas2014LocalClimate PerezLuqueetal2020LanduseLegacies RubioCuadradoetal2018AbioticFactors">(<a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>, <a href="#ref-RubioCuadradoetal2018AbioticFactors" role="doc-biblioref">Rubio-Cuadrado et al. 2018</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span> suggesting that this mountain range could act as an ecological refugee for this species. Thus those positive growth trends could explain the high values of carbon sequestration obtained in our study.</p>
</section>
<section id="sec-carbon-discussion-factors" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="sec-carbon-discussion-factors"><span class="header-section-number">6.6.2</span> Factors explaining biomass in the oak woodlands</h3>
<p>Regarding the factors explaining biomass, we found a positive effect of the structural richness on total biomass, and therefore on C stock (Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>). Our results are consistent with general patterns obtained for tree species in Iberian Peninsula <span class="citation" data-cites="Vayredaetal2012SpatialPatterns">(<a href="#ref-Vayredaetal2012SpatialPatterns" role="doc-biblioref">Vayreda et al. 2012</a>)</span>. In structural-heterogeneous stands, trees occupy different horizontal and vertical layers, thus they can maximize the resources <span class="citation" data-cites="Forrester2014StandlevelLight">(<a href="#ref-Forrester2014StandlevelLight" role="doc-biblioref">Forrester 2014</a>)</span>, whereas homogeneous stand structure may reduce complementary effects <span class="citation" data-cites="Goncalves2018EffectsForest Vayredaetal2012SpatialPatterns">(<a href="#ref-Vayredaetal2012SpatialPatterns" role="doc-biblioref">Vayreda et al. 2012</a>, <a href="#ref-Goncalves2018EffectsForest" role="doc-biblioref">Gonçalves 2018</a>)</span>. Being surrounded by size-diverse neighbours allow trees to fill the available canopy space around them and hence capture more light <span class="citation" data-cites="Forrester2014StandlevelLight Vanhellemontetal2018SpeciesStructural">(<a href="#ref-Forrester2014StandlevelLight" role="doc-biblioref">Forrester 2014</a>, <a href="#ref-Vanhellemontetal2018SpeciesStructural" role="doc-biblioref">Vanhellemont et al. 2018</a>)</span>. Our results show that the higher the tree density, the lower the total biomass (Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>). Previous studies on forests located on NW of Spain, reported tree stand density as one of the main factors affecting potential biomass production and carbon sequestration <span class="citation" data-cites="CastanoSantamariaetal2013PotentialGround">(<a href="#ref-CastanoSantamariaetal2013PotentialGround" role="doc-biblioref">Castaño-Santamaría et al. 2013</a>)</span>. Tree growth of <em>Q. pyrenaica</em> is inversely influenced by competition <span class="citation" data-cites="Canellasetal2004GrowthResponse FernandezdeUnaetal2015StandCompetition FernandezdeUnaetal2016DisentanglingEffect">(<a href="#ref-Canellasetal2004GrowthResponse" role="doc-biblioref">Cañellas et al. 2004</a>, <a href="#ref-FernandezdeUnaetal2015StandCompetition" role="doc-biblioref">Fernández-de-Uña et al. 2015</a>, <a href="#ref-FernandezdeUnaetal2016DisentanglingEffect" role="doc-biblioref">2016</a>)</span>. Thus, trees respond to reduced competition through the structural shifts such as increased radial growth <span class="citation" data-cites="Canellasetal2004GrowthResponse FernandezdeUnaetal2016DisentanglingEffect">(<a href="#ref-Canellasetal2004GrowthResponse" role="doc-biblioref">Cañellas et al. 2004</a>, <a href="#ref-FernandezdeUnaetal2016DisentanglingEffect" role="doc-biblioref">Fernández-de-Uña et al. 2016</a>)</span>, and therefore a potential increase in biomass. We also found an interaction effect between the tree-density and stand structure diversity (Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>) which suggests that at high tree-densities resources are not maximized, even if structural diversity exists. Despite the importance of the water availability in the growth of <em>Q. pyrenaica</em> <span class="citation" data-cites="GeaIzquierdoCanellas2014LocalClimate MorenoFernandezetal2020InfluenceClimate">(<a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>, <a href="#ref-MorenoFernandezetal2020InfluenceClimate" role="doc-biblioref">Moreno-Fernández et al. 2020</a>)</span>, none of the best models selected for , or , included the topographic wetness index (Table&nbsp;<a href="#tab:carbon:model-selection" data-reference-type="ref" data-reference="tab:carbon:model-selection">[tab:carbon:model-selection]</a>). This would seem suggest that the water requirement of this species in this mountain is met by the location of the oak populations within Sierra Nevada, and therefore would reinforce the role of this mountain region as an ecological refugee for this species.</p>
</section>
<section id="sec-carbon-discussion-differences" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="sec-carbon-discussion-differences"><span class="header-section-number">6.6.3</span> Biomass differences within oak woodlands</h3>
<p>We found that oak woodlands of the Northern cluster showed stands with taller and greater trees (Table&nbsp;<a href="#tab:carbon:compara" data-reference-type="ref" data-reference="tab:carbon:compara">[tab:carbon:compara]</a>), and also high values of biomass (Figures <a href="#fig:carbon:mapas-wt" data-reference-type="ref" data-reference="fig:carbon:mapas-wt">[fig:carbon:mapas-wt]</a> and <a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>). It could be related with lower intensity of anthropogenic disturbances in comparison with the other oak woodlands, mainly because the northern oak woodlands had greater protection during the second half of the last century <span class="citation" data-cites="JimenezOlivencia1991PaisajesSierra">(<a href="#ref-JimenezOlivencia1991PaisajesSierra" role="doc-biblioref">Jiménez Olivencia 1991</a>)</span>, and currently also have the highest level of legal protection within the protected area <span class="citation" data-cites="Anonymous2011Decreto238">(<a href="#ref-Anonymous2011Decreto238" role="doc-biblioref">Anónimo 2011</a>)</span>. The less anthropogenic disturbances have resulted in well-conserved forests with a greater species diversity <span class="citation" data-cites="PerezLuqueetal2021EcologicalDiversity">(<a href="#ref-PerezLuqueetal2021EcologicalDiversity" role="doc-biblioref">Pérez-Luque et al. 2021</a>)</span>, and also a stable stand structure with high values of biomass (Figures <a href="#fig:carbon:mapas-wt" data-reference-type="ref" data-reference="fig:carbon:mapas-wt">[fig:carbon:mapas-wt]</a> and <a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>). For other species of <em>Quercus</em> it has been observed that forests with less disturbance have a higher potential for carbon storage <span class="citation" data-cites="BalboaMuriasetal2006CarbonNutrient Cotillasetal2016AbovegroundBelowground Stojanovicetal2017ForecastingTree">(<a href="#ref-BalboaMuriasetal2006CarbonNutrient" role="doc-biblioref">Balboa-Murias et al. 2006</a>, <a href="#ref-Cotillasetal2016AbovegroundBelowground" role="doc-biblioref">Cotillas et al. 2016</a>, <a href="#ref-Stojanovicetal2017ForecastingTree" role="doc-biblioref">Stojanović et al. 2017</a>)</span>.</p>
<p>Our results also highlighted how differences in stand structure conditioned stand tree biomass (Table&nbsp;<a href="#tab:carbon:bestmodels" data-reference-type="ref" data-reference="tab:carbon:bestmodels">[tab:carbon:bestmodels]</a>, Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>). High dense stands, <em>i.e.</em> northwestern oak populations, showed lower total biomass than less dense stands (northern or southern oak populations) (Figure&nbsp;<a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>). High stand density increase tree competition, limiting stand growth which provokes loss of vitality and reduction in acorn production <span class="citation" data-cites="Bravoetal2008SelviculturaMontes Piqueetal2018Spain">(<a href="#ref-Bravoetal2008SelviculturaMontes" role="doc-biblioref">Bravo et al. 2008</a>, <a href="#ref-Piqueetal2018Spain" role="doc-biblioref">Piqué et al. 2018</a>)</span>, and according to our results, the higher the tree density the lower the capacity of these forests to act as carbon sinks (Figures <a href="#fig:carbon:schema" data-reference-type="ref" data-reference="fig:carbon:schema">[fig:carbon:schema]</a>, <a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>). In addition, an accumulation of biomass, coupled with a loss of structural diversity (Figure&nbsp;<a href="#fig:carbon:glm" data-reference-type="ref" data-reference="fig:carbon:glm">[fig:carbon:glm]</a>), would increase the risk of forest fires due to the large amount of biomass <span class="citation" data-cites="Canellasetal2004GrowthResponse PiqueVericat2015EvolutionPerspectives Serradaetal1992CoppiceSystem">(<a href="#ref-Serradaetal1992CoppiceSystem" role="doc-biblioref">Serrada et al. 1992</a>, <a href="#ref-Canellasetal2004GrowthResponse" role="doc-biblioref">Cañellas et al. 2004</a>, <a href="#ref-PiqueVericat2015EvolutionPerspectives" role="doc-biblioref">Piqué and Vericat 2015</a>)</span></p>
</section>
<section id="sec-carbon-discussion-trends" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="sec-carbon-discussion-trends"><span class="header-section-number">6.6.4</span> Trends of carbon sequestration by oak woodlands</h3>
<p>We observed an increase in aboveground tree biomass between the two inventories for plots located in oak woodlands (Table&nbsp;<a href="#tab:carbon:temporal" data-reference-type="ref" data-reference="tab:carbon:temporal">[tab:carbon:temporal]</a>, Figure&nbsp;<a href="#fig:carbon:ifn" data-reference-type="ref" data-reference="fig:carbon:ifn">[fig:carbon:ifn]</a>). Recent studies have reported a positive trend for primary production and for secondary growth in oak woodlands in Sierra Nevada <span class="citation" data-cites="AlcarazSeguraetal2016ChangesVegetation Dionisioetal2012SatelliteBasedMonitoring PerezLuqueetal2015OntologicalSystem PerezLuqueetal2020LanduseLegacies">(<a href="#ref-Dionisioetal2012SatelliteBasedMonitoring" role="doc-biblioref">Dionisio et al. 2012</a>, <a href="#ref-PerezLuqueetal2015OntologicalSystem" role="doc-biblioref">Pérez-Luque et al. 2015</a>, <a href="#ref-AlcarazSeguraetal2016ChangesVegetation" role="doc-biblioref">Alcaraz-Segura et al. 2016</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>. In addition, an increase in the area occupied by oak forests <span class="citation" data-cites="CamachoOlmedoetal2002TransformacionPaisaje">(<a href="#ref-CamachoOlmedoetal2002TransformacionPaisaje" role="doc-biblioref">Camacho-Olmedo et al. 2002b</a>)</span> as well as the densification of existing forest have been found <span class="citation" data-cites="JimenezOlivenciaetal2015MedioSiglo">(<a href="#ref-JimenezOlivenciaetal2015MedioSiglo" role="doc-biblioref">Jiménez-Olivencia et al. 2015</a>)</span>. All these results indicated that this ecosystem service, <em>i.e.</em> carbon sequestration, have suffered an increase in the last decades in our study area. Land-use changes have extensively affected C storage of terrestrial ecosystems for several areas of south Europe <span class="citation" data-cites="MunozRojasetal2011ChangesLand MunozRojasetal2015ImpactLand">(<a href="#ref-MunozRojasetal2011ChangesLand" role="doc-biblioref">Muñoz-Rojas et al. 2011</a>, <a href="#ref-MunozRojasetal2015ImpactLand" role="doc-biblioref">2015</a>)</span>. Abandonment of traditional activities and rural exodus are the main drivers explaining the densification and expansion of forests particularly in mountainous regions such as Sierra Nevada <span class="citation" data-cites="JimenezOlivenciaetal2015MedioSiglo MacDonaldetal2000AgriculturalAbandonment">(<a href="#ref-MacDonaldetal2000AgriculturalAbandonment" role="doc-biblioref">MacDonald et al. 2000</a>, <a href="#ref-JimenezOlivenciaetal2015MedioSiglo" role="doc-biblioref">Jiménez-Olivencia et al. 2015</a>)</span>. Considering the positive trend observed for the increase in biomass, and the lack of direct human-drive disturbances as these forests are in a protected area, it would expect a positive trend in forest carbon stock, such as has been recorded in many forests in the Mediterranean region in the last decades <span class="citation" data-cites="FAOPlanBleu2018StateMediterranean">(<a href="#ref-FAOPlanBleu2018StateMediterranean" role="doc-biblioref">FAO and Plan Bleu 2018</a>)</span>. It also agrees with the predictions under different scenarios forecasting a forest growth in the next decades <span class="citation" data-cites="Aparicioetal2015ClimateChange">(<a href="#ref-Aparicioetal2015ClimateChange" role="doc-biblioref">Aparicio et al. 2015</a>)</span>. However, it should be taken with caution, since some early signs of saturation of forests as a carbon sink are being documented in Europe <span class="citation" data-cites="Nabuursetal2013FirstSigns">(<a href="#ref-Nabuursetal2013FirstSigns" role="doc-biblioref">Nabuurs et al. 2013</a>)</span>.</p>
</section>
</section>
<section id="sec-carbon-discussion-management" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-carbon-discussion-management"><span class="header-section-number">6.7</span> Management implications</h2>
<p>Several studies indicated that reductions of tree-density on oak coppices forests, by moderate thinning, causes an increase in the tree growth and biomass for <em>Q. pyrenaica</em> woodlands <span class="citation" data-cites="Aldeaetal2017ThinningEnhances Aldeaetal2017EfectoClaras MorenoFernandezetal2020InfluenceClimate Canellasetal2004GrowthResponse">(<a href="#ref-Canellasetal2004GrowthResponse" role="doc-biblioref">Cañellas et al. 2004</a>, <a href="#ref-Aldeaetal2017ThinningEnhances" role="doc-biblioref">Aldea et al. 2017b</a>, <a href="#ref-Aldeaetal2017EfectoClaras" role="doc-biblioref">Aldea et al. 2017a</a>, <a href="#ref-MorenoFernandezetal2020InfluenceClimate" role="doc-biblioref">Moreno-Fernández et al. 2020</a>)</span>, and also for other <em>Quercus</em> species <span class="citation" data-cites="Cotillasetal2009GrowthResponse FernandezdeUnaetal2015StandCompetition">(<a href="#ref-Cotillasetal2009GrowthResponse" role="doc-biblioref">Cotillas et al. 2009</a>, <a href="#ref-FernandezdeUnaetal2015StandCompetition" role="doc-biblioref">Fernández-de-Uña et al. 2015</a>)</span>. This reduction in the stand density could increase the carbon sequestration of the woodland by a higher structural diversity which maximized the use of resources <span class="citation" data-cites="CastanoSantamariaetal2013PotentialGround">(<a href="#ref-CastanoSantamariaetal2013PotentialGround" role="doc-biblioref">Castaño-Santamaría et al. 2013</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Alberdietal2016SpanishNational" class="csl-entry" role="listitem">
Alberdi, I., V. Sandoval, S. Condes, I. Cañellas, and R. Vallejo. 2016. <a href="https://doi.org/10.7818/ECOS.2016.25-3.10">The spanish national forest inventory, a tool for the knowledge, management and conservation of forest ecosystems</a>. Ecosistemas 25:88–97.
</div>
<div id="ref-AlcarazSeguraetal2016ChangesVegetation" class="csl-entry" role="listitem">
Alcaraz-Segura, D., A. Reyes, and J. Cabello. 2016. Changes in vegetation productivity according to teledetection. Pages 142–145 <em>in</em> R. Zamora, A. J. Pérez-Luque, F. J. Bonet, J. M. Barea-Azcón, and R. Aspizua, editors. Global change impacts in <span>Sierra Nevada</span>: Challenges for conservation. <span>Consejería de Medio Ambiente y Ordenación del Territorio. Junta de Andalucía</span>.
</div>
<div id="ref-Aldeaetal2017EfectoClaras" class="csl-entry" role="listitem">
Aldea, J., F. Bravo, A. Bravo-Oviedo, R. Ruiz-Peinado, F. Rodríguez, and M. Del Rio. 2017a. Efecto de las claras en el incremento radial intra-anual de masas mixtas de <em><span>Pinus</span> pinaster</em> <span>Ait</span>. Y <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. <span>VII Congreso Forestal Español</span>. <span>Plasencia, Cáceres (Spain)</span>.
</div>
<div id="ref-Aldeaetal2017ThinningEnhances" class="csl-entry" role="listitem">
Aldea, J., F. Bravo, A. Bravo-Oviedo, R. Ruiz-Peinado, F. Rodríguez, and M. del Río. 2017b. <a href="https://doi.org/10.1016/j.agrformet.2017.02.009">Thinning enhances the species-specific radial increment response to drought in <span>Mediterranean</span> pine-oak stands</a>. Agricultural and Forest Meteorology 237–238:371–383.
</div>
<div id="ref-Anonymous2011Decreto238" class="csl-entry" role="listitem">
Anónimo. 2011. Decreto 238/2011, de 12 de julio, por el que se establece la ordenación y gestión de <span>Sierra Nevada</span>. <span>Consejería</span> de <span>Medio Ambiente</span>. BOJA 155:114–314.
</div>
<div id="ref-Aparicioetal2015ClimateChange" class="csl-entry" role="listitem">
Aparicio, S., N. Carvalhais, and J. Seixas. 2015. <a href="https://doi.org/10.1002/2014JG002755">Climate change impacts on the vegetation carbon cycle of the <span>Iberian Peninsula</span>-<span>Intercomparison</span> of <span>CMIP5</span> results: Climate <span>Change Impacts</span> on <span>Carbon Cycle</span></a>. Journal of Geophysical Research: Biogeosciences 120:641–660.
</div>
<div id="ref-BalboaMuriasetal2006CarbonNutrient" class="csl-entry" role="listitem">
Balboa-Murias, M. A., A. Rojo, J. G. Álvarez, and A. Merino. 2006. <a href="https://doi.org/10.1051/forest:2006038">Carbon and nutrient stocks in mature <span><em>Quercus</em></span><span> <em>robur</em></span> <span>L</span>. Stands in <span>NW Spain</span></a>. Annals of Forest Science 63:557–565.
</div>
<div id="ref-MuMIn" class="csl-entry" role="listitem">
Bartoń, K. 2020. <a href="https://CRAN.R-project.org/package=MuMIn">MuMIn: Multi-model inference</a>.
</div>
<div id="ref-nlstools" class="csl-entry" role="listitem">
Baty, F., C. Ritz, S. Charles, M. Brutsche, J.-P. Flandrois, and M.-L. Delignette-Muller. 2015. <a href="http://www.jstatsoft.org/v66/i05/">A toolbox for nonlinear regression in <span>R</span>: The package nlstools</a>. Journal of Statistical Software 66:1–21.
</div>
<div id="ref-Belandetal2019PromotingUse" class="csl-entry" role="listitem">
Beland, M., G. Parker, B. Sparrow, D. Harding, L. Chasmer, S. Phinn, A. Antonarakis, and A. Strahler. 2019. <a href="https://doi.org/10.1016/j.foreco.2019.117484">On promoting the use of lidar systems in forest ecosystem research</a>. Forest Ecology and Management 450:117484.
</div>
<div id="ref-Benitoetal2011SimulatingPotential" class="csl-entry" role="listitem">
Benito, B., J. Lorite, and J. Peñas. 2011. <a href="https://doi.org/10.1007/s10584-010-0015-3">Simulating potential effects of climatic warming on altitudinal patterns of key species in <span>Mediterranean</span>-alpine ecosystems</a>. Climatic Change 108:471–483.
</div>
<div id="ref-Bravoetal2008SelviculturaMontes" class="csl-entry" role="listitem">
Bravo, J. A., S. Roig, and R. Serrada. 2008. Selvicultura en montes bajos y medios de <em>quercus ilex</em> l., <em>q. Pyrenaica</em> willd. Y <em>q. Faginea</em> lam. Pages 657–744 <em>in</em> R. Serrada, G. Montero, and J. A. Reque, editors. Compendio de selvicultura aplicada en españa. <span>INIA</span>, <span>Madrid</span>.
</div>
<div id="ref-Bruckmanetal2011CarbonPools" class="csl-entry" role="listitem">
Bruckman, V. J., S. Yan, E. Hochbichler, and G. Glatzel. 2011. <a href="https://doi.org/10.1016/j.foreco.2011.08.006">Carbon pools and temporal dynamics along a rotation period in <em>quercus</em> dominated high forest and coppice with standards stands</a>. Forest Ecology and Management 262:1853–1862.
</div>
<div id="ref-glmulti" class="csl-entry" role="listitem">
Calcagno, V. 2020. <a href="https://CRAN.R-project.org/package=glmulti">Glmulti: Model selection and multimodel inference made easy</a>.
</div>
<div id="ref-CamachoOlmedoetal2002DinamicaEvolutiva" class="csl-entry" role="listitem">
Camacho-Olmedo, M., P. García-Martínez, Y. Jiménez-Olivencia, J. Menor-Toribio, and A. Paniza-Cabrera. 2002a. Dinámica evolutiva del paisaje vegetal de la <span>Alta Alpujarra</span> granadina en la segunda mitad del s. <span>XX</span>. Cuadernos Geográficos 32:25–42.
</div>
<div id="ref-CamachoOlmedoetal2002TransformacionPaisaje" class="csl-entry" role="listitem">
Camacho-Olmedo, M., Y. Jiménez-Olivencia, P. García-Martínez, J. Menor-Toribio, and A. Paniza-Cabrera. 2002b. La transformación de un paisaje de montaña: El proceso de abandono de la agricultura en la alta alpujarra granadina. Pages 547–558 Los espacios rurales entre hoy y mañana: Actas del <span>XI Coloquio</span> de <span>Geografía Rural</span>. Asociación de Geógrafos Españoles. <span>Universidad de Cantabria</span>, <span>Santander</span>.
</div>
<div id="ref-Canellasetal2004GrowthResponse" class="csl-entry" role="listitem">
Cañellas, I., M. Del-Río, S. Roig, and G. Montero. 2004. <a href="https://doi.org/10.1051/forest:2004017">Growth response to thinning in <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. Coppice stands in <span>Spanish</span> central mountain</a>. Annals of Forest Science 61:243–250.
</div>
<div id="ref-Canellasetal2008SilvicultureCarbon" class="csl-entry" role="listitem">
Cañellas, I., M. Sánchez-González, S. M. Bogino, P. Adame, C. Herrero, S. Roig, M. Tomé, J. A. Paulo, and F. Bravo. 2008. <a href="https://doi.org/10.1007/978-1-4020-8343-3_18">Silviculture and carbon sequestration in <span>Mediterranean</span> oak forests</a>. Pages 317–338 <em>in</em> F. Bravo, R. Jandl, V. LeMay, and K. von Gadow, editors. Managing forest ecosystems: The challenge of climate change. <span>Springer Netherlands</span>, <span>Dordrecht</span>.
</div>
<div id="ref-Canellasetal2017CarbonSequestration" class="csl-entry" role="listitem">
Cañellas, I., M. Sánchez-González, S. M. Bogino, P. Adame, D. Moreno-Fernández, C. Herrero, S. Roig, M. Tomé, J. A. Paulo, and F. Bravo. 2017. <a href="https://doi.org/10.1007/978-3-319-28250-3_20">Carbon <span>Sequestration</span> in <span>Mediterranean Oak Forests</span></a>. Pages 403–427 <em>in</em> F. Bravo, V. LeMay, and R. Jandl, editors. Managing <span>Forest Ecosystems</span>: <span>The Challenge</span> of <span>Climate Change</span>. <span>Springer International Publishing</span>, <span>Cham</span>.
</div>
<div id="ref-CarvalhoParresol2003AdditivityTree" class="csl-entry" role="listitem">
Carvalho, J. P., and B. R. Parresol. 2003. <a href="https://doi.org/10.1016/S0378-1127(02)00549-2">Additivity in tree biomass components of <span>Pyrenean</span> oak (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.)</a>. Forest Ecology and Management 179:269–276.
</div>
<div id="ref-CastanoSantamariaetal2013PotentialGround" class="csl-entry" role="listitem">
Castaño-Santamaría, J., M. Barrio-Anta, and P. Álvarez-Álvarez. 2013. <a href="https://doi.org/10.1505/146554813807700083">Potential above ground biomass production and total tree carbon sequestration in the major forest species in <span>NW Spain</span></a>. International Forestry Review 15:273–289.
</div>
<div id="ref-Chauchardetal2007PatternsLanduse" class="csl-entry" role="listitem">
Chauchard, S., C. Carcaillet, and F. Guibal. 2007. <a href="https://doi.org/10.1007/s10021-007-9065-4">Patterns of land-use abandonment control tree-recruitment and forest dynamics in <span>Mediterranean</span> mountains</a>. Ecosystems 10:936–948.
</div>
<div id="ref-Chiesietal2005ModellingCarbon" class="csl-entry" role="listitem">
Chiesi, M., F. Maselli, M. Bindi, L. Fibbi, P. Cherubini, E. Arlotta, G. Tirone, G. Matteucci, and G. Seufert. 2005. <a href="https://doi.org/10.1016/j.agrformet.2005.09.011">Modelling carbon budget of <span>Mediterranean</span> forests using ground and remote sensing measurements</a>. Agricultural and Forest Meteorology 135:22–34.
</div>
<div id="ref-CMAOT2014CartografiaEvaluacion" class="csl-entry" role="listitem">
CMAOT. 2014. Cartografía y evaluación de la vegetación y flora de los ecosistemas forestales de <span>Andalucía</span> a escala de detalle (1:10000). <span>Consejería de Medio Ambiente y Ordenación del Territorio. Junta de Andalucía</span>, <span>Sevilla, Spain</span>.
</div>
<div id="ref-Cotillasetal2016AbovegroundBelowground" class="csl-entry" role="listitem">
Cotillas, M., J. M. Espelta, E. Sánchez-Costa, and S. Sabaté. 2016. <a href="https://doi.org/10.1007/s10342-015-0932-9">Aboveground and belowground biomass allocation patterns in two <span>Mediterranean</span> oaks with contrasting leaf habit: An insight into carbon stock in young oak coppices</a>. European Journal of Forest Research 135:243–252.
</div>
<div id="ref-Cotillasetal2009GrowthResponse" class="csl-entry" role="listitem">
Cotillas, M., S. Sabaté, C. Gracia, and J. M. Espelta. 2009. <a href="https://doi.org/10.1016/j.foreco.2009.07.033">Growth response of mixed mediterranean oak coppices to rainfall reduction</a>. Forest Ecology and Management 258:1677–1683.
</div>
<div id="ref-Debusscheetal1999MediterraneanLandscape" class="csl-entry" role="listitem">
Debussche, M., J. Lepart, and A. Dervieux. 1999. <a href="https://doi.org/10.1046/j.1365-2699.1999.00316.x">Mediterranean landscape changes: Evidence from old postcards</a>. Global Ecology and Biogeography 8:3–15.
</div>
<div id="ref-Dionisioetal2012SatelliteBasedMonitoring" class="csl-entry" role="listitem">
Dionisio, M. A., D. Alcaraz-Segura, and J. Cabello. 2012. <a href="https://doi.org/10.5772/27711">Satellite-<span class="nocase">Based monitoring</span> of <span class="nocase">ecosystem functioning</span> in <span class="nocase">protected areas</span>: <span class="nocase">Recent trends</span> in the <span class="nocase">oak forests</span> (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.) of <span>Sierra Nevada</span> (<span>Spain</span>)</a>. Pages 355–374 International <span>Perspectives</span> on <span>Global Environmental Change</span>.
</div>
<div id="ref-EvansHudak2007MultiscaleCurvature" class="csl-entry" role="listitem">
Evans, J. S., and A. T. Hudak. 2007. <a href="https://doi.org/10.1109/TGRS.2006.890412">A multiscale curvature algorithm for classifying discrete return <span>LIDAR</span> in forested environments</a>. IEEE Transactions on Geoscience and Remote Sensing 45:1029–1038.
</div>
<div id="ref-Fadyetal2016EvolutionbasedApproach" class="csl-entry" role="listitem">
Fady, B., F. A. Aravanopoulos, P. Alizoti, C. Mátyás, G. von Wühlisch, M. Westergren, P. Belletti, B. Cvjetkovic, F. Ducci, G. Huber, C. T. Kelleher, A. Khaldi, M. B. D. Kharrat, H. Kraigher, K. Kramer, U. Mühlethaler, S. Peric, A. Perry, M. Rousi, H. Sbay, S. Stojnic, M. Tijardovic, I. Tsvetkov, M. C. Varela, G. G. Vendramin, and T. Zlatanov. 2016. <a href="https://doi.org/10.1016/j.foreco.2016.05.015">Evolution-based approach needed for the conservation and silviculture of peripheral forest tree populations</a>. Forest Ecology and Management 375:66–75.
</div>
<div id="ref-FAOPlanBleu2018StateMediterranean" class="csl-entry" role="listitem">
FAO, and Plan Bleu, editors. 2018. State of <span>Mediterranean</span> forests 2018. <span>Food and agriculture organization of the United Nations; Plan Bleu</span>, <span>Rome</span>.
</div>
<div id="ref-FernandezdeUnaetal2015StandCompetition" class="csl-entry" role="listitem">
Fernández-de-Uña, L., I. Cañellas, and G. Gea-Izquierdo. 2015. <a href="https://doi.org/10.1371/journal.pone.0122255">Stand competition determines how different tree species will cope with a warming climate</a>. PLOS ONE 10:e0122255.
</div>
<div id="ref-FernandezdeUnaetal2016DisentanglingEffect" class="csl-entry" role="listitem">
Fernández-de-Uña, L., N. G. McDowell, I. Cañellas, and G. Gea-Izquierdo. 2016. <a href="https://doi.org/10.1111/1365-2745.12544">Disentangling the effect of competition, <span>CO</span><span><sub>2</sub></span> and climate on intrinsic water-use efficiency and tree growth</a>. Journal of Ecology 104:678–690.
</div>
<div id="ref-Forrester2014StandlevelLight" class="csl-entry" role="listitem">
Forrester, D. I. 2014. <a href="https://doi.org/10.1016/j.ecolmodel.2013.12.021">A stand-level light interception model for horizontally and vertically heterogeneous canopies</a>. Ecological Modelling 276:14–22.
</div>
<div id="ref-Franco1990Quercus" class="csl-entry" role="listitem">
Franco, A. 1990. <em>Quercus</em> <span>L</span>. Pages 15–36 <em>in</em> A. Castroviejo, M. Laínz, G. López-González, P. Montserrat, F. Muñoz-Garmendia, J. Paiva, and L. Villar, editors. Flora <span>Ibérica</span>. <span>Real Jardín Botánico, CSIC</span>, <span>Madrid</span>.
</div>
<div id="ref-Gadowetal2012ForestStructure" class="csl-entry" role="listitem">
Gadow, K. v., C. Y. Zhang, C. Wehenkel, A. Pommerening, J. Corral-Rivas, M. Korol, S. Myklush, G. Y. Hui, A. Kiviste, and X. H. Zhao. 2012. <a href="https://doi.org/10.1007/978-94-007-2202-6₂">Forest structure and diversity</a>. Pages 29–83 <em>in</em> T. Pukkala and K. von Gadow, editors. Continuous cover forestry. <span>Springer Netherlands</span>, <span>Dordrecht</span>.
</div>
<div id="ref-GallardoLanchoGonzalezHernandez2004SequestrationCarbon" class="csl-entry" role="listitem">
Gallardo Lancho, J. F., and M. I. González Hernández. 2004. <a href="https://www.cabdirect.org/cabdirect/abstract/20053053334">Sequestration of carbon in <span>Spanish</span> deciduous oak forests.</a> Advances in Geoecology:341–351.
</div>
<div id="ref-Garciaetal2010EstimatingBiomass" class="csl-entry" role="listitem">
García, M., D. Riaño, E. Chuvieco, and F. M. Danson. 2010. <a href="https://doi.org/10.1016/j.rse.2009.11.021">Estimating biomass carbon stocks for a <span>Mediterranean</span> forest in central <span>Spain</span> using <span>LiDAR</span> height and intensity data</a>. Remote Sensing of Environment 114:816–830.
</div>
<div id="ref-Gauquelinetal2018MediterraneanForests" class="csl-entry" role="listitem">
Gauquelin, T., G. Michon, R. Joffre, R. Duponnois, D. Génin, B. Fady, M. Bou Dagher-Kharrat, A. Derridj, S. Slimani, W. Badri, M. Alifriqui, L. Auclair, R. Simenel, M. Aderghal, E. Baudoin, A. Galiana, Y. Prin, H. Sanguin, C. Fernandez, and V. Baldy. 2018. <a href="https://doi.org/10.1007/s10113-016-0994-3">Mediterranean forests, land use and climate change: A social-ecological perspective</a>. Regional Environmental Change 18:623–636.
</div>
<div id="ref-GeaIzquierdoCanellas2014LocalClimate" class="csl-entry" role="listitem">
Gea-Izquierdo, G., and I. Cañellas. 2014. <a href="https://doi.org/10.1007/s10021-013-9719-3">Local climate forces instability in long-term productivity of a <span>Mediterranean</span> oak along climatic gradients</a>. Ecosystems 17:228–241.
</div>
<div id="ref-GeaIzquierdoetal2013GrowthProjections" class="csl-entry" role="listitem">
Gea-Izquierdo, G., L. Fernández-de-Uña, and I. Cañellas. 2013. <a href="https://doi.org/10.1016/j.foreco.2013.05.058">Growth projections reveal local vulnerability of <span>Mediterranean</span> oaks with rising temperatures</a>. Forest Ecology and Management 305:282–293.
</div>
<div id="ref-GeaIzquierdoetal2017RiskyFuture" class="csl-entry" role="listitem">
Gea-Izquierdo, G., A. Nicault, G. Battipaglia, I. Dorado-Liñán, E. Gutiérrez, M. Ribas, and J. Guiot. 2017. <a href="https://doi.org/10.1111/gcb.13597">Risky future for <span>Mediterranean</span> forests unless they undergo extreme carbon fertilization</a>. Global Change Biology 23:2915–2927.
</div>
<div id="ref-biostat" class="csl-entry" role="listitem">
Gegzna, V. 2020. Biostat: <span>Routines</span> for basic (<span>Bio</span>)<span>Statistics</span>. manual.
</div>
<div id="ref-VSURF" class="csl-entry" role="listitem">
Genuer, R., J.-M. Poggi, and C. Tuleau-Malot. 2019. <a href="https://CRAN.R-project.org/package=VSURF">VSURF: Variable selection using random forests</a>.
</div>
<div id="ref-Goncalves2018EffectsForest" class="csl-entry" role="listitem">
Gonçalves, A. C. 2018. <a href="https://doi.org/10.5772/intechopen.76004">Effects of forest stand structure in biomass and carbon</a>. <em>in</em> G. Shukla and S. Chakravarty, editors. Forest biomass and carbon. <span>InTech</span>.
</div>
<div id="ref-GuerraHernandezetal2016ComparisonALS" class="csl-entry" role="listitem">
Guerra-Hernández, J., E. B. Görgens, J. García-Gutiérrez, L. C. E. Rodriguez, M. Tomé, and E. González-Ferreiro. 2016. <a href="https://doi.org/10.5721/EuJRS20164911">Comparison of <span>ALS</span> based models for estimating aboveground biomass in three types of <span>Mediterranean</span> forest</a>. European Journal of Remote Sensing 49:185–204.
</div>
<div id="ref-HampePetit2005ConservingBiodiversity" class="csl-entry" role="listitem">
Hampe, A., and R. J. Petit. 2005. <a href="https://doi.org/10.1111/j.1461-0248.2005.00739.x">Conserving biodiversity under climate change: The rear edge matters</a>. Ecology Letters 8:461–467.
</div>
<div id="ref-HerreraCalvo2016UsoPastoral" class="csl-entry" role="listitem">
Herrera Calvo, P. M. 2016. El uso pastoral como alternativa de gestión de los hábitats vinculados a los rebollares ibéricos. Revista Pastos 46:6–23.
</div>
<div id="ref-Ibanezetal2002MetodologiaComplementaria" class="csl-entry" role="listitem">
Ibáñez, J. J., J. Vayreda, and C. Gracia. 2002. Metodología complementaria al <span>Inventario Forestal Nacional</span> en <span>Catalunya</span>. Pages 67–77 <em>in</em> F. Bravo, M. Del Rio, and C. del Peso, editors. El <span>Inventario Forestal Nacional</span>. <span>Elemento</span> clave para la gestión forestal sostenible. <span>Fundación General de la Universidad de Valladolid</span>.
</div>
<div id="ref-IPCC2006ForestLand" class="csl-entry" role="listitem">
IPCC. 2006. <a href="http://www.ipcc-nggip.iges.or.jp/public/2006gl/index.htm">Forest land</a>. <em>in</em> H. S. Eggleston, L. Buendía, K. Miwa, T. Ngara, and K. Tanabe, editors. 2006 <span>IPCC</span> guidelines for national greenhouse gas inventories.
</div>
<div id="ref-Iversonetal2018EcosystemServices" class="csl-entry" role="listitem">
Iverson, L. R., A. H. Perera, G. M. Pastur, and U. Peterson. 2018. <a href="https://doi.org/10.1007/978-3-319-74515-2₉">Ecosystem services from forest landscapes: Where we are and where we go</a>. Pages 249–258 <em>in</em> A. H. Perera, U. Peterson, G. M. Pastur, and L. R. Iverson, editors. Ecosystem services from forest landscapes: Broadscale considerations. <span>Springer International Publishing</span>, <span>Cham</span>.
</div>
<div id="ref-JimenezOlivencia1991PaisajesSierra" class="csl-entry" role="listitem">
Jiménez Olivencia, Y. 1991. Los paisajes de <span>Sierra Nevada</span>: Cartografía de los sistemas naturales de una montaña mediterránea. <span>Universidad de Granada</span>, <span>Granada</span>.
</div>
<div id="ref-JimenezOlivenciaetal2015MedioSiglo" class="csl-entry" role="listitem">
Jiménez-Olivencia, Y., L. Porcel, and A. Caballero. 2015. Medio siglo en la evolución de los paisajes naturales y agrarios de <span>Sierra Nevada</span> (<span>España</span>). Boletín de la Asociación de Geógrafos Españoles 68:205–232.
</div>
<div id="ref-Kutschetal2009EcophysiologicalCharacteristics" class="csl-entry" role="listitem">
Kutsch, W. L., C. Wirth, J. Kattge, S. Nöllert, M. Herbst, and L. Kappen. 2009. <a href="https://doi.org/10.1007/978-3-540-92706-8_4">Ecophysiological characteristics of mature trees and stands - consequences for old-growth forest productivity</a>. Pages 57–79 <em>in</em> C. Wirth, G. Gleixner, and M. Heimann, editors. Old-growth forests: Function, fate and value. <span>Springer Berlin Heidelberg</span>, <span>Berlin, Heidelberg</span>.
</div>
<div id="ref-Lauterbach2007AssessmentExisting" class="csl-entry" role="listitem">
Lauterbach, S. 2007. <a href="https://doi.org/10.1300/J091v25n01_04">An assessment of existing demand for carbon sequestration services</a>. Journal of Sustainable Forestry 25:75–98.
</div>
<div id="ref-Lefskyetal2002LidarRemote" class="csl-entry" role="listitem">
Lefsky, M. A., W. B. Cohen, G. G. Parker, and D. J. Harding. 2002. <a href="https://doi.org/10.1641/0006-3568(2002)052[0019:LRSFES]2.0.CO;2">Lidar remote sensing for ecosystem studies</a>. BioScience 52:19.
</div>
<div id="ref-randomForest" class="csl-entry" role="listitem">
Liaw, A., and M. Wiener. 2002. <a href="https://CRAN.R-project.org/doc/Rnews/">Classification and regression by randomForest</a>. R News 2:18–22.
</div>
<div id="ref-Loriteetal2008PhytosociologicalReview" class="csl-entry" role="listitem">
Lorite, J., C. Salazar, J. Peñast, and F. Valle. 2008. <a href="https://doi.org/10.1080/12538078.2008.10516105">Phytosociological review on the forests of <em><span>Q</span>uercus pyrenaica</em> <span>Willd</span>.</a> Acta Botanica Gallica 155:219–233.
</div>
<div id="ref-Luyssaertetal2008OldgrowthForests" class="csl-entry" role="listitem">
Luyssaert, S., E.-D. Schulze, A. Börner, A. Knohl, D. Hessenmöller, B. E. Law, P. Ciais, and J. Grace. 2008. <a href="https://doi.org/10.1038/nature07276">Old-growth forests as global carbon sinks</a>. Nature 455:213–215.
</div>
<div id="ref-MacDonaldetal2000AgriculturalAbandonment" class="csl-entry" role="listitem">
MacDonald, D., J. R. Crabtree, G. Wiesinger, T. Dax, N. Stamou, P. Fleury, J. Gutierrez Lazpita, and A. Gibon. 2000. <a href="https://doi.org/10.1006/jema.1999.0335">Agricultural abandonment in mountain areas of <span>Europe</span>: Environmental consequences and policy response</a>. Journal of Environmental Management 59:47–69.
</div>
<div id="ref-Makinecietal2015EcosystemCarbon" class="csl-entry" role="listitem">
Makineci, E., E. Ozdemir, S. Caliskan, E. Yilmaz, M. Kumbasli, A. Keten, V. Beskardes, H. Zengin, and H. Yilmaz. 2015. Ecosystem carbon pools of coppice-originated oak forests at different development stages. European Journal of Forest Research:15.
</div>
<div id="ref-MartinezPasturetal2018EcosystemServices" class="csl-entry" role="listitem">
Martínez Pastur, G., A. H. Perera, U. Peterson, and L. R. Iverson. 2018. <a href="https://doi.org/10.1007/978-3-319-74515-2₁">Ecosystem services from forest landscapes: An overview</a>. Pages 1–10 <em>in</em> A. H. Perera, U. Peterson, G. M. Pastur, and L. R. Iverson, editors. Ecosystem services from forest landscapes: Broadscale considerations. <span>Springer International Publishing</span>, <span>Cham</span>.
</div>
<div id="ref-McElhinnyetal2005ForestWoodland" class="csl-entry" role="listitem">
McElhinny, C., P. Gibbons, C. Brack, and J. Bauhus. 2005. <a href="https://doi.org/10.1016/j.foreco.2005.08.034">Forest and woodland stand structural complexity: <span>Its</span> definition and measurement</a>. Forest Ecology and Management 218:1–24.
</div>
<div id="ref-MesonMontoya1985VegetacionForestal" class="csl-entry" role="listitem">
Mesón, M. L., and J. M. Montoya. 1985. Vegetación forestal y degradación de los bosques de <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. En <span>España</span>. <span>Instituto Nacional de Investigaciones Agrarias</span>, <span>Madrid, España</span>.
</div>
<div id="ref-Metcalfeetal2018DynatopmodelImplementation" class="csl-entry" role="listitem">
Metcalfe, P., K. Beven, and J. Freer. 2018. <a href="https://CRAN.R-project.org/package=dynatopmodel">Dynatopmodel: <span>Implementation</span> of the dynamic <span>TOPMODEL</span> hydrological model</a>. manual.
</div>
<div id="ref-Monteroetal2005ProduccionBiomasa" class="csl-entry" role="listitem">
Montero, G., R. Ruiz-Peinado, and M. Muñoz. 2005. Producción de biomasa y fijación de <span>CO</span><span><sub>2</sub></span> por los bosques españoles.
</div>
<div id="ref-Montoya1982SelviculturaOrdenacion" class="csl-entry" role="listitem">
Montoya, J. 1982. Selvicultura, ordenación y economía de los rebollares de <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. Boletín de la Estación Central de Ecología 11:3–13.
</div>
<div id="ref-Montoya1983UsosAlternativos" class="csl-entry" role="listitem">
Montoya, J. 1983. Usos alternativos y conservación de los rebollares de <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. Boletín de la Estación Central de Ecología 12:35–42.
</div>
<div id="ref-MontoyaMeson1979SituacionActual" class="csl-entry" role="listitem">
Montoya, J., and M. Mesón. 1979. Situación actual y perspectivas futuras de los montes bajos de <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. Montes 193:211–216.
</div>
<div id="ref-MorenoFernandezetal2020InfluenceClimate" class="csl-entry" role="listitem">
Moreno-Fernández, D., J. Aldea, G. Gea-Izquierdo, I. Cañellas, and D. Martín-Benito. 2020. <a href="https://doi.org/10.1007/s10342-020-01322-3">Influence of climate and thinning on <em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. Coppices growth dynamics</a>. European Journal of Forest Research.
</div>
<div id="ref-MunozRojasetal2011ChangesLand" class="csl-entry" role="listitem">
Muñoz-Rojas, M., D. De la Rosa, L. M. Zavala, A. Jordán, and M. Anaya-Romero. 2011. <a href="https://doi.org/10.1016/j.scitotenv.2011.04.009">Changes in land cover and vegetation carbon stocks in <span>Andalusia</span>, <span>Southern Spain</span> (1956)</a>. Science of The Total Environment 409:2796–2806.
</div>
<div id="ref-MunozRojasetal2015ImpactLand" class="csl-entry" role="listitem">
Muñoz-Rojas, M., A. Jordán, L. M. Zavala, D. De la Rosa, S. K. Abd-Elmabod, and M. Anaya-Romero. 2015. <a href="https://doi.org/10.1002/ldr.2194">Impact of land use and land cover changes on organic carbon stocks in <span>Mediterranean</span> soils (1956)</a>. Land Degradation &amp; Development 26:168–179.
</div>
<div id="ref-Nabuursetal2013FirstSigns" class="csl-entry" role="listitem">
Nabuurs, G.-J., M. Lindner, P. J. Verkerk, K. Gunia, P. Deda, R. Michalak, and G. Grassi. 2013. <a href="https://doi.org/10.1038/nclimate1853">First signs of carbon sink saturation in <span>European</span> forest biomass</a>. Nature Climate Change 3:792–796.
</div>
<div id="ref-NoceSantini2018MediterraneanForest" class="csl-entry" role="listitem">
Noce, S., and M. Santini. 2018. Mediterranean forest ecosystem services and their vulnerability. <span>Foundation Euro-Mediterranean Center on Climate Change</span>.
</div>
<div id="ref-vegan" class="csl-entry" role="listitem">
Oksanen, J., F. G. Blanchet, M. Friendly, R. Kindt, P. Legendre, D. McGlinn, P. R. Minchin, R. B. O’Hara, G. L. Simpson, P. Solymos, M. H. H. Stevens, E. Szoecs, and H. Wagner. 2019. <a href="https://CRAN.R-project.org/package=vegan">Vegan: Community ecology package</a>.
</div>
<div id="ref-PasalodosTatoetal2017EvaluationTree" class="csl-entry" role="listitem">
Pasalodos-Tato, M., E. Almazán Riballo, G. Montero, and L. Diaz-Balteiro. 2017. <a href="https://doi.org/10.1080/17583004.2017.1306407">Evaluation of tree biomass carbon stock changes in <span>Andalusian</span> forests: Comparison of two methodologies</a>. Carbon Management 8:125–134.
</div>
<div id="ref-PerezLuqueetal2021EcologicalDiversity" class="csl-entry" role="listitem">
Pérez-Luque, A. J., B. M. Benito, F. J. Bonet-García, and R. Zamora. 2021. <a href="https://doi.org/10.3390/f12010010">Ecological <span class="nocase">diversity</span> within <span class="nocase">rear</span>-<span class="nocase">edge</span>: <span class="nocase">A case study</span> from <span>Mediterranean <em>Quercus</em></span> <em>pyrenaica</em> <span>Willd</span>.</a> Forests 12:10.
</div>
<div id="ref-PerezLuqueetal2019MapEcosystems" class="csl-entry" role="listitem">
Pérez-Luque, A. J., F. J. Bonet-García, and R. Zamora Rodríguez. 2019. <a href="https://doi.org/10.1594/PANGAEA.910176">Map of ecosystems types in <span>Sierra Nevada</span> mountain (southern <span>Spain</span>)</a>. data set, <span>PANGAEA</span>.
</div>
<div id="ref-PerezLuqueetal2020LanduseLegacies" class="csl-entry" role="listitem">
Pérez-Luque, A. J., G. Gea-Izquierdo, and R. Zamora. 2020. <a href="https://doi.org/10.1007/s10021-020-00547-y">Land-use legacies and climate change as a double challenge to oak forest resilience: Mismatches of geographical and ecological rear edges</a>. Ecosystems.
</div>
<div id="ref-PerezLuqueetal2015OntologicalSystem" class="csl-entry" role="listitem">
Pérez-Luque, A. J., R. Pérez-Pérez, F. J. Bonet-García, and P. J. Magaña. 2015. <a href="https://doi.org/10.1016/j.jag.2014.09.003">An ontological system based on <span>MODIS</span> images to assess ecosystem functioning of <span>Natura</span> 2000 habitats: <span>A</span> case study for <em><span>Quercus</span> pyrenaica</em> forests</a>. International Journal of Applied Earth Observation and Geoinformation 37:142–151.
</div>
<div id="ref-Petrosellietal2013EcologicalBehavior" class="csl-entry" role="listitem">
Petroselli, A., F. Vessella, L. Cavagnuolo, G. Piovesan, and B. Schirone. 2013. Ecological behavior of <em><span>Quercus</span> suber</em> and <em><span>Quercus</span> ilex</em> inferred by topographic wetness index (<span>TWI</span>):15.
</div>
<div id="ref-nlme" class="csl-entry" role="listitem">
Pinheiro, J., D. Bates, S. DebRoy, D. Sarkar, and R Core Team. 2021. <a href="https://CRAN.R-project.org/package=nlme"><span class="nocase">nlme</span>: Linear and nonlinear mixed effects models</a>.
</div>
<div id="ref-Piqueetal2018Spain" class="csl-entry" role="listitem">
Piqué, M., R. Laina, P. Vericat Grau, M. Beltrán, E. Busquets, and E. Tolosana. 2018. Spain. Pages 331–336 <em>in</em> A. Unrau, G. Becker, R. Spinelli, D. Lazdina, N. Magagnotti, V. N. Nicolescu, P. Buckley, D. Barlett, and P. D. Kofman, editors. Coppice forests in <span>Europe</span>. <span>Albert Ludwig University of Freiburg.</span>, <span>Freiburg i. Br., Germany</span>.
</div>
<div id="ref-PiqueVericat2015EvolutionPerspectives" class="csl-entry" role="listitem">
Piqué, M., and P. Vericat. 2015. <a href="http://gala.gre.ac.uk/id/eprint/14009/">Evolution and perspectives of coppice forests in <span>European</span> countries and <span>South Africa</span>. <span>Spain</span></a>. Pages 38–40 <em>in</em> D. Bartlett, V.-N. Nicolescu, and P. Pyttel, editors. Innovative management and multifunctional utilization of traditional coppice forests? An answer to future ecological, economic and social challenges in the <span>European</span> forestry sector. <span>FPS COST Action FP1301. EuroCoppice</span>.
</div>
<div id="ref-Pirononetal2017GeographicVariation" class="csl-entry" role="listitem">
Pironon, S., G. Papuga, J. Villellas, A. L. Angert, M. B. García, and J. D. Thompson. 2017. <a href="https://doi.org/10.1111/brv.12313">Geographic variation in genetic and demographic performance: New insights from an old biogeographical paradigm: <span>The</span> centre-periphery hypothesis</a>. Biological Reviews 92:1877–1909.
</div>
<div id="ref-Prieto1975BosquesSierra" class="csl-entry" role="listitem">
Prieto, P. 1975. Los bosques de <span>Sierra Nevada</span>. Anales Instituto Botanica Cavanilles 32:1099–1129.
</div>
<div id="ref-base" class="csl-entry" role="listitem">
R Core Team. 2020. <a href="https://www.R-project.org/">R: A language and environment for statistical computing</a>. R Foundation for Statistical Computing, Vienna, Austria.
</div>
<div id="ref-Rehmetal2015LosingYour" class="csl-entry" role="listitem">
Rehm, E. M., P. Olivas, J. Stroud, and K. J. Feeley. 2015. <a href="https://doi.org/10.1002/ece3.1645">Losing your edge: Climate change and the conservation value of range-edge populations</a>. Ecology and Evolution 5:4315–4326.
</div>
<div id="ref-delRioetal2003IndicesStand" class="csl-entry" role="listitem">
Rio, M. del, F. Montes, I. Cañellas, and G. Montero. 2003. Índices de diversidad estructural en masas forestales. Forest Systems 12:159–176.
</div>
<div id="ref-RubioCuadradoetal2018AbioticFactors" class="csl-entry" role="listitem">
Rubio-Cuadrado, Á., J. J. Camarero, R. Aspizua, M. Sánchez-González, L. Gil, and F. Montes. 2018. <a href="https://doi.org/10.1016/j.dendro.2018.08.001">Abiotic factors modulate post-drought growth resilience of <span>Scots</span> pine plantations and rear-edge <span>Scots</span> pine and oak forests</a>. Dendrochronologia 51:54–65.
</div>
<div id="ref-RuizdelaTorre2006FloraMayor" class="csl-entry" role="listitem">
Ruiz de la Torre, J. 2006. Flora mayor. <span>Organismo Autónomo Parques Nacionales</span>, <span>Madrid</span>.
</div>
<div id="ref-RuizPeinadoetal2017ForestManagement" class="csl-entry" role="listitem">
Ruiz-Peinado, R., A. Bravo-Oviedo, E. López-Senespleda, F. Bravo, and M. Del Rio. 2017. <a href="https://doi.org/10.5424/fs/2017262-11205">Forest management and carbon sequestration in the <span>Mediterranean</span> region: A review</a>. Forest Systems 26:eR04S.
</div>
<div id="ref-RuizPeinadoetal2012BiomassModels" class="csl-entry" role="listitem">
Ruiz-Peinado, R., G. Montero, and M. Del Rio. 2012. <a href="https://doi.org/10.5424/fs/2112211-02193">Biomass models to estimate carbon stocks for hardwood tree species</a>. Forest Systems 21:42.
</div>
<div id="ref-Salomonetal2017GeneralFailure" class="csl-entry" role="listitem">
Salomón, R., J. Rodríguez-Calcerrada, I. González-Doncel, L. Gil, and M. Valbuena-Carabaña. 2017. <a href="https://doi.org/10.1007/s12224-016-9257-9">On the general failure of coppice conversion into high forest in <em><span>Quercus</span> pyrenaica</em> stands: A genetic and physiological approach</a>. Folia Geobotanica 52:101–112.
</div>
<div id="ref-SanMigueletal2012BosquesMatorrales" class="csl-entry" role="listitem">
San Miguel, A., R. Perea, S. Roig, and M. Fernández-Olalla. 2012. Bosques y matorrales mediterráneos continentales. Revista Ambienta 98:66–72.
</div>
<div id="ref-SanchezPalomaresetal2008EstacionesEcologicas" class="csl-entry" role="listitem">
Sánchez Palomares, O., S. Roig, M. del Río, A. Rubio-Sánchez, and J. M. Gandullo. 2008. Las estaciones ecológicas actuales y potenciales de los rebollares españoles. <span>Instituto Nacional de Investigación y Tecnología Agraria y Alimentaria</span>, <span>Madrid</span>.
</div>
<div id="ref-Serradaetal1992CoppiceSystem" class="csl-entry" role="listitem">
Serrada, R., M. Allué, and A. Miguel. 1992. The coppice system in <span>Spain</span>. <span>Current</span> situation, state of art and major areas to be investigated. Annali dell’Istituto Sperimentale per la Selvicoltura 23:266–275.
</div>
<div id="ref-Simonsonetal2016ModellingAboveground" class="csl-entry" role="listitem">
Simonson, W., P. Ruiz-Benito, F. Valladares, and D. Coomes. 2016. <a href="https://doi.org/10.5194/bg-13-961-2016">Modelling above-ground carbon dynamics using multi-temporal airborne lidar: Insights from a <span>Mediterranean</span> woodland</a>. Biogeosciences 13:961–973.
</div>
<div id="ref-Stojanovicetal2017ForecastingTree" class="csl-entry" role="listitem">
Stojanović, M., R. Sánchez-Salguero, T. Levanič, J. Szatniewska, R. Pokorný, and J. C. Linares. 2017. <a href="https://doi.org/10.1016/j.foreco.2017.09.021">Forecasting tree growth in coppiced and high forests in the <span>Czech Republic</span>. <span>The</span> legacy of management drives the coming <em><span>Quercus</span> petraea</em> climate responses</a>. Forest Ecology and Management 405:56–68.
</div>
<div id="ref-Tardieuetal2018HumanNeeds" class="csl-entry" role="listitem">
Tardieu, L., B. Myus, and L. Tuffery. 2018. Human needs and ecosystem services. <em>in</em> FAO and Plan Bleu, editors. State of <span>Mediterranean</span> forests 2018. <span>Food and agriculture organization of the United Nations; Plan Bleu</span>, <span>Rome</span>.
</div>
<div id="ref-Tarregaetal2006ForestStructure" class="csl-entry" role="listitem">
Tárrega, R., L. Calvo, E. Marcos, and A. Taboada. 2006. <a href="https://doi.org/10.1016/j.foreco.2006.02.008">Forest structure and understory diversity in <span><em>Quercus</em></span> <em>pyrenaica</em> communities with different human uses and disturbances</a>. Forest Ecology and Management 227:50–58.
</div>
<div id="ref-ValbuenaCarabanaGil2013GeneticResilience" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., and L. Gil. 2013. <a href="https://doi.org/10.1007/s11295-013-0614-z">Genetic resilience in a historically profited root sprouting oak (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.) at its southern boundary</a>. Tree Genetics &amp; Genomes 9:1129–1142.
</div>
<div id="ref-ValbuenaCarabanaGil2017CentenaryCoppicing" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., and L. Gil. 2017. <a href="https://doi.org/10.1007/s11295-017-1105-4">Centenary coppicing maintains high levels of genetic diversity in a root resprouting oak (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.)</a>. Tree Genetics &amp; Genomes 13:28.
</div>
<div id="ref-ValbuenaCarabanaetal2010HistoricalRecent" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., U. L. de Heredia, P. Fuentes-Utrilla, I. González-Doncel, and L. Gil. 2010. Historical and recent changes in the <span>Spanish</span> forests: A socio-economic process. Review of Palaeobotany and Palynology 162:492–506.
</div>
<div id="ref-Vanhellemontetal2018SpeciesStructural" class="csl-entry" role="listitem">
Vanhellemont, M., R.-J. Bijlsma, L. De Keersmaeker, K. Vandekerkhove, and K. Verheyen. 2018. <a href="https://doi.org/10.1016/j.baae.2018.01.003">Species and structural diversity affect growth of oak, but not pine, in uneven-aged mature forests</a>. Basic and Applied Ecology 27:41–50.
</div>
<div id="ref-Vayredaetal2012SpatialPatterns" class="csl-entry" role="listitem">
Vayreda, J., M. Gracia, J. G. Canadell, and J. Retana. 2012. <a href="https://doi.org/10.1007/s10021-012-9582-7">Spatial patterns and predictors of forest carbon stocks in western <span>Mediterranean</span></a>. Ecosystems 15:1258–1270.
</div>
<div id="ref-Vericatetal2012GestionAdaptativa" class="csl-entry" role="listitem">
Vericat, P., M. Piqué, and R. Serrada, editors. 2012. Gestión adaptativa al cambio global en masas de <em>quercus</em> mediterráneos. <span>Centre Tecnològic Forestal de Catalunya (CTFC)</span>, <span>Solsona (Lleida)</span>.
</div>
<div id="ref-VilaCabreraetal2017NewForests" class="csl-entry" role="listitem">
Vilà-Cabrera, A., J. M. Espelta, J. Vayreda, and J. Pino. 2017. <a href="https://doi.org/10.1007/s10021-016-0019-6"><span>“<span>New</span> forests”</span> from the twentieth century are a relevant contribution for <span>C</span> storage in the <span>Iberian Peninsula</span></a>. Ecosystems 20:130–143.
</div>
<div id="ref-VillaescusaDiaz1998SegundoInventario" class="csl-entry" role="listitem">
Villaescusa, R., and R. Díaz, editors. 1998. Segundo <span>Inventario Forestal Nacional</span> (1986 - 1996). <span>Ministerio de Medio Ambiente, ICONA</span>, <span>Madrid, Spain</span>.
</div>
<div id="ref-Villanueva2005TercerInventario" class="csl-entry" role="listitem">
Villanueva, J. A., editor. 2005. Tercer <span>Inventario Forestal Nacional</span> (1997). <span>Ministerio de Medio Ambiente</span>, <span>Madrid, Spain</span>.
</div>
<div id="ref-Xiaoetal2019RemoteSensing" class="csl-entry" role="listitem">
Xiao, J., F. Chevallier, C. Gomez, L. Guanter, J. A. Hicke, A. R. Huete, K. Ichii, W. Ni, Y. Pang, A. F. Rahman, G. Sun, W. Yuan, L. Zhang, and X. Zhang. 2019. <a href="https://doi.org/10.1016/j.rse.2019.111383">Remote sensing of the terrestrial carbon cycle: A review of advances over 50 years</a>. Remote Sensing of Environment 233:111383.
</div>
<div id="ref-XimenezdeEmbun1961MonteBajo" class="csl-entry" role="listitem">
Ximénez de Embún, J. 1961. El monte bajo. <span>Ministerio de Agricultura.</span>, <span>Madrid</span>.
</div>
<div id="ref-Xuetal2012AgerelatedDecline" class="csl-entry" role="listitem">
Xu, C.-Y., M. H. Turnbull, D. T. Tissue, J. D. Lewis, R. Carson, W. S. F. Schuster, D. Whitehead, A. S. Walcroft, J. Li, and K. L. Griffin. 2012. <a href="https://doi.org/10.1111/j.1365-2745.2011.01933.x">Age-related decline of stand biomass accumulation is primarily due to mortality and not to reduction in <span>NPP</span> associated with individual tree physiology, tree growth or stand structure in a <em>quercus</em>-dominated forest: Age-related decline in a <em>quercus</em> forest</a>. Journal of Ecology 100:428–440.
</div>
<div id="ref-Zhaoetal2018UtilityMultitemporal" class="csl-entry" role="listitem">
Zhao, K., J. C. Suarez, M. Garcia, T. Hu, C. Wang, and A. Londo. 2018. <a href="https://doi.org/10.1016/j.rse.2017.09.007">Utility of multitemporal lidar for forest and carbon monitoring: Tree growth, biomass dynamics, and carbon flux</a>. Remote Sensing of Environment 204:883–897.
</div>
<div id="ref-Zinkoetal2005PlantSpecies" class="csl-entry" role="listitem">
Zinko, U., J. Seibert, M. Dynesius, and C. Nilsson. 2005. <a href="https://doi.org/10.1007/s10021-003-0125-0">Plant species numbers predicted by a topography-based groundwater flow index</a>. Ecosystems 8:430–441.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chap04-coloniza.html" class="pagination-link" aria-label="Colonization pattern of abandoned croplands by *Q. pyrenaica* in a Mediterranean mountain region">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Colonization pattern of abandoned croplands by <em>Q. pyrenaica</em> in a Mediterranean mountain region</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chap06-dendro.html" class="pagination-link" aria-label="Land-use legacies and climate change as a double challenge to oak forest resilience: mismatches of geographical and ecological rear edges">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land-use legacies and climate change as a double challenge to oak forest resilience: mismatches of geographical and ecological rear edges</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>