<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Ecological diversity within rear-edge: a case study from Mediterranean Quercus pyrenaica Willd. – Tesis Quarto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chap04-coloniza.html" rel="next">
<link href="./chap02-metodologia.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chap03-multivariante.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ecological diversity within rear-edge: a case study from Mediterranean <em>Quercus pyrenaica</em> Willd.</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tesis Quarto</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Título de tu tesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción General</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap02-metodologia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Metodología general</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap03-multivariante.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ecological diversity within rear-edge: a case study from Mediterranean <em>Quercus pyrenaica</em> Willd.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap04-coloniza.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Colonization pattern of abandoned croplands by <em>Q. pyrenaica</em> in a Mediterranean mountain region</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap05-carbon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Carbon sequestration of coppiced forests of <em>Q. pyrenaica</em>. An study case from the rear-edge of its distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap06-dendro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land-use legacies and climate change as a double challenge to oak forest resilience: mismatches of geographical and ecological rear edges</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Referencias</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-multivar-intro" id="toc-sec-multivar-intro" class="nav-link active" data-scroll-target="#sec-multivar-intro"><span class="header-section-number">4.1</span> Introduction</a></li>
  <li><a href="#sec-multivar-MatMet" id="toc-sec-multivar-MatMet" class="nav-link" data-scroll-target="#sec-multivar-MatMet"><span class="header-section-number">4.2</span> Material and Methods</a>
  <ul class="collapse">
  <li><a href="#sec-multivar-StudyArea" id="toc-sec-multivar-StudyArea" class="nav-link" data-scroll-target="#sec-multivar-StudyArea"><span class="header-section-number">4.2.1</span> Study area</a></li>
  <li><a href="#sec-multivar-EnvData" id="toc-sec-multivar-EnvData" class="nav-link" data-scroll-target="#sec-multivar-EnvData"><span class="header-section-number">4.2.2</span> Environmental data</a></li>
  <li><a href="#sec-multivar-ForAtri" id="toc-sec-multivar-ForAtri" class="nav-link" data-scroll-target="#sec-multivar-ForAtri"><span class="header-section-number">4.2.3</span> Forest attributes</a></li>
  <li><a href="#sec-multivar-Analysis" id="toc-sec-multivar-Analysis" class="nav-link" data-scroll-target="#sec-multivar-Analysis"><span class="header-section-number">4.2.4</span> Statistical analysis</a></li>
  </ul></li>
  <li><a href="#sec-multivar-Results" id="toc-sec-multivar-Results" class="nav-link" data-scroll-target="#sec-multivar-Results"><span class="header-section-number">4.3</span> Results</a></li>
  <li><a href="#sec-multivar-Discussion" id="toc-sec-multivar-Discussion" class="nav-link" data-scroll-target="#sec-multivar-Discussion"><span class="header-section-number">4.4</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#sec-multivar-EcolDiversity" id="toc-sec-multivar-EcolDiversity" class="nav-link" data-scroll-target="#sec-multivar-EcolDiversity"><span class="header-section-number">4.4.1</span> Ecological diversity within the rear-edge</a></li>
  <li><a href="#sec-multivarSummerRainfall" id="toc-sec-multivarSummerRainfall" class="nav-link" data-scroll-target="#sec-multivarSummerRainfall"><span class="header-section-number">4.4.2</span> The importance of summer rainfall at the micro-habitat level.</a></li>
  <li><a href="#sec-multivar-ImplicaForecast" id="toc-sec-multivar-ImplicaForecast" class="nav-link" data-scroll-target="#sec-multivar-ImplicaForecast"><span class="header-section-number">4.4.3</span> Implications for forecasting and modelling.</a></li>
  </ul></li>
  <li><a href="#sec-multivar-Conclusion" id="toc-sec-multivar-Conclusion" class="nav-link" data-scroll-target="#sec-multivar-Conclusion"><span class="header-section-number">4.5</span> Concluding remarks: biodiversity from the genetics to the landscape.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-multivar" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ecological diversity within rear-edge: a case study from Mediterranean <em>Quercus pyrenaica</em> Willd.</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Antonio J. Pérez-Luque</strong>; Blas M. Benito; Francisco J. Bonet-García &amp; Regino Zamora. 2021. <em>Forests</em>, 12(1): 10. <a href="https://dx.doi.org/10.3390/f12010010">doi:10.3390/f12010010</a></p>
</blockquote>
<section id="abstract" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="abstract">Abstract</h5>
<p><br>
</p>
<p>Understanding the ecology of populations located in the rear-edge of their distribution is key to assess the response of the species to changing environmental conditions. Here we focus on rear-edge populations of <em>Quercus pyrenaica</em> in Sierra Nevada (southern Iberian Peninsula) to analyze their ecological and floristic diversity. We perform multivariate analyses using high-resolution environmental information and forest inventories to determine how environmental variables differ among oak populations, and to identify population groups based on environmental and floristic composition. We find that water availability is a key variable in explaining the distribution of <em>Q. pyrenaica</em> and the floristic diversity of their accompanying communities within its rear edge. Three cluster of oak populations were identified based on environmental variables. We found differences among these clusters regarding plant diversity, but no for forest attributes. A remarkable match between the populations clustering derived from analysis of environmental variables and the ordination of the populations according to species composition was found. The diversity of ecological behaviors for <em>Q. pyrenaica</em> populations in this rear edge are consistent with the high genetic diversity shown by populations of this oak in the Sierra Nevada. The identification of differences between oak populations within the rear-edge with respect to environmental variables can aid to plan the forest management and restoration actions, particularly considering the importance of some environmental factors in key ecological aspects.</p>
</section>
<section id="sec-multivar-intro" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-multivar-intro"><span class="header-section-number">4.1</span> Introduction</h2>
<p>The study of ecological dynamics within the rear edge populations is considered essential to establish proper management guidelines under current climate uncertainties <span class="citation" data-cites="Fadyetal2016EvolutionbasedApproach">(<a href="#ref-Fadyetal2016EvolutionbasedApproach" role="doc-biblioref">Fady et al. 2016</a>)</span>. Rear-edge populations are often adapted to local environmental conditions at the limit of the species’ ecological amplitude, and often show a long-term persistence <span class="citation" data-cites="HampePetit2005ConservingBiodiversity">(<a href="#ref-HampePetit2005ConservingBiodiversity" role="doc-biblioref">Hampe and Petit 2005</a>)</span>. Local responses to environmental changes may differ from the species mean response <span class="citation" data-cites="Castroetal2004SeedlingEstablishment Benavidesetal2013DirectIndirect GeaIzquierdoCanellas2014LocalClimate Matiasetal2017ContrastingGrowth">(<a href="#ref-Castroetal2004SeedlingEstablishment" role="doc-biblioref">Castro et al. 2004</a>, <a href="#ref-Benavidesetal2013DirectIndirect" role="doc-biblioref">Benavides et al. 2013</a>, <a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>, <a href="#ref-Matiasetal2017ContrastingGrowth" role="doc-biblioref">Matías et al. 2017</a>)</span>, and such differences may either promote or hamper the survival of edge populations under global change <span class="citation" data-cites="BenitoGarzonetal2011IntraspecificVariability">(<a href="#ref-BenitoGarzonetal2011IntraspecificVariability" role="doc-biblioref">Benito-Garzón et al. 2011</a>)</span>. Furthermore, the heterogeneity in the response to climate change observed across ecological and geographical gradients <span class="citation" data-cites="GeaIzquierdoetal2013GrowthProjections Chenetal2015InfluenceClimate DoradoLinanetal2019GeographicalAdaptation PerezLuqueetal2020LanduseLegacies">(<a href="#ref-GeaIzquierdoetal2013GrowthProjections" role="doc-biblioref">Gea-Izquierdo et al. 2013</a>, <a href="#ref-Chenetal2015InfluenceClimate" role="doc-biblioref">Chen et al. 2015</a>, <a href="#ref-DoradoLinanetal2019GeographicalAdaptation" role="doc-biblioref">Dorado-Liñán et al. 2019</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>, justifies the need to incorporate fine-scale variation of environment variables throughout species ranges to better understand species responses to global change <span class="citation" data-cites="DeFrenneetal2013MicroclimateModerates Oldfatheretal2020RangeEdges">(<a href="#ref-DeFrenneetal2013MicroclimateModerates" role="doc-biblioref">De Frenne et al. 2013</a>, <a href="#ref-Oldfatheretal2020RangeEdges" role="doc-biblioref">Oldfather et al. 2020</a>)</span>. This is particularly important for mountain landscapes, where the topographic complexity may cause a decoupling between the climate and the geographic spaces <span class="citation" data-cites="ElsenTingley2015GlobalMountain Pirononetal2015GeographicClimatic">(<a href="#ref-ElsenTingley2015GlobalMountain" role="doc-biblioref">Elsen and Tingley 2015</a>, <a href="#ref-Pirononetal2015GeographicClimatic" role="doc-biblioref">Pironon et al. 2015</a>)</span>.</p>
<p>The environmental heterogeneity (microclimate, geomorphology, topography, etc.) found in mountains allows the existence of a diverse plethora of ecological conditions at very fine spatial scales <span class="citation" data-cites="Hannahetal2014FinegrainModeling KornerSpehn2019HumboldtianView">(<a href="#ref-Hannahetal2014FinegrainModeling" role="doc-biblioref">Hannah et al. 2014</a>, <a href="#ref-KornerSpehn2019HumboldtianView" role="doc-biblioref">Körner and Spehn 2019</a>)</span>, offering an excellent opportunity to study ecological responses to future environmental changes <span class="citation" data-cites="SpehnKorner2009MountainLaboratory Kohleretal2014MountainsClimate Payneetal2017OpportunitiesResearch Zamoraetal2017GlobalChange">(<a href="#ref-SpehnKorner2009MountainLaboratory" role="doc-biblioref">Spehn and Korner 2009</a>, <a href="#ref-Kohleretal2014MountainsClimate" role="doc-biblioref">Kohler et al. 2014</a>, <a href="#ref-Payneetal2017OpportunitiesResearch" role="doc-biblioref">Payne et al. 2017</a>, <a href="#ref-Zamoraetal2017GlobalChange" role="doc-biblioref">Zamora et al. 2017</a>)</span>. Some tree species, such as <em>Pinus sylvestris</em> and <em>Quercus pyrenaica</em>, have their rear-edge populations located in mountainous areas of southern Europe. The topographic heterogeneity of such habitats, which act as microclimatic islands within a region of unsuitable climate for the persistence of these species, is likely to have a significant impact on persistence of these populations <span class="citation" data-cites="MeineriHylander2017FinegrainLargedomain">(<a href="#ref-MeineriHylander2017FinegrainLargedomain" role="doc-biblioref">Meineri and Hylander 2017</a>)</span>. In these areas, the climate variation controlled by topography <span class="citation" data-cites="Franklinetal2013ModelingPlant Potteretal2013MicroclimaticChallenges">(<a href="#ref-Franklinetal2013ModelingPlant" role="doc-biblioref">Franklin et al. 2013</a>, <a href="#ref-Potteretal2013MicroclimaticChallenges" role="doc-biblioref">Potter et al. 2013</a>)</span> is hard to capture, and the fine scales non-climate factors (both biotic and abiotic) can be at least as much relevant for species distribution as climate <span class="citation" data-cites="Loetal2010WordCaution">(<a href="#ref-Loetal2010WordCaution" role="doc-biblioref">Lo et al. 2010</a>)</span> by modulating the direct effect of regional climate on individuals. Additionally, there are finer scale gradients nested within each mountain range, which reproduce rear, optimum and leading edge conditions making the interpretation of what is currently occurring in the so-called rear edge extremely complex <span class="citation" data-cites="Benavidesetal2013DirectIndirect Oldfatheretal2020RangeEdges">(<a href="#ref-Benavidesetal2013DirectIndirect" role="doc-biblioref">Benavides et al. 2013</a>, <a href="#ref-Oldfatheretal2020RangeEdges" role="doc-biblioref">Oldfather et al. 2020</a>)</span>. When environmental conditions are homogeneous, similar responses are expected which facilitate future forecast. Conversely, if the environmental conditions are heterogeneous, we expect a variety of responses, which forces us to consider different future scenarios at a very fine spatial scale, since climate change sensitivities could strongly vary at local scales <span class="citation" data-cites="Lindneretal2010ClimateChange GeaIzquierdoCanellas2014LocalClimate Titoetal2020MountainEcosystems">(<a href="#ref-Lindneretal2010ClimateChange" role="doc-biblioref">Lindner et al. 2010</a>, <a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>, <a href="#ref-Titoetal2020MountainEcosystems" role="doc-biblioref">Tito et al. 2020</a>)</span>.</p>
<p><em>Quercus pyrenaica</em> Willd. (Pyrenean oak) is a deciduous Mediterranean tree species widely distributed throughout south-western France and the Iberian Peninsula reaching their southern limit in mountain areas of northern Morocco <span class="citation" data-cites="Franco1990Quercus">(<a href="#ref-Franco1990Quercus" role="doc-biblioref">Franco 1990</a>)</span>. The rear-edge populations of this species are restricted to high-mountain areas where these populations persists as isolated nuclei with ecological conditions very different from those of the main distribution area. <em>Q. pyrenaica</em> is considered one of the Mediterranean trees with a higher sensitivity to climate change <span class="citation" data-cites="BenitoGarzonetal2008EffectsClimate GarciaValdesetal2013ChasingMoving">(<a href="#ref-BenitoGarzonetal2008EffectsClimate" role="doc-biblioref">Benito-Garzón et al. 2008</a>, <a href="#ref-GarciaValdesetal2013ChasingMoving" role="doc-biblioref">García-Valdés et al. 2013</a>)</span>. Several studies analyzed the potential effects of climate change on distribution of this species at different spatio-temporal scales <span class="citation" data-cites="Benitoetal2011SimulatingPotential BenitoGarzonetal2008EffectsClimate BenitoGarzonetal2007PredictiveModelling Felicisimo2011ImpactosVulnerabilidad GeaIzquierdoetal2013GrowthProjections RuizBenitoetal2013PatternsDrivers RuizLabourdetteetal2013ChangesTree Urbietaetal2011MediterraneanPine">(<a href="#ref-BenitoGarzonetal2007PredictiveModelling" role="doc-biblioref">Benito-Garzón et al. 2007</a>, <a href="#ref-BenitoGarzonetal2008EffectsClimate" role="doc-biblioref">2008</a>, <a href="#ref-Benitoetal2011SimulatingPotential" role="doc-biblioref">Benito et al. 2011</a>, <a href="#ref-Felicisimo2011ImpactosVulnerabilidad" role="doc-biblioref">Felicísimo 2011</a>, <a href="#ref-Urbietaetal2011MediterraneanPine" role="doc-biblioref">Urbieta et al. 2011</a>, <a href="#ref-GeaIzquierdoetal2013GrowthProjections" role="doc-biblioref">Gea-Izquierdo et al. 2013</a>, <a href="#ref-RuizBenitoetal2013PatternsDrivers" role="doc-biblioref">Ruiz-Benito et al. 2013</a>, <a href="#ref-RuizLabourdetteetal2013ChangesTree" role="doc-biblioref">Ruiz-Labourdette et al. 2013</a>)</span> forecasting a decrease in the suitable area of this tree species, particularly in its southern range.</p>
<p>Considering that the conservation strategies for tree species need to take into account the peculiarities of the rear-edge populations <span class="citation" data-cites="HampePetit2005ConservingBiodiversity Fadyetal2016EvolutionbasedApproach Rehmetal2015LosingYour">(<a href="#ref-HampePetit2005ConservingBiodiversity" role="doc-biblioref">Hampe and Petit 2005</a>, <a href="#ref-Rehmetal2015LosingYour" role="doc-biblioref">Rehm et al. 2015</a>, <a href="#ref-Fadyetal2016EvolutionbasedApproach" role="doc-biblioref">Fady et al. 2016</a>)</span>, and the high vulnerability to climate change of <em>Q. pyrenaica</em> <span class="citation" data-cites="GarciaValdesetal2013ChasingMoving">(<a href="#ref-GarciaValdesetal2013ChasingMoving" role="doc-biblioref">García-Valdés et al. 2013</a>)</span>, here we focus on the rear-edge populations of this species in the mountains of southern Iberian Peninsula to answer the question: Are the environmental conditions of the rear-edge populations of <em>Q. pyrenaica</em> in Sierra Nevada homogeneous?. The answer to this question may be useful to analyze how the predicted climate changes would impact the rear-edge population, providing valuable information for the development of efficient forest management and restoration plans. We selected rear-edge populations of <em>Q. pyrenaica</em> located in Sierra Nevada (Southern Iberian Peninsula), since peripheral forest tree populations located in mountain areas represent natural laboratories for resolving priority research questions <span class="citation" data-cites="Fadyetal2016EvolutionbasedApproach">(<a href="#ref-Fadyetal2016EvolutionbasedApproach" role="doc-biblioref">Fady et al. 2016</a>)</span>. Particularly, we hypothesize that the rear-edge populations of <em>Q. pyrenaica</em> located in mountain areas are representative of different environmental conditions at local scale due to the strong topographic gradients available at the edge of its range. In this work we analyze whether these rear-edge populations inhabit similar environmental conditions. We also assess to what extent the environmental variability is matched by the floristic diversity of <em>Q. pyrenaica</em> forests. Specifically, the objectives of the work were: <em>(i)</em> to determine the most important environmental variables for the distribution of Pyrenean oak populations in Sierra Nevada; <em>(ii)</em> to identify groups of Pyrenean oak populations based on floristic composition and environmental conditions; and <em>(iii)</em> to unveil whether the rear-edge populations clustering according to environmental variables coincides with their grouping based on their floristic composition.</p>
<div id="fig-multivar-location-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multivar-location-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/multivariante/dist_map_multivariante.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multivar-location-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Distribution of <em>Quercus pyrenaica</em> forests in the Iberian Peninsula (<strong>a</strong>) and location of the patches in Sierra Nevada mountain range (<strong>b</strong>). Name of the each population as in Table~ref{tab:multivar:tpop}.
</figcaption>
</figure>
</div>
</section>
<section id="sec-multivar-MatMet" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-multivar-MatMet"><span class="header-section-number">4.2</span> Material and Methods</h2>
<section id="sec-multivar-StudyArea" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="sec-multivar-StudyArea"><span class="header-section-number">4.2.1</span> Study area</h3>
<p>The study was conducted at the Sierra Nevada (Andalusia, SE Spain; Figure&nbsp;<a href="#fig:multivar:location-map" data-reference-type="ref" data-reference="fig:multivar:location-map">[fig:multivar:location-map]</a>), a mountainous region covering more than 2000 km<sup>2</sup> with an elevation range of between 860 and 3482 <em>m.a.s.l.</em> The climate is Mediterranean, characterized by cold winters and hot summers, with a pronounced summer drought. The annual average temperature decreases in altitude from 12-16 °C below 1500 <em>m.a.s.l.</em> to 0 °C above 3000 <em>m.a.s.l.</em>. Annual precipitation ranges from less than 250 mm in the lowest areas of the mountain range to more than 700 mm in the highest peaks. Winter precipitation is mainly in the form of snow above 2000 <em>m.a.s.l.</em>. Additionally, the complex orography causes strong climatic contrasts between south and north-facing slopes. This mountain range is considered one of the most important biodiversity hotspots in the Mediterranean region <span class="citation" data-cites="Blancaetal1998ThreatenedVascular">(<a href="#ref-Blancaetal1998ThreatenedVascular" role="doc-biblioref">Blanca et al. 1998</a>)</span>, hosting 105 endemic plant species for a total of 2353 taxa of vascular plants (33&nbsp;</p>
<div id="tbl-multivar-tpop" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multivar-tpop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Description of the <em>Q. pyrenaica</em> populations in Sierra Nevada. For elevation, minimum and maximum values are in brackets. The latitude and longitude coordinates referred to polygon centroid.
</figcaption>
<div aria-describedby="tbl-multivar-tpop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>llllllll@{}} Oak poulation</th>
<th>Code</th>
<th>River valley</th>
<th>Municipalities</th>
<th>Elevation (m)</th>
<th>Latitude</th>
<th>Longitude</th>
<th>Area (ha)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>El Camarate</td>
<td>CAM</td>
<td>Alhama</td>
<td>Lugros</td>
<td>1740 (1441-2026)</td>
<td>37º 10’ 29.49’’ N</td>
<td>3º 15’ 24.33’’ W</td>
<td>457.15</td>
</tr>
<tr class="even">
<td>Robledal de San Juan</td>
<td>GEN</td>
<td>Genil</td>
<td>Güejar-Sierra</td>
<td>1519 (1189-1899)</td>
<td>37º 7’ 29.63’’ N</td>
<td>3º 21’ 54.60’’ W</td>
<td>395</td>
</tr>
<tr class="odd">
<td>Loma de la Perdíz</td>
<td>MON</td>
<td>Monachil</td>
<td>Monachil</td>
<td>1780 (1564-1990)</td>
<td>37º 5’ 54.87’’ N</td>
<td>3º 25’ 46.65’’ W</td>
<td>204.55</td>
</tr>
<tr class="even">
<td>Umbría de la Dehesa de Dílar</td>
<td>DIL</td>
<td>Dílar</td>
<td>Dílar</td>
<td>1764 (1478-1960)</td>
<td>37º 3’ 33.61’’ N</td>
<td>3º 28’ 29.07’’ W</td>
<td>154.07</td>
</tr>
<tr class="odd">
<td>Loma de Enmedio</td>
<td>DUR</td>
<td>Dúrcal</td>
<td>Dúrcal</td>
<td>1824 (1530-2035)</td>
<td>37º 1’ 58.75’’ N</td>
<td>3º 28’ 38.44’’ W</td>
<td>137.04</td>
</tr>
<tr class="even">
<td>El Robledal de Cáñar</td>
<td>CAN</td>
<td>Chico</td>
<td>Cáñar</td>
<td>1687 (1366-1935)</td>
<td>36º 57’ 28.04’’ N</td>
<td>3º 25’ 57.10’’ W</td>
<td>436.2</td>
</tr>
<tr class="odd">
<td>Loma de la Matanza y Loma de Ramón</td>
<td>POQ</td>
<td>Poqueira</td>
<td>Soportújar, Pampaneira, Bubión, Capileira</td>
<td>1740 (1214-1981)</td>
<td>36º 57’ 58.90’’ N</td>
<td>3º 22’ 55.12’’ W</td>
<td>458.95</td>
</tr>
<tr class="even">
<td>Loma de los Lotes</td>
<td>TRE</td>
<td>Trevélez</td>
<td>Pórtugos, Busquístar</td>
<td>1692 (1312-1963)</td>
<td>36º 58’ 37.38’’ N</td>
<td>3º 17’ 25.75’’ W</td>
<td>197.92</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Quercus pyrenaica</em> is a deciduous species extending through southwestern France, the Iberian Peninsula and northern Morocco <span class="citation" data-cites="Franco1990Quercus">(<a href="#ref-Franco1990Quercus" role="doc-biblioref">Franco 1990</a>)</span>. The forests of this species reach their southernmost European limit in Andalusian mountains such as Sierra Nevada, where eight populations have been identified (Figure&nbsp;<a href="#fig:multivar:location-map" data-reference-type="ref" data-reference="fig:multivar:location-map">[fig:multivar:location-map]</a>a; Table&nbsp;<a href="#tab:multivar:tpop" data-reference-type="ref" data-reference="tab:multivar:tpop">[tab:multivar:tpop]</a>) on the basis of their isolated geographic locations in deep valleys separated by distances considerably longer than the average dispersal distances of the seeds by birds such as Eurasian jay (<em>Garrulus glandarius</em>) <span class="citation" data-cites="Gomez2003SpatialPatterns ValbuenaCarabanaetal2005GeneFlow">(<a href="#ref-Gomez2003SpatialPatterns" role="doc-biblioref">Gómez 2003</a>, <a href="#ref-ValbuenaCarabanaetal2005GeneFlow" role="doc-biblioref">Valbuena-Carabaña et al. 2005</a>)</span>. They are distributed on siliceous soils both in the northwestern and southern slopes of the mountain range and are often associated to major river valleys. These oak woodlands represent a rear edge of their distribution <span class="citation" data-cites="HampePetit2005ConservingBiodiversity">(<a href="#ref-HampePetit2005ConservingBiodiversity" role="doc-biblioref">Hampe and Petit 2005</a>)</span>, containing high levels of intraspecific genetic diversity <span class="citation" data-cites="ValbuenaCarabanaGil2013GeneticResilience">(<a href="#ref-ValbuenaCarabanaGil2013GeneticResilience" role="doc-biblioref">Valbuena-Carabaña and Gil 2013</a>)</span>. Their conservation status for southern Spain is “Vulnerable”, and it is expected to suffer from climate change, potentially reducing its suitable habitats in the near future <span class="citation" data-cites="GeaIzquierdoetal2013GrowthProjections GeaIzquierdoetal2017RiskyFuture">(<a href="#ref-GeaIzquierdoetal2013GrowthProjections" role="doc-biblioref">Gea-Izquierdo et al. 2013</a>, <a href="#ref-GeaIzquierdoetal2017RiskyFuture" role="doc-biblioref">2017</a>)</span>.</p>
<p>The distribution of <em>Q. pyrenaica</em> forests in Sierra Nevada was delimited using the updated version of the forest map of Sierra Nevada at 1:10 000 scale <span class="citation" data-cites="CMAOT2014CartografiaEvaluacion PerezLuqueetal2019MapEcosystems">(<a href="#ref-CMAOT2014CartografiaEvaluacion" role="doc-biblioref">CMAOT 2014</a>, <a href="#ref-PerezLuqueetal2019MapEcosystems" role="doc-biblioref">Pérez-Luque et al. 2019</a>)</span>. Black and white ortophotographies from 2001 (0.5-m of spatial resolution) and false color aerial photographies (Color Infrared) from 2005 (1-m resolution) were used to correct errors by detailed photographic interpretation, resulting in a detailed map of oak forests (Figure&nbsp;<a href="#fig:multivar:location-map" data-reference-type="ref" data-reference="fig:multivar:location-map">[fig:multivar:location-map]</a>b). Forest patches with at least 50 &nbsp;</p>
</section>
<section id="sec-multivar-EnvData" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="sec-multivar-EnvData"><span class="header-section-number">4.2.2</span> Environmental data</h3>
<p>For each oak population we obtained the values of 30 environmental variables selected to represent different direct and indirect gradients important for plant distribution <span class="citation" data-cites="GuisanZimmermann2000PredictiveHabitat Williamsetal2012WhichEnvironmental">(<a href="#ref-GuisanZimmermann2000PredictiveHabitat" role="doc-biblioref">Guisan and Zimmermann 2000</a>, <a href="#ref-Williamsetal2012WhichEnvironmental" role="doc-biblioref">Williams et al. 2012</a>)</span>: temperature, water availability, topography, solar radiation and land-use (Table&nbsp;<a href="#tab:multivar:tvars" data-reference-type="ref" data-reference="tab:multivar:tvars">[tab:multivar:tvars]</a>). Observed climate data (1960-2010) from 43 meteorological stations 50 km around Sierra Nevada, compiled by Sierra Nevada Global Change Observatory <span class="citation" data-cites="Zamoraetal2017GlobalChange">(<a href="#ref-Zamoraetal2017GlobalChange" role="doc-biblioref">Zamora et al. 2017</a>)</span>, were used as input to compute high resolution (100 x 100 m pixel-size) climate maps <span class="citation" data-cites="Benitoetal2014ClimateSimulations">(<a href="#ref-Benitoetal2014ClimateSimulations" role="doc-biblioref">Benito et al. 2014</a>)</span> based on the mapping method proposed by <span class="citation" data-cites="Ninyerolaetal2000MethodologicalApproach">Ninyerola et al. (<a href="#ref-Ninyerolaetal2000MethodologicalApproach" role="doc-biblioref">2000</a>)</span>. Seasonal and annual maps with the averages of direct solar radiation and insolation time were computing using the GIS GRASS module r.sun <span class="citation" data-cites="Neteleretal2012GRASSGIS SuriHofierka2004NewGISbased">(<a href="#ref-Neteleretal2012GRASSGIS" role="doc-biblioref">Neteler et al. 2012</a>, <a href="#ref-SuriHofierka2004NewGISbased" role="doc-biblioref"><strong>SuriHofierka2004NewGISbased?</strong></a>)</span>. From a high-resolution digital elevation model (10-m; Department of the Environment, Regional Government of Andalusia) several topographic variables were derived: elevation, slope, aspect, E-W and N-S gradients, topographic position (difference in elevation between a cell and surrounding cells within a 1000 meter radius)<span class="citation" data-cites="Guisanetal1999GLMCCA">(<a href="#ref-Guisanetal1999GLMCCA" role="doc-biblioref">Guisan et al. 1999</a>)</span>. Also, topographic wetness index and flow accumulation were computed using the r.terraflow module of GRASS GIS. As a surrogate of anthropogenic influence, we computed the frequency of human infrastructures in a 2000 meter radius buffer. Finally, for each environmental variable we extracted the values for all the 100 m size pixels contained within each oak population (Figure&nbsp;<a href="#fig:multivar:schemamulti" data-reference-type="ref" data-reference="fig:multivar:schemamulti">[fig:multivar:schemamulti]</a>).</p>
<div id="tbl-multivar-tvars" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multivar-tvars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.2: Description of environmental variables and forest attributes used in our analysis
</figcaption>
<div aria-describedby="tbl-multivar-tvars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Category</strong></th>
<th><strong>Code</strong></th>
<th><strong>Description</strong></th>
<th><strong>Units</strong></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>multirow{13}{*}{Climate}</td>
<td>precYE</td>
<td>Annual precipitation</td>
<td>mm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>precSU</td>
<td>Summer precipitation</td>
<td>mm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>precAU</td>
<td>Autumn precipitation</td>
<td>mm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>precWI</td>
<td>Winter precipitation</td>
<td>mm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>precSP</td>
<td>Spring precipitation</td>
<td>mm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>tmaxSU</td>
<td>Summer mean maximum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>tmaxAU</td>
<td>Autumn mean maximum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>tmaxWI</td>
<td>Winter mean maximum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>tmaxSP</td>
<td>Spring mean maximum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>tminSU</td>
<td>Summer mean minimum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>tminAU</td>
<td>Autumn mean minimum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>tminWI</td>
<td>Winter mean minimum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>tminSP</td>
<td>Spring mean minimum temperature</td>
<td>º C</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>hline multirow{16}{*}{Topography}</td>
<td>elev</td>
<td>Elevation</td>
<td>meter</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>aspect</td>
<td>Aspect</td>
<td>º</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>slope</td>
<td>Slope</td>
<td>º</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>tpNS</td>
<td>North-South gradient</td>
<td></td>
<td>tpEW</td>
<td>East-West gradient</td>
<td></td>
<td>radSU</td>
<td>Summer direct radiation</td>
<td>Whm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>radAU</td>
<td>Autumn direct radiation</td>
<td>Whm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>radWI</td>
<td>Winter direct radiation</td>
<td>Whm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>radSP</td>
<td>Spring direct radiation</td>
<td>Whm</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>radhSU</td>
<td>Mean duration of insolation in Summer</td>
<td>hour</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>radhAU</td>
<td>Mean duration of insolation in Autumn</td>
<td>hour</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>radhWI</td>
<td>Mean duration of insolation in Winter</td>
<td>hour</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>radhSP</td>
<td>Mean duration of insolation in Spring</td>
<td>hour</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>twi</td>
<td>Topographic wetness index</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>tpos</td>
<td>Topographic position</td>
<td>meter</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>flow</td>
<td>Flow accumulation</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>hline Landscape</td>
<td>human</td>
<td>Anthropogenic influence</td>
<td>cells</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>hline multirow{9}{*}{Forest structure}</td>
<td>FCC</td>
<td>Forest canopy cover</td>
<td></td>
<td>FCCTree</td>
<td>Forest canopy cover of Tree</td>
<td></td>
<td>FCCShru</td>
<td>Forest canopy cover of Shrub</td>
<td></td>
<td>FCCHerb</td>
<td>Forest canopy cover of Herbaceous</td>
<td></td>
<td>CCshann</td>
<td>Canopy Cover diversity</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>heiTree</td>
<td>Tree Height</td>
<td>m</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>denTree</td>
<td>Density</td>
<td>trees <span class="math inline">\(ha^{-1}\)</span></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>BA</td>
<td>Basal area</td>
<td><span class="math inline">\(mathrm{m^2 cdot h^{-1}}\)</span></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>vol</td>
<td>Volume</td>
<td><span class="math inline">\(mathrm{m^3 cdot h^{-1}}\)</span></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>hline multirow{2}{*}{Forest biodiversity}</td>
<td>diver</td>
<td>Plant diversity</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>rich</td>
<td>Richness</td>
<td>species number</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>hline multirow{3}{*}{Forest function}</td>
<td>regTot</td>
<td>Total regeneration</td>
<td>total seedling number</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>regQp</td>
<td>Pyrenean Oak regeneration</td>
<td>seedling number</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>regQi</td>
<td>Holm Oak regeneration</td>
<td>seedling number</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-multivar-ForAtri" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="sec-multivar-ForAtri"><span class="header-section-number">4.2.3</span> Forest attributes</h3>
<p>To characterize oak patches, we selected several stand attributes relating to forest structure, function, and composition from Sierra Nevada Forest Inventory <span class="citation" data-cites="PerezLuqueetal2014SinfonevadaDataset">(<a href="#ref-PerezLuqueetal2014SinfonevadaDataset" role="doc-biblioref">Pérez-Luque et al. 2014</a>)</span> (Table&nbsp;<a href="#tab:multivar:tvars" data-reference-type="ref" data-reference="tab:multivar:tvars">[tab:multivar:tvars]</a>). By using this approach, we characterized the plant community both in terms of their species composition, and also regarding their ecological functioning <span class="citation" data-cites="McElhinnyetal2005ForestWoodland delRioetal2016CharacterizationStructure">(<a href="#ref-McElhinnyetal2005ForestWoodland" role="doc-biblioref">McElhinny et al. 2005</a>, <a href="#ref-delRioetal2016CharacterizationStructure" role="doc-biblioref">Río et al. 2016</a>)</span>. SINFONEVADA forest inventory was carried out during 2004-2005, and it includes an extensive network of plots distributed within the main forest units of Sierra Nevada mountain range. We selected 32 plots belonging to deciduous broadleaf forests category. All of them are located within the eight Pyrenean oak populations identified in Sierra Nevada. For each plot (20 x 20 m), all trees with diameter at breast height (dbh) &gt; 7.5 cm were tallied by species and dbh. Regeneration, species composition and abundance were also recorded in two additional subplots <span class="citation" data-cites="PerezLuqueetal2014SinfonevadaDataset">(<a href="#ref-PerezLuqueetal2014SinfonevadaDataset" role="doc-biblioref">Pérez-Luque et al. 2014</a>)</span>: a 5-m radius subplot where the seedling abundance of <em>Q. pyrenaica</em> was recorded; and a 10-m radius subplot where the species composition and abundance estimated by the Braun-Blanquet cover-abundance scale were measured <span class="citation" data-cites="BraunBlanquet1964PflanzensoziologieGrundzuge">(<a href="#ref-BraunBlanquet1964PflanzensoziologieGrundzuge" role="doc-biblioref">Braun-Blanquet 1964</a>)</span> (See Table&nbsp;<a href="#tab:multivar-s1" data-reference-type="ref" data-reference="tab:multivar-s1">[tab:multivar-s1]</a>).</p>
<p>Forest composition (richness) and plant diversity were used as indicator for overall forest biodiversity. Plant diversity was measured using the Shannon diversity index <span class="citation" data-cites="Krebs1999EcologicalMethodology">(<a href="#ref-Krebs1999EcologicalMethodology" role="doc-biblioref">Krebs 1999</a>)</span>. The total regeneration was used as proxy for forest functioning. Finally, as forest structure indicators we selected the following attributes: the total- and strata- (<em>i.e.</em> tree, shrub and herbaceous) canopy cover; canopy cover diversity; tree height, tree density, basal area and volume of adult tree. Canopy covers were computed as the proportion of plot area covered by the whole forest (total) and the different strata considered (tree, shrub and herbaceous respectively). Canopy cover diversity was quantified through the Shannon index for the proportion of plot area covered by different vegetation strata (tree, shrub and herbaceous) according with the following equation: <span class="math display">\[CCd'=\sum_{i=1}^{n} g_i \cdot \ln g_i\]</span> where <span class="math inline">\(g_i\)</span> is the proportion of strata <span class="math inline">\(i\)</span> of the total plot area and <span class="math inline">\(n\)</span> is the number of strata <span class="citation" data-cites="delRioetal2003IndicesStand">(<a href="#ref-delRioetal2003IndicesStand" role="doc-biblioref">Rio et al. 2003</a>)</span>. Basal area was calculated as the sum of the basal areas of the adult trees assuming a circular cross-section of the trunk. Volume was calculated as sum of volume (<span class="math inline">\(V = 0.55 \cdot \textrm{height} \cdot \textrm{diameter}^2\)</span>) of all <em>Q. pyrenaica</em> adult trees. Additionally, we also extracted the values of the environmental variables for the centroids of the plots and we added a species-composition matrix for each of the 32 selected plots.</p>
<div id="fig-multivar-schemamulti" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multivar-schemamulti-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/multivariante/schema.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multivar-schemamulti-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Methodological scheme of the analyses. Using an environmental data matrix, the main environmental gradients that characterize the oak forests at Sierra Nevada were identified using a Principal Component Analysis (PCA). Linear Discriminant Analysis (LDA) was also applied to identify different groups of oak populations. With a matrix of floristic composition, a Non-metric Multidimensional Scaling (NMDS) ordination were applied to visualize patterns of species composition, interpret them according to the environmental factors, and identify groups of oak populations based on similarities between floristic composition. See material and methods for more details.
</figcaption>
</figure>
</div>
</section>
<section id="sec-multivar-Analysis" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="sec-multivar-Analysis"><span class="header-section-number">4.2.4</span> Statistical analysis</h3>
<p>To identify the main environmental gradients that characterize the oak forests at Sierra Nevada, we performed a principal component analysis (PCA) on the standardized variables (Figure&nbsp;<a href="#fig:multivar:schemamulti" data-reference-type="ref" data-reference="fig:multivar:schemamulti">[fig:multivar:schemamulti]</a>). Over 75 &nbsp;</p>
<p>Then, environmental variables and forest attributes were tested for differences among populations groups previously identified. Normality and homoscedasticity were checked using the Shapiro-Wilk test and Levene’s test respectively. If normality and homoscedasticity assumptions were satisfied, we performed ANOVA analysis followed by the Tukey LSD for testing statistical significance. Otherwise, Kruskal-Wallis ANOVA for nonparametric data were conducted followed by manual pairwise comparison using Mann-Whitney U-test.</p>
<p>Finally we used a Non-metric Multidimensional Scaling (NMDS) ordination analysis based on Bray–Curtis dissimilarity distance <span class="citation" data-cites="Kruskal1964NonmetricMultidimensional">(<a href="#ref-Kruskal1964NonmetricMultidimensional" role="doc-biblioref">Kruskal 1964</a>)</span> to: (<em>i</em>) visualize patterns of species compositions, (<em>ii</em>) interpret them with respect to the environmental factors (<em>i.e.</em> relate the variability in species composition to environmental variables), and (<em>iii</em>) identify groups of Pyrenean oak populations based on similarities between floristic composition. NMDS involves the reduction of multidimensional similarity data to a low-dimensional ordination in which relative distance indicates relative similarity (<em>i.e.</em> plots with very similar species composition are close and <em>vice versa</em>) <span class="citation" data-cites="Minchin1987SimulationMultidimensional">(<a href="#ref-Minchin1987SimulationMultidimensional" role="doc-biblioref">Minchin 1987</a>)</span>. We compared two and three-dimensional solutions based on Kruskal’s stress (as a measure of goodness of fit). We also studied the floristic-environment relationships by fitting linear trends on the ordination yielded by the NMDS. For these linear fittings, squared correlation coefficients and empirical p-values were calculated using random permutations (n = 1000) of the data <span class="citation" data-cites="Oksanen2013MultivariateAnalysis">(<a href="#ref-Oksanen2013MultivariateAnalysis" role="doc-biblioref">Oksanen 2013</a>)</span>. Finally we fitted non-parametrically smoothed surfaces of continuous environmental variables on the NMDS ordination. The smooth surfaces were fitted using generalized additive models (GAM) with thin plate splines, using the coefficient of determination (<span class="math inline">\(R^2\)</span>) as goodness-of-fit statistic <span class="citation" data-cites="Oksanen2013MultivariateAnalysis Virtanenetal2006BroadScale">(<a href="#ref-Virtanenetal2006BroadScale" role="doc-biblioref">Virtanen et al. 2006</a>, <a href="#ref-Oksanen2013MultivariateAnalysis" role="doc-biblioref">Oksanen 2013</a>)</span>.</p>
<p>All analysis was conducted in R software <span class="citation" data-cites="base">(<a href="#ref-base" role="doc-biblioref">R Core Team 2020</a>)</span> using the following packages: MASS <span class="citation" data-cites="MASS">(<a href="#ref-MASS" role="doc-biblioref">Venables and Ripley 2002</a>)</span>, nFactors <span class="citation" data-cites="nFactors">(<a href="#ref-nFactors" role="doc-biblioref">Raiche and Magis 2020</a>)</span>, and vegan <span class="citation" data-cites="vegan">(<a href="#ref-vegan" role="doc-biblioref">Oksanen et al. 2019</a>)</span>. We also used the packages candisc <span class="citation" data-cites="candisc">(<a href="#ref-candisc" role="doc-biblioref">Friendly and Fox 2020</a>)</span>, ellipse <span class="citation" data-cites="ellipse">(<a href="#ref-ellipse" role="doc-biblioref">Murdoch and Chow 2020</a>)</span>, ggpubr <span class="citation" data-cites="ggpubr">(<a href="#ref-ggpubr" role="doc-biblioref">Kassambara 2020</a>)</span>, ggord <span class="citation" data-cites="ggord">(<a href="#ref-ggord" role="doc-biblioref">Beck 2020</a>)</span>, factoextra <span class="citation" data-cites="factoextra">(<a href="#ref-factoextra" role="doc-biblioref">Kassambara and Mundt 2020</a>)</span> and patchwork <span class="citation" data-cites="patchwork">(<a href="#ref-patchwork" role="doc-biblioref">Pedersen 2020</a>)</span> for visualization.</p>
</section>
</section>
<section id="sec-multivar-Results" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-multivar-Results"><span class="header-section-number">4.3</span> Results</h2>
<p>PCA of all measured environmental variables yielded three significant axes explained 62.11 &nbsp;</p>
<div id="tbl-multivar-tpca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multivar-tpca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.3: Results of the principal component and discriminant analysis. The three first axis for PCA and LDA are shown. Loadings and correlations of the environmental variables on principal component axis are reported. For LDA, canonical correlations of environmental variables with each discriminant function are shown.
</figcaption>
<div aria-describedby="tbl-multivar-tpca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>PC1 load</strong></th>
<th><strong>PC1 cor.</strong></th>
<th><strong>PC2 load</strong></th>
<th><strong>PC2 cor.</strong></th>
<th><strong>PC3 load</strong></th>
<th><strong>PC3 cor.</strong></th>
<th><strong>LDA 1</strong></th>
<th><strong>LDA 2</strong></th>
<th><strong>LDA 3</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>twi</td>
<td>-0.022</td>
<td>-0.069</td>
<td>-0.010</td>
<td>-0.024</td>
<td>0.023</td>
<td>0.046</td>
<td>-0.009</td>
<td>0.005</td>
<td>0.018</td>
</tr>
<tr class="even">
<td>flow</td>
<td>0.024</td>
<td>0.073</td>
<td>0.011</td>
<td>0.026</td>
<td>-0.008</td>
<td>-0.015</td>
<td>0.004</td>
<td>-0.003</td>
<td>0.005</td>
</tr>
<tr class="odd">
<td>elev</td>
<td>-0.158</td>
<td>-0.489</td>
<td>-0.016</td>
<td>-0.035</td>
<td>0.142</td>
<td>0.280</td>
<td>0.000</td>
<td>-0.014</td>
<td>0.105</td>
</tr>
<tr class="even">
<td>slope</td>
<td>0.222</td>
<td>0.690</td>
<td>-0.068</td>
<td>-0.155</td>
<td>0.157</td>
<td>0.309</td>
<td>0.032</td>
<td>0.034</td>
<td>-0.073</td>
</tr>
<tr class="odd">
<td>tpos</td>
<td>-0.163</td>
<td>-0.507</td>
<td>-0.019</td>
<td>-0.042</td>
<td>-0.043</td>
<td>-0.085</td>
<td>-0.021</td>
<td>-0.013</td>
<td>0.006</td>
</tr>
<tr class="even">
<td>aspect</td>
<td>-0.210</td>
<td>-0.650</td>
<td>-0.012</td>
<td>-0.026</td>
<td>-0.087</td>
<td>-0.172</td>
<td>-0.044</td>
<td>-0.043</td>
<td>0.075</td>
</tr>
<tr class="odd">
<td>tpEW</td>
<td>0.082</td>
<td>0.255</td>
<td>0.092</td>
<td>0.209</td>
<td>-0.017</td>
<td>-0.033</td>
<td>0.029</td>
<td>0.065</td>
<td>0.044</td>
</tr>
<tr class="even">
<td>tpNS</td>
<td>0.238</td>
<td>0.737</td>
<td>0.031</td>
<td>0.070</td>
<td>0.092</td>
<td>0.182</td>
<td>0.076</td>
<td>0.070</td>
<td>-0.070</td>
</tr>
<tr class="odd">
<td>radWI</td>
<td>-0.270</td>
<td>-0.836</td>
<td>-0.030</td>
<td>-0.067</td>
<td>-0.101</td>
<td>-0.198</td>
<td>-0.071</td>
<td>-0.076</td>
<td>0.081</td>
</tr>
<tr class="even">
<td>radSU</td>
<td>-0.276</td>
<td>-0.857</td>
<td>-0.023</td>
<td>-0.051</td>
<td>-0.119</td>
<td>-0.235</td>
<td>-0.067</td>
<td>-0.077</td>
<td>0.084</td>
</tr>
<tr class="odd">
<td>radSP</td>
<td>-0.287</td>
<td>-0.889</td>
<td>0.031</td>
<td>0.071</td>
<td>-0.152</td>
<td>-0.299</td>
<td>-0.045</td>
<td>-0.059</td>
<td>0.090</td>
</tr>
<tr class="even">
<td>radAU</td>
<td>-0.292</td>
<td>-0.906</td>
<td>0.005</td>
<td>0.011</td>
<td>-0.141</td>
<td>-0.279</td>
<td>-0.056</td>
<td>-0.069</td>
<td>0.090</td>
</tr>
<tr class="odd">
<td>radhWI</td>
<td>-0.286</td>
<td>-0.888</td>
<td>-0.014</td>
<td>-0.032</td>
<td>-0.127</td>
<td>-0.251</td>
<td>-0.073</td>
<td>-0.083</td>
<td>0.098</td>
</tr>
<tr class="even">
<td>radhSP</td>
<td>-0.283</td>
<td>-0.878</td>
<td>0.024</td>
<td>0.054</td>
<td>-0.150</td>
<td>-0.295</td>
<td>-0.051</td>
<td>-0.054</td>
<td>0.101</td>
</tr>
<tr class="odd">
<td>radhSU</td>
<td>-0.138</td>
<td>-0.428</td>
<td>0.111</td>
<td>0.252</td>
<td>-0.105</td>
<td>-0.207</td>
<td>-0.003</td>
<td>0.003</td>
<td>0.061</td>
</tr>
<tr class="even">
<td>radhAU</td>
<td>-0.190</td>
<td>-0.590</td>
<td>0.096</td>
<td>0.218</td>
<td>-0.112</td>
<td>-0.220</td>
<td>-0.018</td>
<td>-0.003</td>
<td>0.074</td>
</tr>
<tr class="odd">
<td>human</td>
<td>-0.143</td>
<td>-0.443</td>
<td>-0.069</td>
<td>-0.156</td>
<td>0.165</td>
<td>0.326</td>
<td>-0.067</td>
<td>0.013</td>
<td>0.107</td>
</tr>
<tr class="even">
<td>precWI</td>
<td>-0.191</td>
<td>-0.593</td>
<td>-0.178</td>
<td>-0.404</td>
<td>0.301</td>
<td>0.594</td>
<td>-0.081</td>
<td>0.024</td>
<td>-0.076</td>
</tr>
<tr class="odd">
<td>precSP</td>
<td>-0.178</td>
<td>-0.551</td>
<td>-0.068</td>
<td>-0.153</td>
<td>0.264</td>
<td>0.520</td>
<td>-0.044</td>
<td>0.087</td>
<td>0.074</td>
</tr>
<tr class="even">
<td>precSU</td>
<td>-0.226</td>
<td>-0.702</td>
<td>-0.084</td>
<td>-0.190</td>
<td>0.243</td>
<td>0.479</td>
<td>-0.073</td>
<td>0.069</td>
<td>0.092</td>
</tr>
<tr class="odd">
<td>precAU</td>
<td>-0.223</td>
<td>-0.692</td>
<td>-0.173</td>
<td>-0.391</td>
<td>0.225</td>
<td>0.444</td>
<td>-0.157</td>
<td>-0.043</td>
<td>-0.074</td>
</tr>
<tr class="even">
<td>precYE</td>
<td>-0.223</td>
<td>-0.692</td>
<td>-0.145</td>
<td>-0.329</td>
<td>0.274</td>
<td>0.539</td>
<td>-0.092</td>
<td>0.032</td>
<td>-0.001</td>
</tr>
<tr class="odd">
<td>tminWI</td>
<td>0.042</td>
<td>0.131</td>
<td>-0.342</td>
<td>-0.775</td>
<td>-0.267</td>
<td>-0.525</td>
<td>0.003</td>
<td>-0.001</td>
<td>-0.024</td>
</tr>
<tr class="even">
<td>tminSP</td>
<td>0.036</td>
<td>0.110</td>
<td>-0.293</td>
<td>-0.664</td>
<td>-0.311</td>
<td>-0.613</td>
<td>0.007</td>
<td>-0.008</td>
<td>0.001</td>
</tr>
<tr class="odd">
<td>tminSU</td>
<td>0.022</td>
<td>0.068</td>
<td>-0.189</td>
<td>-0.429</td>
<td>-0.357</td>
<td>-0.705</td>
<td>0.014</td>
<td>-0.011</td>
<td>0.045</td>
</tr>
<tr class="even">
<td>tminAU</td>
<td>0.035</td>
<td>0.109</td>
<td>-0.276</td>
<td>-0.625</td>
<td>-0.321</td>
<td>-0.633</td>
<td>0.009</td>
<td>-0.009</td>
<td>0.008</td>
</tr>
<tr class="odd">
<td>tmaxWI</td>
<td>0.051</td>
<td>0.159</td>
<td>-0.353</td>
<td>-0.800</td>
<td>0.133</td>
<td>0.262</td>
<td>-0.021</td>
<td>0.014</td>
<td>-0.176</td>
</tr>
<tr class="even">
<td>tmaxSP</td>
<td>0.063</td>
<td>0.196</td>
<td>-0.355</td>
<td>-0.804</td>
<td>0.091</td>
<td>0.180</td>
<td>-0.009</td>
<td>-0.014</td>
<td>-0.155</td>
</tr>
<tr class="odd">
<td>tmaxSU</td>
<td>0.056</td>
<td>0.175</td>
<td>-0.396</td>
<td>-0.897</td>
<td>0.015</td>
<td>0.030</td>
<td>-0.010</td>
<td>0.004</td>
<td>-0.120</td>
</tr>
<tr class="even">
<td>tmaxAU</td>
<td>0.054</td>
<td>0.166</td>
<td>-0.372</td>
<td>-0.843</td>
<td>0.100</td>
<td>0.196</td>
<td>-0.018</td>
<td>0.011</td>
<td>-0.160</td>
</tr>
<tr class="odd">
<td>Eigenvalue</td>
<td>9.618</td>
<td></td>
<td>5.130</td>
<td></td>
<td>3.886</td>
<td></td>
<td>150.351</td>
<td>67.162</td>
<td>19.108</td>
</tr>
<tr class="even">
<td>Variance</td>
<td>32.061</td>
<td></td>
<td>17.100</td>
<td></td>
<td>12.953</td>
<td></td>
<td>61.780</td>
<td>27.597</td>
<td>7.851</td>
</tr>
<tr class="odd">
<td>Cumulated variance</td>
<td>32.061</td>
<td></td>
<td>49.161</td>
<td></td>
<td>62.114</td>
<td></td>
<td>61.780</td>
<td>89.378</td>
<td>97.229</td>
</tr>
<tr class="even">
<td>Canonical correlation</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>0.997</td>
<td>0.993</td>
<td>0.975</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-figure-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figure-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/multivariante/lda_biplotsv2.jpg" id="fig-figure-6" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-figure-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3
</figcaption>
</figure>
</div>
<p>The discriminant analysis yielded three significant functions explaining 97.9 &nbsp;</p>
<p>The three oak clusters showed significantly differences for most of the environmental variables analyzed (Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a>). Only winter minimum temperatures (<span class="math inline">\(\chi^2\)</span> = 5.35; p-value = 0.069) and insolation time during summer (<span class="math inline">\(\chi^2\)</span> = 0.306; p-value = 0.306)) was similar among the three oak clusters (Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a>). <em>Post-hoc</em> analysis showed that for most of the environmental variables we found pairwise significant differences between all the three oak clusters (Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a>).</p>
<p>Forest attributes did not significantly differ among the above described oak clusters except for plant diversity and herbaceous canopy cover (Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a>). The N cluster showed higher value of Shannon diversity index (2.27 ± 0.17) than NW cluster (<em>Mann-Whitney U</em> = 22.0; p-value &lt;0.01). For stand attributes relating to forest structure only the herbaceous canopy cover showed significantly differences (<span class="math inline">\(\chi^2\)</span> = 11.18; p-value = 0.004; Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a>) between N and NW clusters (<em>Mann-Whitney U</em> = 15.0; p-value &lt; 0.01). For all other forest structure attributes, despite there are no significant differences, the N cluster showed the lowest values (Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a>). No significant differences were recorded for regeneration variables.</p>
<div id="tbl-multivar-tanovas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multivar-tanovas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.4: Mean values of environmental variables and forest attributes for the three identified clusters of <em>Q. pyrenaica</em> forests derivated from the discriminant anaylisis. The Chi-squared statistics of the nonparametric Kruskal-Wallis test is shown except for those variables analyzed using ANOVA test (<em>fccShru</em>, <em>fccTree</em> and <em>rich</em>). Values within brackets correspond to standard errors. Standard erros are shown in parentheses. Different letters indicate statistically significant differences between clusters oak populations.
</figcaption>
<div aria-describedby="tbl-multivar-tanovas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><strong>variable</strong></th>
<th><strong>statistic</strong></th>
<th><strong>p.value</strong></th>
<th><strong>d.f.</strong></th>
<th><strong>groupA (N)</strong></th>
<th><strong>groupB (NW)</strong></th>
<th><strong>groupC (S)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BA</td>
<td>4.43</td>
<td>0.109</td>
<td>2</td>
<td>0.71 (0.47) a</td>
<td>7.11 (2.00) ab</td>
<td>7.71 (2.78) b</td>
</tr>
<tr class="even">
<td>denTree</td>
<td>3.17</td>
<td>0.204</td>
<td>2</td>
<td>61.57 (31.95) a</td>
<td>226.97 (65.10) a</td>
<td>282.47 (86.03) a</td>
</tr>
<tr class="odd">
<td>fccHerb</td>
<td>11.18</td>
<td>0.004</td>
<td>2</td>
<td>6.50 (0.60) a</td>
<td>2.83 (0.51) b</td>
<td>4.33 (1.12) ab</td>
</tr>
<tr class="even">
<td>fcc</td>
<td>4.45</td>
<td>0.108</td>
<td>2</td>
<td>7.50 (0.57) a</td>
<td>8.50 (0.54) a</td>
<td>8.67 (0.99) a</td>
</tr>
<tr class="odd">
<td>heiTree</td>
<td>1.15</td>
<td>0.563</td>
<td>2</td>
<td>4.19 (1.67) a</td>
<td>6.96 (1.83) a</td>
<td>7.45 (1.76) a</td>
</tr>
<tr class="even">
<td>CCShann</td>
<td>2.09</td>
<td>0.352</td>
<td>2</td>
<td>0.85 (0.06) a</td>
<td>0.92 (0.04) a</td>
<td>0.93 (0.04) a</td>
</tr>
<tr class="odd">
<td>vol</td>
<td>3.63</td>
<td>0.163</td>
<td>2</td>
<td>7.50 (4.92) a</td>
<td>90.05 (29.24) a</td>
<td>76.66 (34.22) a</td>
</tr>
<tr class="even">
<td>fccShru</td>
<td>1.96</td>
<td>0.159</td>
<td>2,29</td>
<td>2.75 (0.86) a</td>
<td>4.50 (0.51) a</td>
<td>5.33 (1.54) a</td>
</tr>
<tr class="odd">
<td>fccTree</td>
<td>1.41</td>
<td>0.261</td>
<td>2,29</td>
<td>1.75 (0.62) a</td>
<td>3.33 (0.58) a</td>
<td>2.67 (0.80) a</td>
</tr>
<tr class="even">
<td>regTot</td>
<td>0.18</td>
<td>0.913</td>
<td>2</td>
<td>19.38 (6.25) a</td>
<td>47.56 (16.16) a</td>
<td>32.67 (15.82) a</td>
</tr>
<tr class="odd">
<td>regQi</td>
<td>3.89</td>
<td>0.143</td>
<td>2</td>
<td>5.75 (3.40) a</td>
<td>0.17 (0.09) a</td>
<td>3.50 (2.08) a</td>
</tr>
<tr class="even">
<td>regQp</td>
<td>0.39</td>
<td>0.823</td>
<td>2</td>
<td>7.62 (3.21) a</td>
<td>46.39 (16.16) a</td>
<td>29.17 (16.30) a</td>
</tr>
<tr class="odd">
<td>diver</td>
<td>8.67</td>
<td>0.013</td>
<td>2</td>
<td>2.27 (0.17) a</td>
<td>1.57 (0.13) b</td>
<td>1.83 (0.09) ab</td>
</tr>
<tr class="even">
<td>rich</td>
<td>2.95</td>
<td>0.068</td>
<td>2,29</td>
<td>16.62 (1.95) a</td>
<td>11.72 (1.21) a</td>
<td>14.17 (0.70) a</td>
</tr>
<tr class="odd">
<td>flow</td>
<td>66.22</td>
<td>0.000</td>
<td>2</td>
<td>345.35 (97.91) a</td>
<td>175.73 (32.95) b</td>
<td>169.57 (21.93) c</td>
</tr>
<tr class="even">
<td>twi</td>
<td>60.74</td>
<td>0.000</td>
<td>2</td>
<td>4.90 (0.08) a</td>
<td>5.08 (0.05) b</td>
<td>5.40 (0.05) c</td>
</tr>
<tr class="odd">
<td>elev</td>
<td>32.38</td>
<td>0.000</td>
<td>2</td>
<td>1740.05 (6.52) a</td>
<td>1669.84 (6.22) b</td>
<td>1710.33 (4.20) c</td>
</tr>
<tr class="even">
<td>tpEW</td>
<td>442.28</td>
<td>0.000</td>
<td>2</td>
<td>40.37 (1.47) a</td>
<td>54.36 (0.84) b</td>
<td>28.34 (0.58) c</td>
</tr>
<tr class="odd">
<td>tpos</td>
<td>201.90</td>
<td>0.000</td>
<td>2</td>
<td>-22.52 (1.73) a</td>
<td>-22.46 (1.64) a</td>
<td>-1.25 (0.75) b</td>
</tr>
<tr class="even">
<td>aspect</td>
<td>656.80</td>
<td>0.000</td>
<td>2</td>
<td>160.25 (5.50) a</td>
<td>113.33 (2.33) b</td>
<td>262.06 (3.14) c</td>
</tr>
<tr class="odd">
<td>slope</td>
<td>568.14</td>
<td>0.000</td>
<td>2</td>
<td>26.10 (0.33) a</td>
<td>29.93 (0.28) b</td>
<td>20.32 (0.25) c</td>
</tr>
<tr class="even">
<td>radWI</td>
<td>1301.22</td>
<td>0.000</td>
<td>2</td>
<td>1489.98 (50.78) a</td>
<td>770.18 (31.99) b</td>
<td>3013.85 (25.28) c</td>
</tr>
<tr class="odd">
<td>radAU</td>
<td>1238.90</td>
<td>0.000</td>
<td>2</td>
<td>5854.49 (40.75) a</td>
<td>5205.08 (30.85) b</td>
<td>6808.90 (17.59) c</td>
</tr>
<tr class="even">
<td>radSU</td>
<td>1242.79</td>
<td>0.000</td>
<td>2</td>
<td>3056.60 (59.95) a</td>
<td>2140.28 (41.68) b</td>
<td>4619.39 (26.39) c</td>
</tr>
<tr class="odd">
<td>radSP</td>
<td>1064.83</td>
<td>0.000</td>
<td>2</td>
<td>6835.85 (29.69) a</td>
<td>6352.91 (25.49) b</td>
<td>7419.43 (14.46) c</td>
</tr>
<tr class="even">
<td>radhWI</td>
<td>1565.28</td>
<td>0.000</td>
<td>2</td>
<td>4.77 (0.10) a</td>
<td>2.98 (0.08) b</td>
<td>8.10 (0.05) c</td>
</tr>
<tr class="odd">
<td>radhAU</td>
<td>125.57</td>
<td>0.000</td>
<td>2</td>
<td>10.44 (0.05) a</td>
<td>10.37 (0.04) a</td>
<td>11.01 (0.03) b</td>
</tr>
<tr class="even">
<td>radhSP</td>
<td>1117.91</td>
<td>0.000</td>
<td>2</td>
<td>7.42 (0.06) a</td>
<td>6.47 (0.06) b</td>
<td>9.13 (0.04) c</td>
</tr>
<tr class="odd">
<td>radhSU</td>
<td>2.36</td>
<td>0.307</td>
<td>2</td>
<td>11.49 (0.05) a</td>
<td>11.37 (0.04) a</td>
<td>11.58 (0.03) a</td>
</tr>
<tr class="even">
<td>tpNS</td>
<td>1363.86</td>
<td>0.000</td>
<td>2</td>
<td>62.33 (0.93) a</td>
<td>73.73 (0.66) b</td>
<td>27.76 (0.54) c</td>
</tr>
<tr class="odd">
<td>dist</td>
<td>2094.16</td>
<td>0.000</td>
<td>2</td>
<td>47.10 (0.04) a</td>
<td>39.52 (0.11) b</td>
<td>25.26 (0.04) c</td>
</tr>
<tr class="even">
<td>human</td>
<td>983.67</td>
<td>0.000</td>
<td>2</td>
<td>0.00 (0.00) a</td>
<td>6.95 (0.38) b</td>
<td>19.53 (0.45) c</td>
</tr>
<tr class="odd">
<td>precYE</td>
<td>1143.00</td>
<td>0.000</td>
<td>2</td>
<td>690.32 (1.66) a</td>
<td>741.43 (1.10) b</td>
<td>778.13 (0.95) c</td>
</tr>
<tr class="even">
<td>precWI</td>
<td>926.56</td>
<td>0.000</td>
<td>2</td>
<td>233.38 (0.43) a</td>
<td>246.53 (0.27) b</td>
<td>253.85 (0.28) c</td>
</tr>
<tr class="odd">
<td>precAU</td>
<td>1703.96</td>
<td>0.000</td>
<td>2</td>
<td>253.82 (0.45) a</td>
<td>267.02 (0.29) b</td>
<td>290.49 (0.35) c</td>
</tr>
<tr class="even">
<td>precSP</td>
<td>576.54</td>
<td>0.000</td>
<td>2</td>
<td>135.36 (0.39) a</td>
<td>148.30 (0.32) b</td>
<td>148.28 (0.21) c</td>
</tr>
<tr class="odd">
<td>precSU</td>
<td>847.35</td>
<td>0.000</td>
<td>2</td>
<td>67.76 (0.39) a</td>
<td>79.57 (0.32) b</td>
<td>85.51 (0.20) c</td>
</tr>
<tr class="even">
<td>tmaxWI</td>
<td>184.76</td>
<td>0.000</td>
<td>2</td>
<td>8.22 (0.05) a</td>
<td>9.40 (0.05) b</td>
<td>9.16 (0.04) c</td>
</tr>
<tr class="odd">
<td>tmaxAU</td>
<td>170.76</td>
<td>0.000</td>
<td>2</td>
<td>16.22 (0.05) a</td>
<td>17.19 (0.05) b</td>
<td>16.97 (0.04) c</td>
</tr>
<tr class="even">
<td>tmaxSP</td>
<td>46.60</td>
<td>0.000</td>
<td>2</td>
<td>13.95 (0.04) a</td>
<td>14.35 (0.04) b</td>
<td>14.21 (0.03) c</td>
</tr>
<tr class="odd">
<td>tmaxSU</td>
<td>87.50</td>
<td>0.000</td>
<td>2</td>
<td>24.93 (0.04) a</td>
<td>25.46 (0.04) b</td>
<td>25.29 (0.03) c</td>
</tr>
<tr class="even">
<td>tminWI</td>
<td>5.35</td>
<td>0.069</td>
<td>2</td>
<td>0.45 (0.04) a</td>
<td>0.42 (0.02) a</td>
<td>0.37 (0.02) a</td>
</tr>
<tr class="odd">
<td>tminAU</td>
<td>28.56</td>
<td>0.000</td>
<td>2</td>
<td>7.15 (0.04) a</td>
<td>6.93 (0.02) b</td>
<td>6.89 (0.02) b</td>
</tr>
<tr class="even">
<td>tminSP</td>
<td>18.45</td>
<td>0.000</td>
<td>2</td>
<td>4.55 (0.04) a</td>
<td>4.37 (0.02) b</td>
<td>4.35 (0.02) b</td>
</tr>
<tr class="odd">
<td>tminSU</td>
<td>80.11</td>
<td>0.000</td>
<td>2</td>
<td>13.13 (0.04) a</td>
<td>12.68 (0.03) b</td>
<td>12.68 (0.03) b</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A three-dimensional solution of the NMDS was chosen because its correlation with the original data was higher than for a two-dimensional solution (Linear fit <span class="math inline">\(R^2\)</span>=0.793 <em>vs.</em> 0.713). Additionally, lower Kruskal’s stress value was observed for the three-dimensional solution (Stress=0.159 <em>vs.</em> 0.226). The NMDS ordination of the forest stands according to their floristic composition was significantly correlated with precipitation variables, elevation and marginally with winter maximum temperatures (Figure&nbsp;<a href="#fig:multivar:nmds" data-reference-type="ref" data-reference="fig:multivar:nmds">[fig:multivar:nmds]</a>; Table&nbsp;<a href="#tab:multivar:nmds" data-reference-type="ref" data-reference="tab:multivar:nmds">[tab:multivar:nmds]</a>). The precipitation variables showed highly and negative correlations with NMDS axis 2 (Table&nbsp;<a href="#tab:multivar:nmds" data-reference-type="ref" data-reference="tab:multivar:nmds">[tab:multivar:nmds]</a>). The NMDS axis 1 were negatively correlated with elevation (<span class="math inline">\(R^2\)</span> = 0.464) and minimum temperatures, and positively correlated with slope and winter maximum temperatures (Table <a href="#tab:multivar:nmds" data-reference-type="ref" data-reference="tab:multivar:nmds">[tab:multivar:nmds]</a>). The NMDS ordinations with fitted vectors and surfaces for significant variables are shown in Figure&nbsp;<a href="#fig:multivar:surfaces" data-reference-type="ref" data-reference="fig:multivar:surfaces">[fig:multivar:surfaces]</a>. All these variables showed a non-linear significant relationship with the ordination pattern (<span class="math inline">\(R^2\)</span> values for surfaces were slightly higher than linear <span class="math inline">\(R^2\)</span> values; Table&nbsp;<a href="#tab:multivar:nmds" data-reference-type="ref" data-reference="tab:multivar:nmds">[tab:multivar:nmds]</a>).</p>
<div id="fig-multivar-nmds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multivar-nmds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/multivariante/nmds.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multivar-nmds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: NMDS ordination of the plots. Points represent plot sites displayed according to their similarity in species composition. Proximity in the statistical space indicates plot sites with a similar species composition. Arrows represent vectors of significantly environmental variables explaining the ordination (see Table~ref{tab:multivar:nmds}). Each plot coloured according to the three oak-populations clusters derived from discriminant analysis. Only two dimensions of the NMDS is illustrated for ease of representation.
</figcaption>
</figure>
</div>
</section>
<section id="sec-multivar-Discussion" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-multivar-Discussion"><span class="header-section-number">4.4</span> Discussion</h2>
<section id="sec-multivar-EcolDiversity" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="sec-multivar-EcolDiversity"><span class="header-section-number">4.4.1</span> Ecological diversity within the rear-edge</h3>
<p>The rear-edge populations of <em>Quercus pyrenaica</em> located in mountain areas are not ecologically homogeneous, neither for their environmental conditions nor for their plant species composition. In this study, we find separate groups of <em>Q. pyrenaica</em> populations within Sierra Nevada (rear-edge) driven by radiation and rainfall as main discriminant variables (Figure&nbsp;<a href="#fig:multivar:lda" data-reference-type="ref" data-reference="fig:multivar:lda">[fig:multivar:lda]</a>). The differences among populations based on environmental variables, are in line with differential ecological dynamics reported for <em>Q. pyrenaica</em> forests in the Sierra Nevada by other studies. For instance, primary productivity of these forest measured using remote sensing showed a heterogeneous spatial behavior, with oak woodlands of the southern slopes displaying a greater annual vegetation greenness than those from the northern slopes <span class="citation" data-cites="Dionisioetal2012SatelliteBasedMonitoring PerezLuqueetal2015OntologicalSystem PerezLuqueetal2020LanduseLegacies">(<a href="#ref-Dionisioetal2012SatelliteBasedMonitoring" role="doc-biblioref">Dionisio et al. 2012</a>, <a href="#ref-PerezLuqueetal2015OntologicalSystem" role="doc-biblioref">Pérez-Luque et al. 2015</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>. Also, differences have been found in both seasonal dynamics of greenness <span class="citation" data-cites="Dionisioetal2012SatelliteBasedMonitoring">(<a href="#ref-Dionisioetal2012SatelliteBasedMonitoring" role="doc-biblioref">Dionisio et al. 2012</a>)</span>, and in temporal trends for primary productivity in the last years related with differential snow-cover trends in contrasting slopes <span class="citation" data-cites="PerezLuqueetal2015OntologicalSystem AlcarazSeguraetal2016ChangesVegetation">(<a href="#ref-PerezLuqueetal2015OntologicalSystem" role="doc-biblioref">Pérez-Luque et al. 2015</a>, <a href="#ref-AlcarazSeguraetal2016ChangesVegetation" role="doc-biblioref">Alcaraz-Segura et al. 2016</a>)</span>.</p>
<div id="fig-multivar-surfaces" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multivar-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/multivariante/surfaces.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multivar-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.5: NMDS ordination with fitted environmental vectors and regression surfaces. Length and direction of the arrows indicate the strength and sign of the linear correlation of environmental variable with ordination scores. The surfaces show smooth trends of the relationship between environmental variables and plot scores.
</figcaption>
</figure>
</div>
<div id="tbl-multivar-nmds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multivar-nmds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.5: Results of the NMDS. Maximum linear correlations (<span class="math inline">\(R^2\)</span>) of the environmental variables (vector) with the NMDS ordination patterns are shown. Significance of the correlations was calculated using 1000 permutations. Non-linear surface responses using GAM are also shown
</figcaption>
<div aria-describedby="tbl-multivar-nmds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>** **</th>
<th><strong>Vector</strong></th>
<th><strong>Response Surface</strong></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variable</td>
<td>Vector <span class="math inline">\(R^2\)</span></td>
<td>Vector p-value</td>
<td>F</td>
<td>Response Surface <span class="math inline">\(R^2\)</span></td>
<td>p-value</td>
</tr>
<tr class="even">
<td>precWI</td>
<td>0.583</td>
<td>0.001</td>
<td>4.89</td>
<td>0.587</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>precSP</td>
<td>0.509</td>
<td>0.001</td>
<td>6.23</td>
<td>0.644</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>precSU</td>
<td>0.584</td>
<td>0.001</td>
<td>7.76</td>
<td>0.693</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>precAU</td>
<td>0.526</td>
<td>0.001</td>
<td>2.93</td>
<td>0.460</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>precYE</td>
<td>0.613</td>
<td>0.001</td>
<td>6.14</td>
<td>0.640</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>tminWI</td>
<td>0.071</td>
<td>0.547</td>
<td>0.73</td>
<td>0.175</td>
<td>0.106</td>
</tr>
<tr class="even">
<td>tminSP</td>
<td>0.091</td>
<td>0.436</td>
<td>0.63</td>
<td>0.155</td>
<td>0.121</td>
</tr>
<tr class="odd">
<td>tminSU</td>
<td>0.138</td>
<td>0.223</td>
<td>0.51</td>
<td>0.130</td>
<td>0.140</td>
</tr>
<tr class="even">
<td>tminAU</td>
<td>0.101</td>
<td>0.384</td>
<td>0.54</td>
<td>0.137</td>
<td>0.144</td>
</tr>
<tr class="odd">
<td>tmaxWI</td>
<td>0.234</td>
<td>0.047</td>
<td>3.21</td>
<td>0.483</td>
<td>0.001</td>
</tr>
<tr class="even">
<td>tmaxSP</td>
<td>0.112</td>
<td>0.363</td>
<td>0.87</td>
<td>0.202</td>
<td>0.069</td>
</tr>
<tr class="odd">
<td>tmaxSU</td>
<td>0.206</td>
<td>0.081</td>
<td>1.78</td>
<td>0.341</td>
<td>0.014</td>
</tr>
<tr class="even">
<td>tmaxAU</td>
<td>0.225</td>
<td>0.057</td>
<td>2.97</td>
<td>0.463</td>
<td>0.002</td>
</tr>
<tr class="odd">
<td>human</td>
<td>0.127</td>
<td>0.277</td>
<td>0.14</td>
<td>0.040</td>
<td>0.319</td>
</tr>
<tr class="even">
<td>twi</td>
<td>0.057</td>
<td>0.649</td>
<td>0.52</td>
<td>0.131</td>
<td>0.133</td>
</tr>
<tr class="odd">
<td>flow</td>
<td>0.032</td>
<td>0.830</td>
<td>0.00</td>
<td>0.000</td>
<td>0.604</td>
</tr>
<tr class="even">
<td>elev</td>
<td>0.464</td>
<td>0.002</td>
<td>5.12</td>
<td>0.598</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>slope</td>
<td>0.053</td>
<td>0.631</td>
<td>0.14</td>
<td>0.040</td>
<td>0.293</td>
</tr>
<tr class="even">
<td>tpos</td>
<td>0.131</td>
<td>0.261</td>
<td>0.27</td>
<td>0.072</td>
<td>0.232</td>
</tr>
<tr class="odd">
<td>aspect</td>
<td>0.050</td>
<td>0.696</td>
<td>0.00</td>
<td>0.000</td>
<td>0.646</td>
</tr>
<tr class="even">
<td>tpEW</td>
<td>0.050</td>
<td>0.698</td>
<td>0.34</td>
<td>0.090</td>
<td>0.217</td>
</tr>
<tr class="odd">
<td>tpNS</td>
<td>0.008</td>
<td>0.970</td>
<td>0.31</td>
<td>0.081</td>
<td>0.211</td>
</tr>
<tr class="even">
<td>radWI</td>
<td>0.021</td>
<td>0.899</td>
<td>0.12</td>
<td>0.034</td>
<td>0.326</td>
</tr>
<tr class="odd">
<td>radSU</td>
<td>0.017</td>
<td>0.918</td>
<td>0.00</td>
<td>0.000</td>
<td>0.841</td>
</tr>
<tr class="even">
<td>radSP</td>
<td>0.024</td>
<td>0.864</td>
<td>0.00</td>
<td>0.000</td>
<td>0.580</td>
</tr>
<tr class="odd">
<td>radAU</td>
<td>0.014</td>
<td>0.937</td>
<td>0.00</td>
<td>0.000</td>
<td>0.660</td>
</tr>
<tr class="even">
<td>radhWI</td>
<td>0.028</td>
<td>0.837</td>
<td>0.05</td>
<td>0.014</td>
<td>0.384</td>
</tr>
<tr class="odd">
<td>radhSP</td>
<td>0.038</td>
<td>0.782</td>
<td>0.00</td>
<td>0.000</td>
<td>0.613</td>
</tr>
<tr class="even">
<td>radhSU</td>
<td>0.139</td>
<td>0.190</td>
<td>0.01</td>
<td>0.004</td>
<td>0.421</td>
</tr>
<tr class="odd">
<td>radhAU</td>
<td>0.115</td>
<td>0.280</td>
<td>0.19</td>
<td>0.052</td>
<td>0.274</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Interestingly, our results also showed differences in species diversity among population groups derived from clustering based on environmental variables. These results are consistent with those provided by <span class="citation" data-cites="Loriteetal2008PhytosociologicalReview">Lorite et al. (<a href="#ref-Loriteetal2008PhytosociologicalReview" role="doc-biblioref">2008</a>)</span>, who pointed out that differences observed for the floristic component in the <em>Q. pyrenaica</em> populations of Sierra Nevada are related to the microclimatic conditions. Thus, the oak woodlands located in the northern of Sierra Nevada showed greater floristic similarity with those located at the center of the <em>Q. pyrenaica</em> distribution than those located at southern slopes of Sierra Nevada (geographically closer) <span class="citation" data-cites="Loriteetal2008PhytosociologicalReview">(<a href="#ref-Loriteetal2008PhytosociologicalReview" role="doc-biblioref">Lorite et al. 2008</a>)</span>. The floristic differences between Sierra Nevada oak populations could also be related to the anthropogenic impact suffered by those populations, since the anthropic disturbances can affect the floristic patterns of the woodlands of this species, as it has been documented for oak woodlands in central Spain <span class="citation" data-cites="Gavilanetal2000EffectsDisturbance">(<a href="#ref-Gavilanetal2000EffectsDisturbance" role="doc-biblioref">Gavilán et al. 2000</a>)</span>. Thus, the CAM oak population (N-cluster) showed both the highest plant species diversity and richness (Table&nbsp;<a href="#tab:multivar:tanovas" data-reference-type="ref" data-reference="tab:multivar:tanovas">[tab:multivar:tanovas]</a> and Supplementary), which may be related to a better conservation status, as this populations has been less exposed to intense anthropogenic activity <span class="citation" data-cites="JimenezOlivencia1991PaisajesSierra">(<a href="#ref-JimenezOlivencia1991PaisajesSierra" role="doc-biblioref">Jiménez Olivencia 1991</a>)</span>. Conversely, the southern oak populations (CAN, POQ and TRE) showed a poorer floristic composition conditioned by both climate and intense land use <span class="citation" data-cites="CamachoOlmedoetal2002DinamicaEvolutiva AlAallalietal1998EstudioVegetacion">(<a href="#ref-AlAallalietal1998EstudioVegetacion" role="doc-biblioref">Al Aallali et al. 1998</a>, <a href="#ref-CamachoOlmedoetal2002DinamicaEvolutiva" role="doc-biblioref">Camacho-Olmedo et al. 2002</a>)</span>.</p>
<p>We found a remarkable match between the population’s clustering derived from analysis of environmental variables (Figure&nbsp;<a href="#fig:multivar:lda" data-reference-type="ref" data-reference="fig:multivar:lda">[fig:multivar:lda]</a>) and the ordination of the populations according to species composition (Figure&nbsp;<a href="#fig:multivar:nmds" data-reference-type="ref" data-reference="fig:multivar:nmds">[fig:multivar:nmds]</a> and Figure&nbsp;<a href="#fig:multivar:surfaces" data-reference-type="ref" data-reference="fig:multivar:surfaces">[fig:multivar:surfaces]</a>). These findings suggest a linkage between the heterogeneity of environmental factors and the variability of species composition for these woodlands. The diversity of ecological conditions for <em>Q. pyrenaica</em> populations in this rear edge are in line with the high levels of genetic diversity shown by populations of this oak in the Sierra Nevada <span class="citation" data-cites="ValbuenaCarabanaGil2013GeneticResilience ValbuenaCarabanaGil2017CentenaryCoppicing">(<a href="#ref-ValbuenaCarabanaGil2013GeneticResilience" role="doc-biblioref">Valbuena-Carabaña and Gil 2013</a>, <a href="#ref-ValbuenaCarabanaGil2017CentenaryCoppicing" role="doc-biblioref">2017</a>)</span>. The climatic and topographical heterogeneity that exists in the Sierra Nevada offers a great diversity of microhabitats, which has allowed this mountain range to act as a refuge for different species <span class="citation" data-cites="MedailDiadema2009GlacialRefugia GomezLunt2007RefugiaRefugia BlancoPastoretal2019TopographyExplains">(<a href="#ref-GomezLunt2007RefugiaRefugia" role="doc-biblioref">Gómez and Lunt 2007</a>, <a href="#ref-MedailDiadema2009GlacialRefugia" role="doc-biblioref">Médail and Diadema 2009</a>, <a href="#ref-BlancoPastoretal2019TopographyExplains" role="doc-biblioref">Blanco-Pastor et al. 2019</a>)</span>, including for deciduous <em>Quercus</em> species during the last glacial period <span class="citation" data-cites="Breweretal2002SpreadDeciduous Olaldeetal2002WhiteOaks RodriguezSanchezetal2010TreeRange">(<a href="#ref-Breweretal2002SpreadDeciduous" role="doc-biblioref">Brewer et al. 2002</a>, <a href="#ref-Olaldeetal2002WhiteOaks" role="doc-biblioref">Olalde et al. 2002</a>, <a href="#ref-RodriguezSanchezetal2010TreeRange" role="doc-biblioref">Rodríguez-Sánchez et al. 2010</a>)</span>. In fact, there are fossil and genetic evidences for different <em>Quercus</em> species that strongly suggest they survived only in southerly refugia during the last glacial maximum <span class="citation" data-cites="Breweretal2002SpreadDeciduous Petitetal2002IdentificationRefugia BhagwatWillis2008SpeciesPersistence BirksWillis2008AlpinesTrees">(<a href="#ref-Breweretal2002SpreadDeciduous" role="doc-biblioref">Brewer et al. 2002</a>, <a href="#ref-Petitetal2002IdentificationRefugia" role="doc-biblioref">Petit et al. 2002</a>, <a href="#ref-BhagwatWillis2008SpeciesPersistence" role="doc-biblioref">Bhagwat and Willis 2008</a>, <a href="#ref-BirksWillis2008AlpinesTrees" role="doc-biblioref">Birks and Willis 2008</a>)</span>. The persistence in a refugium suggests a combination of a moderately suitable local environment buffering against the regional climate, and a relative tolerance to climate change, by either pronounced phenotypic plasticity, and/or adaptive capacity <span class="citation" data-cites="Gavinetal2014ClimateRefugia">(<a href="#ref-Gavinetal2014ClimateRefugia" role="doc-biblioref">Gavin et al. 2014</a>)</span>. This could be very well the case of <em>Q. pyrenaica</em>, a species harboring a high genetic diversity <span class="citation" data-cites="ValbuenaCarabanaGil2013GeneticResilience">(<a href="#ref-ValbuenaCarabanaGil2013GeneticResilience" role="doc-biblioref">Valbuena-Carabaña and Gil 2013</a>)</span>, located in a mountain region with a complex topography that could protect local populations against rapid climate shifts and allow species to persist despite regionally unfavorable environments.</p>
</section>
<section id="sec-multivarSummerRainfall" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="sec-multivarSummerRainfall"><span class="header-section-number">4.4.2</span> The importance of summer rainfall at the micro-habitat level.</h3>
<p>The distribution of <em>Q. pyrenaica</em> is known to be conditioned by summer drought period with a minimum of 100-150 mm of summer rainfall <span class="citation" data-cites="BlancoCastroetal2005BosquesIbericos GarciaJimenez20099230Robledales">(<a href="#ref-BlancoCastroetal2005BosquesIbericos" role="doc-biblioref">Blanco Castro et al. 2005</a>, <a href="#ref-GarciaJimenez20099230Robledales" role="doc-biblioref">García and Jiménez 2009</a>)</span>. Bioclimatic analysis for this species revealed the importance of rainfall and ombrothermic indexes in the separation of temperate and Mediterranean forests <span class="citation" data-cites="delRioetal2007BioclimaticAnalysis">(<a href="#ref-delRioetal2007BioclimaticAnalysis" role="doc-biblioref">del Río et al. 2007</a>)</span>. At more detailed scale, the distribution for this oak is driven by a complex gradient related with temperature, rainfall and radiation <span class="citation" data-cites="Gavilanetal2007ModellingCurrent Urbietaetal2011MediterraneanPine">(<a href="#ref-Gavilanetal2007ModellingCurrent" role="doc-biblioref">Gavilán et al. 2007</a>, <a href="#ref-Urbietaetal2011MediterraneanPine" role="doc-biblioref">Urbieta et al. 2011</a>)</span>. Our study unveils a separation in the environmental space between oak populations at the rear-edge related with the spatial pattern of precipitation for this mountain region <span class="citation" data-cites="Pereiraetal2016SpatialInterpolation">(<a href="#ref-Pereiraetal2016SpatialInterpolation" role="doc-biblioref">Pereira et al. 2016</a>)</span>. Thus, summer and annual rainfall are among the most important factors in explaining the distribution of <em>Q. pyrenaica</em> forests in Sierra Nevada ( Table&nbsp;<a href="#tab:multivar:tpca" data-reference-type="ref" data-reference="tab:multivar:tpca">[tab:multivar:tpca]</a>). The northern and northwestern populations of <em>Q. pyrenaica</em> at Sierra Nevada are located in valley bottoms with and northern orientation, where the relative humidity is greater as result of a lower solar radiation. On the other hand, the populations of the southern slopes of Sierra Nevada get an extra supply of water from moist air from the neighboring Alborán sea <span class="citation" data-cites="MartinezParrasMoleroMesa1982EcologiaFitosociologia">(<a href="#ref-MartinezParrasMoleroMesa1982EcologiaFitosociologia" role="doc-biblioref">Martínez-Parras and Molero-Mesa 1982</a>)</span>. The differences in water availability among oak populations could affect several ecological processes such as tree-growth <span class="citation" data-cites="GeaIzquierdoCanellas2014LocalClimate PerezLuqueetal2020LanduseLegacies">(<a href="#ref-GeaIzquierdoCanellas2014LocalClimate" role="doc-biblioref">Gea-Izquierdo and Cañellas 2014</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>, seedling germination and survival <span class="citation" data-cites="Gomez2003ImpactVertebrate GomezAparicioetal2008OakSeedling Mendozaetal2009SeedingExperiment">(<a href="#ref-Gomez2003ImpactVertebrate" role="doc-biblioref">Gómez et al. 2003</a>, <a href="#ref-GomezAparicioetal2008OakSeedling" role="doc-biblioref">Gómez-Aparicio et al. 2008</a>, <a href="#ref-Mendozaetal2009SeedingExperiment" role="doc-biblioref">Mendoza et al. 2009</a>)</span>, and the regeneration of the species <span class="citation" data-cites="Gomezetal2001ProblemasRegeneracion">(<a href="#ref-Gomezetal2001ProblemasRegeneracion" role="doc-biblioref">Gómez et al. 2001</a>)</span>, mainly due to the key role of water availability in the microsites facilitating the germination and establishment of seedlings.</p>
</section>
<section id="sec-multivar-ImplicaForecast" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="sec-multivar-ImplicaForecast"><span class="header-section-number">4.4.3</span> Implications for forecasting and modelling.</h3>
<p>The factors controlling species distributions may vary depending on the scale of observation. At large scale areas, the distribution of a species is likely to be controlled by climatic regulators <span class="citation" data-cites="GuisanThuiller2005PredictingSpecies">(<a href="#ref-GuisanThuiller2005PredictingSpecies" role="doc-biblioref">Guisan and Thuiller 2005</a>)</span>, whereas at local scales factors related to biological interactions play a relevant role in shaping species distributions <span class="citation" data-cites="Urbietaetal2008SoilWater SanchezdeDiosetal2009PresentFuture">(<a href="#ref-Urbietaetal2008SoilWater" role="doc-biblioref">Urbieta et al. 2008</a>, <a href="#ref-SanchezdeDiosetal2009PresentFuture" role="doc-biblioref">Sánchez de Dios et al. 2009</a>)</span>. At the site level, we found that moisture availability is the environmental factor that better separates the studied oak populations into clearly differentiated clusters. The identification of different population groups based on environmental variables at fine-scale is important when modelling the distribution and forecasting the impact of global change on the species. Our results suggest that incorporating the local adaptations of individual populations into predictive models might help avoid misrepresenting the potential range shift of species under changing climate conditions <span class="citation" data-cites="BenitoGarzonetal2011IntraspecificVariability">(<a href="#ref-BenitoGarzonetal2011IntraspecificVariability" role="doc-biblioref">Benito-Garzón et al. 2011</a>)</span>. This is particularly important for species with rear-edges located in mountain ranges, since these areas provide a broad diversity of microhabitats due to climatic and topographical heterogeneity <span class="citation" data-cites="MedailDiadema2009GlacialRefugia">(<a href="#ref-MedailDiadema2009GlacialRefugia" role="doc-biblioref">Médail and Diadema 2009</a>)</span>. For instance, some recent works have performed out high-resolution models of the distribution of relict trees in Mediterranean southern mountains (<em>e.g</em>. <em>Abies pinsapo</em>, <em>Pinus sylvetris</em> and <em>P. nigra</em>) providing useful information for forest management actions <span class="citation" data-cites="LopezTiradoHidalgo2014HighResolution">(<a href="#ref-LopezTiradoHidalgo2014HighResolution" role="doc-biblioref">López-Tirado and Hidalgo 2014</a>)</span>.</p>
</section>
</section>
<section id="sec-multivar-Conclusion" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-multivar-Conclusion"><span class="header-section-number">4.5</span> Concluding remarks: biodiversity from the genetics to the landscape.</h2>
<p>We identified several groups of oak populations within the rear-edge of the <em>Q. pyrenaica</em> forest mainly due to microhabitats conditions. The different clusters of oak populations are supported both by discriminant analysis of environmental variables and by ordination analysis based on the floristic composition on the target populations. The diversity in the ecological conditions within these populations results from both to the environmental heterogeneity created by the slopes and the contrasting exposures of the valleys they inhabit, and the anthropic use of these ecosystems <span class="citation" data-cites="NavarroGonzalezetal2013WeightLanduse PerezLuqueetal2020LanduseLegacies">(<a href="#ref-NavarroGonzalezetal2013WeightLanduse" role="doc-biblioref">Navarro-González et al. 2013</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>. The confluence of these factors generates a multitude of environmental conditions on a fine scale, which are reflected in the distribution, composition and functioning of the <em>Quercus pyrenaica</em> forests. <em>Quercus pyrenaica</em> woodlands are highly diverse at all organization levels, from a genetic perspective, <em>i.e.</em> high levels of genetic differentiation within specie <span class="citation" data-cites="ValbuenaCarabanaGil2013GeneticResilience">(<a href="#ref-ValbuenaCarabanaGil2013GeneticResilience" role="doc-biblioref">Valbuena-Carabaña and Gil 2013</a>)</span> and differences between populations <span class="citation" data-cites="ValbuenaCarabanaGil2011EvaluacionEstructura">(<a href="#ref-ValbuenaCarabanaGil2011EvaluacionEstructura" role="doc-biblioref">Valbuena-Carabaña and Gil 2011</a>)</span>; to ecosystem-functioning level, <em>i.e.</em> diversity in terms of primary production and growth <span class="citation" data-cites="PerezLuqueetal2015OntologicalSystem AlcarazSeguraetal2016ChangesVegetation">(<a href="#ref-PerezLuqueetal2015OntologicalSystem" role="doc-biblioref">Pérez-Luque et al. 2015</a>, <a href="#ref-AlcarazSeguraetal2016ChangesVegetation" role="doc-biblioref">Alcaraz-Segura et al. 2016</a>)</span>, and diversity of resilience to disturbances <span class="citation" data-cites="PerezLuqueetal2020LanduseLegacies">(<a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>. Such ecological heterogeneity is also made evident by the accompanying plant communities, which are very different depending on the oak population considered, being such differences correlated with the differences in environmental conditions among populations.</p>
<p>Mountains such as Sierra Nevada, not only act an elevation gradients along which plant communities are distributed and replaced, in fact, they constitute an ecological mosaics in which others factors besides elevation, <em>e.g.</em> the exposure and the history of human management, create a broad range of responses from the oak woodlands and its very diverse associated vegetation, from genetics to landscape. Understanding the differences that exist between oak populations within the rear-edge with respect to environmental variables help us to plan both the forest management and restoration actions, especially taking into account the importance of some environmental factors in key ecological aspects <span class="citation" data-cites="GomezAparicioetal2008OakSeedling PerezLuqueetal2020LanduseLegacies">(<a href="#ref-GomezAparicioetal2008OakSeedling" role="doc-biblioref">Gómez-Aparicio et al. 2008</a>, <a href="#ref-PerezLuqueetal2020LanduseLegacies" role="doc-biblioref">Pérez-Luque et al. 2020</a>)</span>. Our results also shows the importance of the rear-edge mountain areas as a refuges for within-species diversity, and the role of species’ southern ranges as hotspots of within-species diversity <span class="citation" data-cites="Jumpetal2010MonitoringManaging HampeJump2011ClimateRelicts">(<a href="#ref-Jumpetal2010MonitoringManaging" role="doc-biblioref">Jump et al. 2010</a>, <a href="#ref-HampeJump2011ClimateRelicts" role="doc-biblioref">Hampe and Jump 2011</a>)</span>. All this knowledge will be important to prioritize the conservation measures, and to design adaptive management actions targeting these populations, in order to maintain their ecological processes and biodiversity.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-AlAallalietal1998EstudioVegetacion" class="csl-entry" role="listitem">
Al Aallali, A., J. M. López-Nieto, F. Pérez-Raya, and J. Molero-Mesa. 1998. Estudio de la vegetación forestal en la vertiente sur de <span>Sierra Nevada</span> (<span>Alpujarra Alta</span> granadina). Itinera Geobotanica 11:387–402.
</div>
<div id="ref-AlcarazSeguraetal2016ChangesVegetation" class="csl-entry" role="listitem">
Alcaraz-Segura, D., A. Reyes, and J. Cabello. 2016. Changes in vegetation productivity according to teledetection. Pages 142–145 <em>in</em> R. Zamora, A. J. Pérez-Luque, F. J. Bonet, J. M. Barea-Azcón, and R. Aspizua, editors. Global change impacts in <span>Sierra Nevada</span>: Challenges for conservation. <span>Consejería de Medio Ambiente y Ordenación del Territorio. Junta de Andalucía</span>.
</div>
<div id="ref-ggord" class="csl-entry" role="listitem">
Beck, M. W. 2020. Ggord: Ordination plots with ggplot2.
</div>
<div id="ref-Benavidesetal2013DirectIndirect" class="csl-entry" role="listitem">
Benavides, R., S. G. Rabasa, E. Granda, A. Escudero, J. A. Hódar, J. Martínez-Vilalta, A. M. Rincón, R. Zamora, and F. Valladares. 2013. <a href="https://doi.org/10.1371/journal.pone.0059824">Direct and indirect effects of climate on demography and early growth of <em><span>Pinus</span> sylvestris</em> at the rear edge: Changing roles of biotic and abiotic factors</a>. PLoS ONE 8:e59824.
</div>
<div id="ref-Benitoetal2014ClimateSimulations" class="csl-entry" role="listitem">
Benito, B. M., R. Pérez-Pérez, and P. S. Reyes-Muñoz. 2014. Climate simulations. Pages 30–31 <em>in</em> R. Aspizua, J. M. Barea-Azcón, F. Bonet, A. J. Pérez-Luque, and R. Zamora, editors. Sierra nevada global-change observatory: Monitoring methodologies. <span>Consejería de Medio Ambiente, Junta de Andalucía</span>.
</div>
<div id="ref-Benitoetal2011SimulatingPotential" class="csl-entry" role="listitem">
Benito, B., J. Lorite, and J. Peñas. 2011. <a href="https://doi.org/10.1007/s10584-010-0015-3">Simulating potential effects of climatic warming on altitudinal patterns of key species in <span>Mediterranean</span>-alpine ecosystems</a>. Climatic Change 108:471–483.
</div>
<div id="ref-BenitoGarzonetal2011IntraspecificVariability" class="csl-entry" role="listitem">
Benito-Garzón, M., R. Alía, T. M. Robson, and M. A. Zavala. 2011. <a href="https://doi.org/10.1111/j.1466-8238.2010.00646.x">Intra-specific variability and plasticity influence potential tree species distributions under climate change</a>. Global Ecology and Biogeography 20:766–778.
</div>
<div id="ref-BenitoGarzonetal2007PredictiveModelling" class="csl-entry" role="listitem">
Benito-Garzón, M., R. S. de Dios, and H. S. Ollero. 2007. <a href="https://doi.org/10.1111/j.0906-7590.2007.04813.x">Predictive modelling of tree species distributions on the <span>Iberian Peninsula</span> during the <span>Last Glacial Maximum</span> and <span>Mid</span>-<span>Holocene</span></a>. Ecography 30:120–134.
</div>
<div id="ref-BenitoGarzonetal2008EffectsClimate" class="csl-entry" role="listitem">
Benito-Garzón, M., R. S. de Dios, and H. S. Ollero. 2008. <a href="https://doi.org/10.3170/2008-7-18348">Effects of climate change on the distribution of <span>Iberian</span> tree species</a>. Applied Vegetation Science 11:169–178.
</div>
<div id="ref-BhagwatWillis2008SpeciesPersistence" class="csl-entry" role="listitem">
Bhagwat, S. A., and K. J. Willis. 2008. <a href="https://doi.org/10.1111/j.1365-2699.2007.01861.x">Species persistence in northerly glacial refugia of <span>Europe</span>: A matter of chance or biogeographical traits?</a> Journal of Biogeography 35:464–482.
</div>
<div id="ref-BirksWillis2008AlpinesTrees" class="csl-entry" role="listitem">
Birks, H. J. B., and K. J. Willis. 2008. <a href="https://doi.org/10.1080/17550870802349146">Alpines, trees, and refugia in <span>Europe</span></a>. Plant Ecology &amp; Diversity 1:147–160.
</div>
<div id="ref-Blancaetal1998ThreatenedVascular" class="csl-entry" role="listitem">
Blanca, G., M. Cueto, M. J. Martínez-Lirola, and J. Molero-Mesa. 1998. <a href="https://doi.org/10.1016/S0006-3207(97)00169-9">Threatened vascular flora of <span>Sierra Nevada</span> (<span>Southern Spain</span>)</a>. Biological Conservation 85:269–285.
</div>
<div id="ref-BlancoCastroetal2005BosquesIbericos" class="csl-entry" role="listitem">
Blanco Castro, E., M. Costa-Tenorio, C. Morla y Juaristi, and H. Sanz-Ollero. 2005. Los bosques ibéricos: Una interpretación geobotánica. <span>Planeta</span>, <span>Barcelona</span>.
</div>
<div id="ref-BlancoPastoretal2019TopographyExplains" class="csl-entry" role="listitem">
Blanco-Pastor, J. L., M. Fernández-Mazuecos, A. J. Coello, J. Pastor, and P. Vargas. 2019. <a href="https://doi.org/10.1111/ddi.12836">Topography explains the distribution of genetic diversity in one of the most fragile <span>European</span> hotspots</a>. Diversity and Distributions 25:74–89.
</div>
<div id="ref-BraunBlanquet1964PflanzensoziologieGrundzuge" class="csl-entry" role="listitem">
Braun-Blanquet, J. 1964. Pflanzensoziologie: Grundzuge der vegetationskunde. <span>Springer-Verlag</span>, <span>Wien</span>.
</div>
<div id="ref-Breweretal2002SpreadDeciduous" class="csl-entry" role="listitem">
Brewer, S., R. Cheddadi, J. L. de Beaulieu, and M. Reille. 2002. <a href="https://doi.org/10.1016/S0378-1127(01)00646-6">The spread of deciduous <em>quercus</em> throughout <span>Europe</span> since the last glacial period</a>. Forest Ecology and Management 156:27–48.
</div>
<div id="ref-CamachoOlmedoetal2002DinamicaEvolutiva" class="csl-entry" role="listitem">
Camacho-Olmedo, M., P. García-Martínez, Y. Jiménez-Olivencia, J. Menor-Toribio, and A. Paniza-Cabrera. 2002. Dinámica evolutiva del paisaje vegetal de la <span>Alta Alpujarra</span> granadina en la segunda mitad del s. <span>XX</span>. Cuadernos Geográficos 32:25–42.
</div>
<div id="ref-Castroetal2004SeedlingEstablishment" class="csl-entry" role="listitem">
Castro, J., R. Zamora, J. A. Hódar, and J. M. Gómez. 2004. Seedling establishment of a boreal tree species (<em><span>Pinus</span> sylvestris</em>) at its southernmost distribution limit: Consequences of being in a marginal <span>Mediterranean</span> habitat. Journal of Ecology:12.
</div>
<div id="ref-Chenetal2015InfluenceClimate" class="csl-entry" role="listitem">
Chen, K., I. Dorado-Liñán, L. Akhmetzyanov, G. Gea-Izquierdo, T. Zlatanov, and A. Menzel. 2015. <a href="https://doi.org/10.3354/cr01345">Influence of climate drivers and the <span>North Atlantic Oscillation</span> on beech growth at marginal sites across the <span>Mediterranean</span></a>. Climate Research 66:229–242.
</div>
<div id="ref-CMAOT2014CartografiaEvaluacion" class="csl-entry" role="listitem">
CMAOT. 2014. Cartografía y evaluación de la vegetación y flora de los ecosistemas forestales de <span>Andalucía</span> a escala de detalle (1:10000). <span>Consejería de Medio Ambiente y Ordenación del Territorio. Junta de Andalucía</span>, <span>Sevilla, Spain</span>.
</div>
<div id="ref-DeFrenneetal2013MicroclimateModerates" class="csl-entry" role="listitem">
De Frenne, P., F. Rodriguez-Sanchez, D. A. Coomes, L. Baeten, G. Verstraeten, M. Vellend, M. Bernhardt-Romermann, C. D. Brown, J. Brunet, J. Cornelis, G. M. Decocq, H. Dierschke, O. Eriksson, F. S. Gilliam, R. Hedl, T. Heinken, M. Hermy, P. Hommel, M. A. Jenkins, D. L. Kelly, K. J. Kirby, F. J. G. Mitchell, T. Naaf, M. Newman, G. Peterken, P. Petrik, J. Schultz, G. Sonnier, H. Van Calster, D. M. Waller, G.-R. Walther, P. S. White, K. D. Woods, M. Wulf, B. J. Graae, and K. Verheyen. 2013. <a href="https://doi.org/10.1073/pnas.1311190110">Microclimate moderates plant responses to macroclimate warming</a>. Proceedings of the National Academy of Sciences 110:18561–18565.
</div>
<div id="ref-delRioetal2007BioclimaticAnalysis" class="csl-entry" role="listitem">
del Río, S., L. Herrero, and Á. Penas. 2007. <a href="https://doi.org/10.1127/0340-269X/2007/0037-0541">Bioclimatic analysis of the <span><em>Quercus</em></span> <em>pyrenaica</em> forests in <span>Spain</span></a>. Phytocoenologia 37:541–560.
</div>
<div id="ref-Dionisioetal2012SatelliteBasedMonitoring" class="csl-entry" role="listitem">
Dionisio, M. A., D. Alcaraz-Segura, and J. Cabello. 2012. <a href="https://doi.org/10.5772/27711">Satellite-<span class="nocase">Based monitoring</span> of <span class="nocase">ecosystem functioning</span> in <span class="nocase">protected areas</span>: <span class="nocase">Recent trends</span> in the <span class="nocase">oak forests</span> (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.) of <span>Sierra Nevada</span> (<span>Spain</span>)</a>. Pages 355–374 International <span>Perspectives</span> on <span>Global Environmental Change</span>.
</div>
<div id="ref-DoradoLinanetal2019GeographicalAdaptation" class="csl-entry" role="listitem">
Dorado-Liñán, I., G. Piovesan, E. Martínez-Sancho, G. Gea-Izquierdo, C. Zang, I. Cañellas, D. Castagneri, A. Di Filippo, E. Gutiérrez, J. Ewald, L. Fernández-de-Uña, D. Hornstein, M. C. Jantsch, T. Levanič, K. H. Mellert, G. Vacchiano, T. Zlatanov, and A. Menzel. 2019. <a href="https://doi.org/10.1111/gcb.14544">Geographical adaptation prevails over species-specific determinism in trees’ vulnerability to climate change at <span>Mediterranean</span> rear-edge forests</a>. Global Change Biology 25:1296–1314.
</div>
<div id="ref-ElsenTingley2015GlobalMountain" class="csl-entry" role="listitem">
Elsen, P. R., and M. W. Tingley. 2015. <a href="https://doi.org/10.1038/nclimate2656">Global mountain topography and the fate of montane species under climate change</a>. Nature Climate Change 5:772–776.
</div>
<div id="ref-Fadyetal2016EvolutionbasedApproach" class="csl-entry" role="listitem">
Fady, B., F. A. Aravanopoulos, P. Alizoti, C. Mátyás, G. von Wühlisch, M. Westergren, P. Belletti, B. Cvjetkovic, F. Ducci, G. Huber, C. T. Kelleher, A. Khaldi, M. B. D. Kharrat, H. Kraigher, K. Kramer, U. Mühlethaler, S. Peric, A. Perry, M. Rousi, H. Sbay, S. Stojnic, M. Tijardovic, I. Tsvetkov, M. C. Varela, G. G. Vendramin, and T. Zlatanov. 2016. <a href="https://doi.org/10.1016/j.foreco.2016.05.015">Evolution-based approach needed for the conservation and silviculture of peripheral forest tree populations</a>. Forest Ecology and Management 375:66–75.
</div>
<div id="ref-Felicisimo2011ImpactosVulnerabilidad" class="csl-entry" role="listitem">
Felicísimo, A. M., editor. 2011. Impactos, vulnerabilidad y adaptación al cambio climático de la biodiversidad española. 2. <span>Flora</span> y vegetación. <span>Oficina Española de Cambio Climático, Ministerio de Medio Ambiente y Medio Rural y Marino</span>, <span>Madrid</span>.
</div>
<div id="ref-Franco1990Quercus" class="csl-entry" role="listitem">
Franco, A. 1990. <em>Quercus</em> <span>L</span>. Pages 15–36 <em>in</em> A. Castroviejo, M. Laínz, G. López-González, P. Montserrat, F. Muñoz-Garmendia, J. Paiva, and L. Villar, editors. Flora <span>Ibérica</span>. <span>Real Jardín Botánico, CSIC</span>, <span>Madrid</span>.
</div>
<div id="ref-Franklinetal2013ModelingPlant" class="csl-entry" role="listitem">
Franklin, J., F. W. Davis, M. Ikegami, A. D. Syphard, L. E. Flint, A. L. Flint, and L. Hannah. 2013. <a href="https://doi.org/10.1111/gcb.12051">Modeling plant species distributions under future climates: How fine scale do climate projections need to be?</a> Global Change Biology 19:473–483.
</div>
<div id="ref-candisc" class="csl-entry" role="listitem">
Friendly, M., and J. Fox. 2020. <a href="https://CRAN.R-project.org/package=candisc">Candisc: Visualizing generalized canonical discriminant and canonical correlation analysis</a>.
</div>
<div id="ref-GarciaJimenez20099230Robledales" class="csl-entry" role="listitem">
García, I., and P. Jiménez. 2009. 9230 <span>Robledales</span> de <em><span>Quercus</span> pyrenaica</em> y robledales de <em><span>Quercus</span> robur</em> y <em><span>Quercus</span> pyrenaica</em> del noroeste ibérico. Pages 1–66 <em>in</em> VV.AA., editor. Bases <span>Ecológicas</span> preliminares para la conservación de los tipos de <span>Hábitat</span> de <span>Interés Comunitario</span> en <span>España</span>. <span>Ministerio de Medio Ambiente, y Medio Rural y Marino</span>, <span>Madrid</span>.
</div>
<div id="ref-GarciaValdesetal2013ChasingMoving" class="csl-entry" role="listitem">
García-Valdés, R., M. A. Zavala, M. B. Araújo, and D. W. Purves. 2013. <a href="https://doi.org/10.1111/1365-2745.12049">Chasing a moving target: Projecting climate change-induced shifts in non-equilibrial tree species distributions</a>. Journal of Ecology 101:441–453.
</div>
<div id="ref-Gavilanetal2000EffectsDisturbance" class="csl-entry" role="listitem">
Gavilán, R. G., A. Escudero, and A. Rubio. 2000. Effects of disturbance on floristic patterns of <em><span>Quercus</span> pyrenaica</em> forests in <span>Central Spain</span>. Pages 226–229 Proceedings <span>IAVS Symposium</span>. <span>International Association for Vegetation Science</span>, <span>Uppsala</span>.
</div>
<div id="ref-Gavilanetal2007ModellingCurrent" class="csl-entry" role="listitem">
Gavilán, R. G., D. S. Mata, B. Vilches, and G. Entrocassi. 2007. <a href="https://doi.org/doi:10.1127/0340-269X/2007/0037-0561">Modelling current distribution of <span>Spanish</span> <em><span>Q</span>uercus</em> <em>pyrenaica</em> forests using climatic parameters</a>. Phytocoenologia 37:561–581.
</div>
<div id="ref-Gavinetal2014ClimateRefugia" class="csl-entry" role="listitem">
Gavin, D. G., M. C. Fitzpatrick, P. F. Gugger, K. D. Heath, F. Rodríguez-Sánchez, S. Z. Dobrowski, A. Hampe, F. S. Hu, M. B. Ashcroft, P. J. Bartlein, J. L. Blois, B. C. Carstens, E. B. Davis, G. de Lafontaine, M. E. Edwards, M. Fernandez, P. D. Henne, E. M. Herring, Z. A. Holden, W. Kong, J. Liu, D. Magri, N. J. Matzke, M. S. McGlone, F. Saltré, A. L. Stigall, Y.-H. E. Tsai, and J. W. Williams. 2014. <a href="https://doi.org/10.1111/nph.12929">Climate refugia: Joint inference from fossil records, species distribution models and phylogeography</a>. New Phytologist 204:37–54.
</div>
<div id="ref-GeaIzquierdoCanellas2014LocalClimate" class="csl-entry" role="listitem">
Gea-Izquierdo, G., and I. Cañellas. 2014. <a href="https://doi.org/10.1007/s10021-013-9719-3">Local climate forces instability in long-term productivity of a <span>Mediterranean</span> oak along climatic gradients</a>. Ecosystems 17:228–241.
</div>
<div id="ref-GeaIzquierdoetal2013GrowthProjections" class="csl-entry" role="listitem">
Gea-Izquierdo, G., L. Fernández-de-Uña, and I. Cañellas. 2013. <a href="https://doi.org/10.1016/j.foreco.2013.05.058">Growth projections reveal local vulnerability of <span>Mediterranean</span> oaks with rising temperatures</a>. Forest Ecology and Management 305:282–293.
</div>
<div id="ref-GeaIzquierdoetal2017RiskyFuture" class="csl-entry" role="listitem">
Gea-Izquierdo, G., A. Nicault, G. Battipaglia, I. Dorado-Liñán, E. Gutiérrez, M. Ribas, and J. Guiot. 2017. <a href="https://doi.org/10.1111/gcb.13597">Risky future for <span>Mediterranean</span> forests unless they undergo extreme carbon fertilization</a>. Global Change Biology 23:2915–2927.
</div>
<div id="ref-GomezLunt2007RefugiaRefugia" class="csl-entry" role="listitem">
Gómez, A., and D. H. Lunt. 2007. <a href="https://doi.org/10.1007/1-4020-4904-8_5">Refugia within refugia: Patterns of phylogeographic concordance in the <span>Iberian Peninsula</span></a>. Pages 155–188 <em>in</em> S. Weiss and N. Ferrand, editors. Phylogeography of southern <span>European</span> refugia. <span>Springer Netherlands</span>, <span>Dordrecht</span>.
</div>
<div id="ref-Gomez2003SpatialPatterns" class="csl-entry" role="listitem">
Gómez, J. M. 2003. <a href="https://doi.org/10.1034/j.1600-0587.2003.03586.x">Spatial patterns in long-distance dispersal of <span><em>Quercus ilex</em></span> acorns by jays in a heterogeneous landscape</a>. Ecography 26:573–584.
</div>
<div id="ref-Gomezetal2001ProblemasRegeneracion" class="csl-entry" role="listitem">
Gómez, J. M., L. Gómez-Aparicio, R. Zamora, and J. Montes. 2001. Problemas de regeneración de especies forestales autóctonas en el espacio natural protegido de <span>Sierra Nevada</span>. <span>Sociedad Española de Ciencias Forestales</span>, <span>Granada</span>.
</div>
<div id="ref-Gomez2003ImpactVertebrate" class="csl-entry" role="listitem">
Gómez, J., G. Daniel, and Z. Regino. 2003. <a href="https://doi.org/10.1016/S0378-1127(02)00608-4">Impact of vertebrate acorn- and seedling-predators on a <span>Mediterranean <em>Quercus</em></span> <em>pyrenaica</em> forest</a>. Forest Ecology and Management 180:125–134.
</div>
<div id="ref-GomezAparicioetal2008OakSeedling" class="csl-entry" role="listitem">
Gómez-Aparicio, L., I. M. Pérez-Ramos, I. Mendoza, L. Matías, J. L. Quero, J. Castro, R. Zamora, and T. Marañón. 2008. <a href="https://doi.org/10.1111/j.1600-0706.2008.16814.x">Oak seedling survival and growth along resource gradients in <span>Mediterranean</span> forests: Implications for regeneration in current and future environmental scenarios</a>. Oikos 117:1683–1699.
</div>
<div id="ref-GuisanThuiller2005PredictingSpecies" class="csl-entry" role="listitem">
Guisan, A., and W. Thuiller. 2005. <a href="https://doi.org/10.1111/j.1461-0248.2005.00792.x">Predicting species distribution: Offering more than simple habitat models</a>. Ecology Letters 8:993–1009.
</div>
<div id="ref-Guisanetal1999GLMCCA" class="csl-entry" role="listitem">
Guisan, A., S. B. Weiss, and A. D. Weiss. 1999. <a href="https://doi.org/10.1023/A:1009841519580"><span>GLM</span> versus <span>CCA</span> spatial modeling of plant species distribution</a>. Plant Ecology 143:107–122.
</div>
<div id="ref-GuisanZimmermann2000PredictiveHabitat" class="csl-entry" role="listitem">
Guisan, A., and N. E. Zimmermann. 2000. <a href="https://doi.org/10.1016/S0304-3800(00)00354-9">Predictive habitat distribution models in ecology</a>. Ecological Modelling 135:147–186.
</div>
<div id="ref-HampeJump2011ClimateRelicts" class="csl-entry" role="listitem">
Hampe, A., and A. S. Jump. 2011. <a href="https://doi.org/10.1146/annurev-ecolsys-102710-145015">Climate relicts: Past, present, future</a>. Annual Review of Ecology, Evolution, and Systematics 42:313–333.
</div>
<div id="ref-HampePetit2005ConservingBiodiversity" class="csl-entry" role="listitem">
Hampe, A., and R. J. Petit. 2005. <a href="https://doi.org/10.1111/j.1461-0248.2005.00739.x">Conserving biodiversity under climate change: The rear edge matters</a>. Ecology Letters 8:461–467.
</div>
<div id="ref-Hannahetal2014FinegrainModeling" class="csl-entry" role="listitem">
Hannah, L., L. Flint, A. D. Syphard, M. A. Moritz, L. B. Buckley, and I. M. McCullough. 2014. <a href="https://doi.org/10.1016/j.tree.2014.04.006">Fine-grain modeling of species’ response to climate change: Holdouts, stepping-stones, and microrefugia</a>. Trends in Ecology &amp; Evolution 29:390–397.
</div>
<div id="ref-JimenezOlivencia1991PaisajesSierra" class="csl-entry" role="listitem">
Jiménez Olivencia, Y. 1991. Los paisajes de <span>Sierra Nevada</span>: Cartografía de los sistemas naturales de una montaña mediterránea. <span>Universidad de Granada</span>, <span>Granada</span>.
</div>
<div id="ref-Jumpetal2010MonitoringManaging" class="csl-entry" role="listitem">
Jump, A. S., L. Cavin, and P. D. Hunter. 2010. Monitoring and managing responses to climate change at the retreating range edge of forest trees. Journal of Environmental Monitoring 12:1791–1798.
</div>
<div id="ref-ggpubr" class="csl-entry" role="listitem">
Kassambara, A. 2020. <a href="https://CRAN.R-project.org/package=ggpubr">Ggpubr: ’ggplot2’ based publication ready plots</a>.
</div>
<div id="ref-factoextra" class="csl-entry" role="listitem">
Kassambara, A., and F. Mundt. 2020. <a href="https://CRAN.R-project.org/package=factoextra">Factoextra: Extract and visualize the results of multivariate data analyses</a>.
</div>
<div id="ref-Kohleretal2014MountainsClimate" class="csl-entry" role="listitem">
Kohler, T., A. Wehrli, and M. Jurek, editors. 2014. Mountains and climate change: A global concern. <span>Centre for Development and Environment, Swiss Agency for Development and Cooperation and Geographica Bernensia</span>, <span>Bern</span>.
</div>
<div id="ref-KornerSpehn2019HumboldtianView" class="csl-entry" role="listitem">
Körner, C., and E. Spehn. 2019. <a href="https://doi.org/10.1126/science.aaz4161">A <span>Humboldtian</span> view of mountains</a>. Science 365:1061–1061.
</div>
<div id="ref-Krebs1999EcologicalMethodology" class="csl-entry" role="listitem">
Krebs, C. J. 1999. Ecological methodology. 2nd ed. <span>Benjamin/Cummings</span>, <span>Menlo Park, Calif</span>.
</div>
<div id="ref-Kruskal1964NonmetricMultidimensional" class="csl-entry" role="listitem">
Kruskal, J. B. 1964. <a href="https://doi.org/10.1007/BF02289694">Nonmetric multidimensional scaling: <span>A</span> numerical method</a>. Psychometrika 29:115–129.
</div>
<div id="ref-Lindneretal2010ClimateChange" class="csl-entry" role="listitem">
Lindner, M., M. Maroschek, S. Netherer, A. Kremer, A. Barbati, J. Garcia-Gonzalo, R. Seidl, S. Delzon, P. Corona, M. Kolström, M. J. Lexer, and M. Marchetti. 2010. <a href="https://doi.org/10.1016/j.foreco.2009.09.023">Climate change impacts, adaptive capacity, and vulnerability of <span>European</span> forest ecosystems</a>. Forest Ecology and Management 259:698–709.
</div>
<div id="ref-Loetal2010WordCaution" class="csl-entry" role="listitem">
Lo, Y.-H., J. A. Blanco, and J. P. (Hamish). Kimmins. 2010. <a href="https://doi.org/10.5558/tfc86312-3">A word of caution when planning forest management using projections of tree species range shifts</a>. The Forestry Chronicle 86:312–316.
</div>
<div id="ref-LopezTiradoHidalgo2014HighResolution" class="csl-entry" role="listitem">
López-Tirado, J., and P. J. Hidalgo. 2014. <a href="https://doi.org/10.1016/j.foreco.2014.07.009">A high resolution predictive model for relict trees in the <span>Mediterranean</span>-mountain forests (<em><span>Pinus</span> sylvestris</em> <span>L</span>., <em><span>P</span>. Nigra</em> <span>Arnold</span> and <em><span>Abies</span> pinsapo</em> <span>Boiss</span>.) from the south of <span>Spain</span>: <span>A</span> reliable management tool for reforestation</a>. Forest Ecology and Management 330:105–114.
</div>
<div id="ref-Loriteetal2008PhytosociologicalReview" class="csl-entry" role="listitem">
Lorite, J., C. Salazar, J. Peñast, and F. Valle. 2008. <a href="https://doi.org/10.1080/12538078.2008.10516105">Phytosociological review on the forests of <em><span>Q</span>uercus pyrenaica</em> <span>Willd</span>.</a> Acta Botanica Gallica 155:219–233.
</div>
<div id="ref-MartinezParrasMoleroMesa1982EcologiaFitosociologia" class="csl-entry" role="listitem">
Martínez-Parras, J. M., and J. Molero-Mesa. 1982. Ecología y fitosociología de <em><span>Q</span>uercus pyrenaica</em> <span>Willd</span>. En la provincia <span>Bética</span>. <span>Los</span> melojares béticos y sus etapas de sustitución. Lazaroa 4:91–104.
</div>
<div id="ref-Matiasetal2017ContrastingGrowth" class="csl-entry" role="listitem">
Matías, L., J. C. Linares, A. Sánchez-Miranda, and A. S. Jump. 2017. <a href="https://doi.org/10.1111/gcb.13627">Contrasting growth forecasts across the geographical range of <span>Scots</span> pine due to altitudinal and latitudinal differences in climatic sensitivity</a>. Global Change Biology 23:4106–4116.
</div>
<div id="ref-McElhinnyetal2005ForestWoodland" class="csl-entry" role="listitem">
McElhinny, C., P. Gibbons, C. Brack, and J. Bauhus. 2005. <a href="https://doi.org/10.1016/j.foreco.2005.08.034">Forest and woodland stand structural complexity: <span>Its</span> definition and measurement</a>. Forest Ecology and Management 218:1–24.
</div>
<div id="ref-MedailDiadema2009GlacialRefugia" class="csl-entry" role="listitem">
Médail, F., and K. Diadema. 2009. <a href="https://doi.org/10.1111/j.1365-2699.2008.02051.x">Glacial refugia influence plant diversity patterns in the <span>Mediterranean Basin</span></a>. Journal of Biogeography 36:1333–1345.
</div>
<div id="ref-MeineriHylander2017FinegrainLargedomain" class="csl-entry" role="listitem">
Meineri, E., and K. Hylander. 2017. <a href="https://doi.org/10.1111/ecog.02494">Fine-grain, large-domain climate models based on climate station and comprehensive topographic information improve microrefugia detection</a>. Ecography 40:1003–1013.
</div>
<div id="ref-Mendozaetal2009SeedingExperiment" class="csl-entry" role="listitem">
Mendoza, I., R. Zamora, and J. Castro. 2009. <a href="https://doi.org/10.1016/j.biocon.2009.02.018">A seeding experiment for testing tree-community recruitment under variable environments: Implications for forest regeneration and conservation in <span>Mediterranean</span> habitats</a>. Biological Conservation 142:1491–1499.
</div>
<div id="ref-Minchin1987SimulationMultidimensional" class="csl-entry" role="listitem">
Minchin, P. R. 1987. <a href="https://doi.org/10.1007/BF00039167">Simulation of multidimensional community patterns: Towards a comprehensive model</a>. Vegetatio 71:145–156.
</div>
<div id="ref-ellipse" class="csl-entry" role="listitem">
Murdoch, D., and E. D. Chow. 2020. <a href="https://CRAN.R-project.org/package=ellipse">Ellipse: Functions for drawing ellipses and ellipse-like confidence regions</a>.
</div>
<div id="ref-NavarroGonzalezetal2013WeightLanduse" class="csl-entry" role="listitem">
Navarro-González, I., A. J. Pérez-Luque, F. J. Bonet, and R. Zamora. 2013. <a href="https://doi.org/10.1890/12-0459.1">The weight of the past: Land-use legacies and recolonization of pine plantations by oak trees</a>. Ecological Applications 23:1267–1276.
</div>
<div id="ref-Neteleretal2012GRASSGIS" class="csl-entry" role="listitem">
Neteler, M., M. H. Bowman, M. Landa, and M. Metz. 2012. <a href="https://doi.org/10.1016/j.envsoft.2011.11.014"><span>GRASS GIS</span>: <span>A</span> multi-purpose open source <span>GIS</span></a>. Environmental Modelling &amp; Software 31:124–130.
</div>
<div id="ref-Ninyerolaetal2000MethodologicalApproach" class="csl-entry" role="listitem">
Ninyerola, M., X. Pons, and J. M. Roure. 2000. A methodological approach of climatological modelling of air temperature and precipitation through <span>GIS</span> techniques. International Journal of Climatology 20:1823–1841.
</div>
<div id="ref-Oksanen2013MultivariateAnalysis" class="csl-entry" role="listitem">
Oksanen, J. 2013. <a href="http://phylodiversity.net/azanne/csfar/images/8/85/Vegan.pdf">Multivariate <span>Analysis</span> of <span>Ecological Communities</span> in <span>R</span>: <span>Vegan Tutorial</span></a>.
</div>
<div id="ref-vegan" class="csl-entry" role="listitem">
Oksanen, J., F. G. Blanchet, M. Friendly, R. Kindt, P. Legendre, D. McGlinn, P. R. Minchin, R. B. O’Hara, G. L. Simpson, P. Solymos, M. H. H. Stevens, E. Szoecs, and H. Wagner. 2019. <a href="https://CRAN.R-project.org/package=vegan">Vegan: Community ecology package</a>.
</div>
<div id="ref-Olaldeetal2002WhiteOaks" class="csl-entry" role="listitem">
Olalde, M., A. Herrán, S. Espinel, and P. G. Goicoechea. 2002. <a href="https://doi.org/10.1016/S0378-1127(01)00636-3">White oaks phylogeography in the <span>Iberian Peninsula</span></a>. Forest Ecology and Management 156:89–102.
</div>
<div id="ref-Oldfatheretal2020RangeEdges" class="csl-entry" role="listitem">
Oldfather, M. F., M. M. Kling, S. N. Sheth, N. C. Emery, and D. D. Ackerly. 2020. <a href="https://doi.org/10.1111/gcb.14897">Range edges in heterogeneous landscapes: <span>Integrating</span> geographic scale and climate complexity into range dynamics</a>. Global Change Biology 26:1055–1067.
</div>
<div id="ref-Payneetal2017OpportunitiesResearch" class="csl-entry" role="listitem">
Payne, D., E. M. Spehn, M. Snethlage, and M. Fischer. 2017. <a href="https://doi.org/10.1016/j.cosust.2017.11.001">Opportunities for research on mountain biodiversity under global change</a>. Current Opinion in Environmental Sustainability 29:40–47.
</div>
<div id="ref-patchwork" class="csl-entry" role="listitem">
Pedersen, T. L. 2020. <a href="https://CRAN.R-project.org/package=patchwork">Patchwork: The composer of plots</a>.
</div>
<div id="ref-Pereiraetal2016SpatialInterpolation" class="csl-entry" role="listitem">
Pereira, P., M. Oliva, and I. Misiune. 2016. <a href="https://doi.org/10.1007/s00704-015-1606-8">Spatial interpolation of precipitation indexes in <span>Sierra Nevada</span> (<span>Spain</span>): Comparing the performance of some interpolation methods</a>. Theoretical and Applied Climatology 126:683–698.
</div>
<div id="ref-PerezLuqueetal2014SinfonevadaDataset" class="csl-entry" role="listitem">
Pérez-Luque, A. J., F. J. Bonet, R. Pérez-Pérez, R. Aspizua, J. Lorite, and R. Zamora. 2014. <a href="https://doi.org/10.3897/phytokeys.35.6363">Sinfonevada: <span>Dataset</span> of floristic diversity in <span>Sierra Nevada</span> forests (<span>SE Spain</span>)</a>. PhytoKeys 35:1–15.
</div>
<div id="ref-PerezLuqueetal2019MapEcosystems" class="csl-entry" role="listitem">
Pérez-Luque, A. J., F. J. Bonet-García, and R. Zamora Rodríguez. 2019. <a href="https://doi.org/10.1594/PANGAEA.910176">Map of ecosystems types in <span>Sierra Nevada</span> mountain (southern <span>Spain</span>)</a>. data set, <span>PANGAEA</span>.
</div>
<div id="ref-PerezLuqueetal2020LanduseLegacies" class="csl-entry" role="listitem">
Pérez-Luque, A. J., G. Gea-Izquierdo, and R. Zamora. 2020. <a href="https://doi.org/10.1007/s10021-020-00547-y">Land-use legacies and climate change as a double challenge to oak forest resilience: Mismatches of geographical and ecological rear edges</a>. Ecosystems.
</div>
<div id="ref-PerezLuqueetal2015OntologicalSystem" class="csl-entry" role="listitem">
Pérez-Luque, A. J., R. Pérez-Pérez, F. J. Bonet-García, and P. J. Magaña. 2015. <a href="https://doi.org/10.1016/j.jag.2014.09.003">An ontological system based on <span>MODIS</span> images to assess ecosystem functioning of <span>Natura</span> 2000 habitats: <span>A</span> case study for <em><span>Quercus</span> pyrenaica</em> forests</a>. International Journal of Applied Earth Observation and Geoinformation 37:142–151.
</div>
<div id="ref-Petitetal2002IdentificationRefugia" class="csl-entry" role="listitem">
Petit, R. J., S. Brewer, S. Bordacs, K. Burg, R. Cheddadi, E. Coart, J. Cottrell, U. M. Csaikl, B. van Dam, J. D. Deans, S. Espinel, S. Fineschi, R. Finkeldey, I. Glaz, P. G. Goicoechea, J. S. Jensen, A. O. Konig, A. J. Lowe, S. F. Madsen, G. Matyas, R. C. Munro, F. Popescu, D. Slade, H. Tabbener, B. Ziegenhagen, J.-L. de Beaulieu, and A. Kremer. 2002. Identification of refugia and post-glacial colonisation routes of <span>European</span> white oaks based on chloroplast <span>DNA</span> and fossil pollen evidence. Forest Ecology and Management:26.
</div>
<div id="ref-Pirononetal2015GeographicClimatic" class="csl-entry" role="listitem">
Pironon, S., J. Villellas, W. F. Morris, D. F. Doak, and M. B. García. 2015. <a href="https://doi.org/10.1111/geb.12263">Do geographic, climatic or historical ranges differentiate the performance of central versus peripheral populations?: <span>The</span> centre-periphery hypothesis: New perspectives</a>. Global Ecology and Biogeography 24:611–620.
</div>
<div id="ref-Potteretal2013MicroclimaticChallenges" class="csl-entry" role="listitem">
Potter, K. A., H. Arthur Woods, and S. Pincebourde. 2013. <a href="https://doi.org/10.1111/gcb.12257">Microclimatic challenges in global change biology</a>. Global Change Biology 19:2932–2939.
</div>
<div id="ref-base" class="csl-entry" role="listitem">
R Core Team. 2020. <a href="https://www.R-project.org/">R: A language and environment for statistical computing</a>. R Foundation for Statistical Computing, Vienna, Austria.
</div>
<div id="ref-nFactors" class="csl-entry" role="listitem">
Raiche, G., and D. Magis. 2020. <a href="https://CRAN.R-project.org/package=nFactors">nFactors: Parallel analysis and other non graphical solutions to the cattell scree test</a>.
</div>
<div id="ref-Rehmetal2015LosingYour" class="csl-entry" role="listitem">
Rehm, E. M., P. Olivas, J. Stroud, and K. J. Feeley. 2015. <a href="https://doi.org/10.1002/ece3.1645">Losing your edge: Climate change and the conservation value of range-edge populations</a>. Ecology and Evolution 5:4315–4326.
</div>
<div id="ref-delRioetal2003IndicesStand" class="csl-entry" role="listitem">
Rio, M. del, F. Montes, I. Cañellas, and G. Montero. 2003. Índices de diversidad estructural en masas forestales. Forest Systems 12:159–176.
</div>
<div id="ref-delRioetal2016CharacterizationStructure" class="csl-entry" role="listitem">
Río, M. del, H. Pretzsch, I. Alberdi, K. Bielak, F. Bravo, A. Brunner, S. Condés, M. J. Ducey, T. Fonseca, N. von Lüpke, M. Pach, S. Peric, T. Perot, Z. Souidi, P. Spathelf, H. Sterba, M. Tijardovic, M. Tomé, P. Vallet, and A. Bravo-Oviedo. 2016. <a href="https://doi.org/10.1007/s10342-015-0927-6">Characterization of the structure, dynamics, and productivity of mixed-species stands: Review and perspectives</a>. European Journal of Forest Research 135:23–49.
</div>
<div id="ref-RodriguezSanchezetal2010TreeRange" class="csl-entry" role="listitem">
Rodríguez-Sánchez, F., A. Hampe, P. Jordano, and J. Arroyo. 2010. <a href="https://doi.org/10.1016/j.revpalbo.2010.03.008">Past tree range dynamics in the <span>Iberian Peninsula</span> inferred through phylogeography and palaeodistribution modelling: <span>A</span> review</a>. Review of Palaeobotany and Palynology 162:507–521.
</div>
<div id="ref-RuizBenitoetal2013PatternsDrivers" class="csl-entry" role="listitem">
Ruiz-Benito, P., E. R. Lines, L. Gómez-Aparicio, M. A. Zavala, and D. A. Coomes. 2013. <a href="https://doi.org/10.1371/journal.pone.0056843">Patterns and drivers of tree mortality in iberian forests: Climatic effects are modified by competition</a>. PLoS ONE 8:e56843.
</div>
<div id="ref-RuizLabourdetteetal2013ChangesTree" class="csl-entry" role="listitem">
Ruiz-Labourdette, D., M. F. Schmitz, and F. D. Pineda. 2013. <a href="https://doi.org/10.1016/j.ecolind.2012.06.021">Changes in tree species composition in <span>Mediterranean</span> mountains under climate change: <span>Indicators</span> for conservation planning</a>. Ecological Indicators 24:310–323.
</div>
<div id="ref-SanchezdeDiosetal2009PresentFuture" class="csl-entry" role="listitem">
Sánchez de Dios, R., M. Benito-Garzón, and H. Sainz-Ollero. 2009. <a href="https://doi.org/10.1007/s11258-009-9584-5">Present and future extension of the <span>Iberian</span> submediterranean territories as determined from the distribution of marcescent oaks</a>. Plant Ecology 204:189–205.
</div>
<div id="ref-SpehnKorner2009MountainLaboratory" class="csl-entry" role="listitem">
Spehn, E., and C. Korner. 2009. <a href="https://doi.org/10.1201/9781420083705.ch16">The mountain laboratory of naturea largely unexplored mine of information synthesis of the book</a>. Pages 165–169 <em>in</em> E. Spehn and C. Korner, editors. Data <span>Mining</span> for <span>Global Trends</span> in <span>Mountain Biodiversity</span>. <span>CRC Press</span>.
</div>
<div id="ref-Titoetal2020MountainEcosystems" class="csl-entry" role="listitem">
Tito, R., H. L. Vasconcelos, and K. J. Feeley. 2020. <a href="https://doi.org/10.3389/ffgc.2020.00038">Mountain ecosystems as natural laboratories for climate change experiments</a>. Frontiers in Forests and Global Change 3:38.
</div>
<div id="ref-Urbietaetal2011MediterraneanPine" class="csl-entry" role="listitem">
Urbieta, I. R., L. V. Garćıa, M. A. Zavala, and T. Marañón. 2011. <a href="https://doi.org/10.1111/j.1654-1103.2010.01222.x">Mediterranean pine and oak distribution in southern <span>Spain</span>: Is there a mismatch between regeneration and adult distribution?</a> Journal of Vegetation Science 22:18–31.
</div>
<div id="ref-Urbietaetal2008SoilWater" class="csl-entry" role="listitem">
Urbieta, I. R., I. M. Pérez-Ramos, M. A. Zavala, T. Marañón, and R. K. Kobe. 2008. <a href="https://doi.org/10.1139/X08-089">Soil water content and emergence time control seedling establishment in three co-occurring <span>Mediterranean</span> oak species</a>. Canadian Journal of Forest Research 38:2382–2393.
</div>
<div id="ref-ValbuenaCarabanaGil2011EvaluacionEstructura" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., and L. Gil. 2011. Evaluación de la estructura genética de poblaciones marginales de <em>quercus pyrenaica</em> willd. Y su evolución. Implicaciones para la conservación de sus recursos genéticos. Pages 175–204 <em>in</em> L. Ramírez and B. Asensio, editors. Proyectos de investigación en parques nacionales, 2007-2010. <span>Organismo Autónomo Parques Nacionales (Spain)</span>, <span>Madrid</span>.
</div>
<div id="ref-ValbuenaCarabanaGil2013GeneticResilience" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., and L. Gil. 2013. <a href="https://doi.org/10.1007/s11295-013-0614-z">Genetic resilience in a historically profited root sprouting oak (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.) at its southern boundary</a>. Tree Genetics &amp; Genomes 9:1129–1142.
</div>
<div id="ref-ValbuenaCarabanaGil2017CentenaryCoppicing" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., and L. Gil. 2017. <a href="https://doi.org/10.1007/s11295-017-1105-4">Centenary coppicing maintains high levels of genetic diversity in a root resprouting oak (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>.)</a>. Tree Genetics &amp; Genomes 13:28.
</div>
<div id="ref-ValbuenaCarabanaetal2005GeneFlow" class="csl-entry" role="listitem">
Valbuena-Carabaña, M., S. C. González-Martínez, V. L. Sork, C. Collada, A. Soto, P. G. Goicoechea, and L. Gil. 2005. <a href="https://doi.org/10.1038/sj.hdy.6800752">Gene flow and hybridisation in a mixed oak forest (<em><span>Quercus</span> pyrenaica</em> <span>Willd</span>. And <em><span>Quercus</span> petraea</em> (<span>Matts</span>.) <span>Liebl</span>.) in central <span>Spain</span></a>. Heredity 95:457–465.
</div>
<div id="ref-MASS" class="csl-entry" role="listitem">
Venables, W. N., and B. D. Ripley. 2002. <a href="http://www.stats.ox.ac.uk/pub/MASS4">Modern applied statistics with s</a>. Fourth. Springer, New York.
</div>
<div id="ref-Virtanenetal2006BroadScale" class="csl-entry" role="listitem">
Virtanen, R., J. Oksanen, L. Oksanen, and V. Y. Razzhivin. 2006. <a href="https://doi.org/10.1111/j.1654-1103.2006.tb02473.x">Broad-scale vegetation-environment relationships in <span>Eurasian</span> high-latitude areas</a>. Journal of Vegetation Science 17:519–528.
</div>
<div id="ref-Williamsetal2012WhichEnvironmental" class="csl-entry" role="listitem">
Williams, K. J., L. Belbin, M. P. Austin, J. L. Stein, and S. Ferrier. 2012. <a href="https://doi.org/10.1080/13658816.2012.698015">Which environmental variables should <span>I</span> use in my biodiversity model?</a> International Journal of Geographical Information Science 26:2009–2047.
</div>
<div id="ref-Zamoraetal2017GlobalChange" class="csl-entry" role="listitem">
Zamora, R., A. J. Pérez-Luque, F. J. Bonet, J. M. Barea-Azcón, R. Aspizua, F. J. Sánchez-Gutiérrez, F. J. Cano-Manuel, B. Ramos-Losada, and I. Henares-Civantos. 2017. <a href="https://doi.org/10.1002/bes2.1308">Global change impacts in the <span>Sierra Nevada Long</span>-<span>Term Ecological Research Site</span> (southern <span>Spain</span>)</a>. The Bulletin of the Ecological Society of America 98:157–164.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chap02-metodologia.html" class="pagination-link" aria-label="Metodología general">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Metodología general</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chap04-coloniza.html" class="pagination-link" aria-label="Colonization pattern of abandoned croplands by *Q. pyrenaica* in a Mediterranean mountain region">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Colonization pattern of abandoned croplands by <em>Q. pyrenaica</em> in a Mediterranean mountain region</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>